'use strict';
const assert=require('assert');
const svc=require('../SERVICES/orion/FederalSourceReadinessAuditService');
assert.deepStrictEqual(svc.firstPresentEnv({SAM_API_KEY:'abc'},['SAM_API_KEY']),{present:true,envName:'SAM_API_KEY',length:3,value:'abc'});
assert.strictEqual(svc.mmddyyyy(new Date('2026-08-30T12:00:00Z')),'08/30/2026');
const fs=require('fs'),path=require('path');
const src=fs.readFileSync(path.join(__dirname,'..','SERVICES','orion','FederalSourceReadinessAuditService.js'),'utf8');
assert(src.includes('secretValuesLogged:false'));
assert(src.includes('webScraping:false'));
assert(src.includes('officialApisOnly:true'));
assert(src.includes('bulkStrategyRequired:true'));
assert(!src.includes('console.log(key.value)'));
console.log('FEDERAL_SOURCE_READINESS_AUDIT_TEST_PASS');
