'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const readiness=fs.readFileSync(path.join(root,'SERVICES','orion','FederalSourceReadinessAuditService.js'),'utf8');
const acquire=fs.readFileSync(path.join(root,'SERVICES','orion','SamBulkExtractAcquisitionService.js'),'utf8');
const policy=JSON.parse(fs.readFileSync(path.join(root,'CONFIG','GOVERNMENT_DATA','sam_lead_eligibility_policy.json'),'utf8'));
const Eligibility=require(path.join(root,'SERVICES','orion','SamLeadEligibilityService.js'));
assert(readiness.includes('useBulkExtractForOrionScaleRefresh:true'));
assert(readiness.includes('automated401DoesNotInvalidateUserConfirmedKey:true'));
assert(readiness.includes('SAM_ENTITY_PUBLIC_BULK_EXTRACT_NOT_DISCOVERED'));
assert(readiness.includes('ContractOpportunitiesFullCSV.csv'));
assert(readiness.includes('GSA eLibrary'));
assert(acquire.includes('SAM_PUBLIC_UTF-8_MONTHLY_V2_'));
assert(acquire.includes('publicDataServicesOnly:true'));
assert(acquire.includes('samApiKeyUsed:false'));
assert(acquire.includes('productionDatabaseModified:false'));
assert(policy.hardExcludedNaicsPrefixes.includes('31'));
assert(policy.hardExcludedNaicsPrefixes.includes('32'));
assert(policy.hardExcludedNaicsPrefixes.includes('33'));
assert(policy.segmentPriority[0]==='EXPIRED_EVERYTHING');
assert(policy.segmentPriority.includes('SAM'));
const gate=new Eligibility({rootDir:root,policy});
assert.equal(gate.evaluate({registrationStatus:'A',forProfit:true,primaryNaics:'541611',businessTypes:'For Profit Organization',legalName:'Example Consulting LLC'}).status,'ELIGIBLE');
assert.equal(gate.evaluate({registrationStatus:'A',forProfit:false,primaryNaics:'541611',businessTypes:'Non Profit Organization',legalName:'Example Foundation'}).status,'REJECTED');
assert.equal(gate.evaluate({registrationStatus:'A',forProfit:true,primaryNaics:'541611',businessTypes:'State Government',legalName:'State Agency'}).status,'REJECTED');
assert.equal(gate.evaluate({registrationStatus:'A',forProfit:true,primaryNaics:'332710',businessTypes:'For Profit Organization',legalName:'Precision Manufacturing LLC'}).status,'REJECTED');
assert.equal(gate.evaluate({registrationStatus:'A',forProfit:true,primaryNaics:'722511',businessTypes:'For Profit Organization',legalName:'Main Street Restaurant'}).status,'REJECTED');
console.log('SAM_BULK_REFRESH_STRATEGY_TEST=PASS');
