"use strict";
const assert=require("assert"),fs=require("fs"),os=require("os"),path=require("path");
const Service=require("../SERVICES/revenue/RevenueOutboundRemediationPlanService");
const {parseArguments}=require("../SCRIPTS/PlanRevenueOutboundRemediation");
let passed=0;async function test(name,fn){await fn();passed++;console.log("[PASS] "+name);}
(async()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),"miles-remediation-"));const auditPath=path.join(root,"audit.json"),outputRoot=path.join(root,"out");
 const names=["Expiring GSA 12 Months","Expiring VA 12 Months","GSA","VA","8(a)","HUBZone","SDVOSB","VOSB","WOSB","SBS"];
 const routes=names.map((route,i)=>({route,campaignId:"c"+i,messageSteps:i===2?2:i===9?5:0,ready:i===9,blockers:i===9?[]:["FOUR_STEP_SEQUENCE_REQUIRED",...([3,4,5,6,7,8].includes(i)?["STOP_ON_REPLY_REQUIRED"]:[]),...([2,3,4,5,6,7,8].includes(i)?["STOP_ON_AUTO_REPLY_REQUIRED"]:[])]}));
 fs.writeFileSync(auditPath,JSON.stringify({ok:true,status:"OUTBOUND_READINESS_AUDITED",readinessFingerprint:"278C79A52A620522295BB9848E11A223FFA3B3BACFBC67079CBBB4EFAAE2F1A6",summary:{campaignsAudited:10},routes}),"utf8");
 const service=new Service({rootDir:root,auditPath,outputRoot,generatedAt:()=>"2026-08-08T00:00:00.000Z"});
 await test("service is constructable",()=>assert.ok(service));
 const preview=service.build({});
 await test("default mode is plan-only",()=>assert.strictEqual(preview.mode,"PLAN_ONLY"));
 await test("preview performs no writes",()=>assert.strictEqual(fs.existsSync(outputRoot),false));
 await test("preview authorizes no provider writes",()=>assert.strictEqual(preview.providerWritesAuthorized,false));
 const report=service.build({apply:true});
 await test("remediation plan completes",()=>assert.strictEqual(report.status,"OUTBOUND_REMEDIATION_PLANNED"));
 await test("nine campaigns require remediation",()=>assert.strictEqual(report.summary.campaignsToRemediate,9));
 await test("nine sequences are planned",()=>assert.strictEqual(report.summary.sequencesToInstall,9));
 await test("six stop-on-reply updates are planned",()=>assert.strictEqual(report.summary.stopOnReplyUpdates,6));
 await test("seven auto-reply updates are planned",()=>assert.strictEqual(report.summary.stopOnAutoReplyUpdates,7));
 await test("ready SBS campaign is preserved",()=>assert.strictEqual(report.summary.readyCampaignsPreserved,1));
 await test("each new sequence has four steps",()=>assert.ok(report.routes.filter(r=>r.proposedSequence).every(r=>r.proposedSequence.length===4)));
 await test("sequence timing is 0 2 4 7 days",()=>assert.deepStrictEqual(report.routes[0].proposedSequence.map(s=>s.delayDays),[0,2,4,7]));
 await test("GSA messaging addresses vehicle pipeline",()=>assert.match(report.routes.find(r=>r.route==="GSA").proposedSequence[0].subject,/GSA Schedule/));
 await test("VA messaging addresses VA FSS",()=>assert.match(report.routes.find(r=>r.route==="VA").proposedSequence[0].subject,/VA\/FSS/));
 await test("certification messaging is tailored",()=>assert.match(report.routes.find(r=>r.route==="SDVOSB").proposedSequence[0].subject,/SDVOSB/));
 await test("messages ask for a conversation",()=>assert.match(report.routes[0].proposedSequence[0].body,/15-minute/));
 await test("all routes must remain paused",()=>assert.ok(report.routes.every(r=>r.mustRemainPaused)));
 await test("reply routing handles positive replies",()=>assert.strictEqual(report.replyRouting.positive,"BOOKING_AND_HUMAN_FOLLOW_UP"));
 await test("reply routing suppresses unsubscribes",()=>assert.strictEqual(report.replyRouting.unsubscribe,"GLOBAL_SUPPRESSION"));
 await test("out of office is separated",()=>assert.strictEqual(report.replyRouting.outOfOffice,"OUT_OF_OFFICE_RETRY_AFTER_RETURN"));
 await test("exact next authorization is declared",()=>assert.strictEqual(report.authorizationRequired,"AUTHORIZE_GATE_21_OUTBOUND_REMEDIATION_NO_LAUNCH"));
 await test("provider writes remain unauthorized",()=>assert.strictEqual(report.providerWritesAuthorized,false));
 await test("no emails send",()=>assert.strictEqual(report.emailsSent,false));
 await test("no campaigns launch",()=>assert.strictEqual(report.campaignsLaunched,false));
 await test("plan artifact exists",()=>assert.ok(fs.existsSync(report.artifacts.plan.filePath)));
 await test("reply routing artifact exists",()=>assert.ok(fs.existsSync(report.artifacts.replyRouting.filePath)));
 await test("fingerprint is recorded",()=>assert.match(report.remediationFingerprint,/^[A-F0-9]{64}$/));
 await test("CLI defaults safely",()=>assert.deepStrictEqual(parseArguments([]),{apply:false}));
 await test("CLI parses apply",()=>assert.deepStrictEqual(parseArguments(["--apply"]),{apply:true}));
 console.log("REVENUE_OUTBOUND_REMEDIATION_PLAN_TEST_PASS "+passed+"/29");
 fs.rmSync(root,{recursive:true,force:true});
})().catch(e=>{console.error(e.stack||e.message);process.exitCode=1;});
