"use strict";
const assert=require("assert"),fs=require("fs"),os=require("os"),path=require("path");
const Service=require("../SERVICES/revenue/RevenueOutboundRemediationApplyService");
const {parseArguments}=require("../SCRIPTS/ApplyRevenueOutboundRemediation");
let passed=0;async function test(name,fn){await fn();passed++;console.log("[PASS] "+name);}
(async()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),"miles-remediation-apply-")),planPath=path.join(root,"plan.json"),routingPath=path.join(root,"routing.json"),outputRoot=path.join(root,"out");
 const names=["Expiring GSA 12 Months","Expiring VA 12 Months","GSA","VA","8(a)","HUBZone","SDVOSB","VOSB","WOSB","SBS"];
 const steps=Array.from({length:4},(_,i)=>({step:i+1,delayDays:[0,2,4,7][i],subject:"Subject "+i,body:"Body "+i}));
 const routes=names.map((route,i)=>({route,campaignId:"c"+i,action:i===9?"PRESERVE_READY_CAMPAIGN":"REMEDIATE_PAUSED_CAMPAIGN",proposedSequence:i===9?null:steps,proposedControls:{stopOnReply:i>2&&i<9?true:null,stopOnAutoReply:i>1&&i<9?true:null,allowRiskyContacts:false,disableBounceProtect:false},mustRemainPaused:true,launchAuthorized:false}));
 fs.writeFileSync(planPath,JSON.stringify({ok:true,status:"OUTBOUND_REMEDIATION_PLANNED",remediationFingerprint:"07745F581EE1D39C6C3809D03497680C480D0DBE72D184AF35CF084A231B3492",summary:{campaignsToRemediate:9,readyCampaignsPreserved:1},routes,providerWritesAuthorized:false,emailsSent:false,campaignsLaunched:false}),"utf8");
 const routing={ok:true,positive:"BOOKING_AND_HUMAN_FOLLOW_UP",negative:"DO_NOT_CONTACT",neutral:"NURTURE",technical:"TECHNICAL_REVIEW",outOfOffice:"OUT_OF_OFFICE_RETRY_AFTER_RETURN",unsubscribe:"GLOBAL_SUPPRESSION",unknown:"MANUAL_REVIEW",autoReplyDoesNotCountAsPositive:true};
 fs.writeFileSync(routingPath,JSON.stringify(routing,null,2),"utf8");
 const reads=[],updates=[],pauses=[];
 const service=new Service({rootDir:root,planPath,proposedRoutingPath:routingPath,replyRoutingPath:path.join(root,"live-routing.json"),outputRoot,generatedAt:()=>"2026-08-08T00:00:00.000Z",readProvider:async id=>{reads.push(id);return{id,status:2};},updateProvider:async(id,payload)=>{updates.push({id,payload});return{id};},pauseProvider:async id=>{pauses.push(id);return{id,status:2};}});
 const auth="AUTHORIZE_GATE_21_OUTBOUND_REMEDIATION_NO_LAUNCH";
 await test("service is constructable",()=>assert.ok(service));
 const preview=await service.apply({});
 await test("default mode is plan-only",()=>assert.strictEqual(preview.mode,"PLAN_ONLY"));
 await test("plan performs no provider writes",()=>assert.strictEqual(updates.length+pauses.length,0));
 await test("apply requires live flag",()=>assert.rejects(()=>service.apply({apply:true,authorization:auth}),/--live/));
 await test("wrong authorization fails closed",()=>assert.rejects(()=>service.apply({apply:true,live:true,authorization:"WRONG"}),/Exact CEO/));
 const report=await service.apply({apply:true,live:true,authorization:auth});
 await test("remediation completes",()=>assert.strictEqual(report.status,"OUTBOUND_REMEDIATION_COMPLETED"));
 await test("all ten campaigns are backed up",()=>assert.strictEqual(reads.length,10));
 await test("nine campaigns are updated",()=>assert.strictEqual(updates.length,9));
 await test("nine campaigns are re-paused",()=>assert.strictEqual(pauses.length,9));
 await test("SBS is preserved without update",()=>assert.ok(!updates.some(x=>x.id==="c9")));
 await test("sequences use Instantly step structure",()=>assert.strictEqual(updates[0].payload.sequences[0].steps.length,4));
 await test("message variants preserve subjects",()=>assert.strictEqual(updates[0].payload.sequences[0].steps[0].variants[0].subject,"Subject 0"));
 await test("message variants preserve bodies",()=>assert.strictEqual(updates[0].payload.sequences[0].steps[0].variants[0].body,"Body 0"));
 await test("sequence delays are preserved",()=>assert.deepStrictEqual(updates[0].payload.sequences[0].steps.map(x=>x.delay),[0,2,4,7]));
 await test("risky contacts remain blocked",()=>assert.ok(updates.every(x=>x.payload.allow_risky_contacts===false)));
 await test("bounce protection remains enabled",()=>assert.ok(updates.every(x=>x.payload.disable_bounce_protect===false)));
 await test("reply routing is persisted",()=>assert.strictEqual(report.summary.replyRoutingPersisted,true));
 await test("reply routing file exists",()=>assert.ok(fs.existsSync(service.replyRoutingPath)));
 await test("positive routing is preserved",()=>assert.strictEqual(JSON.parse(fs.readFileSync(service.replyRoutingPath)).positive,"BOOKING_AND_HUMAN_FOLLOW_UP"));
 await test("provider scope is constrained",()=>assert.strictEqual(report.providerWriteScope,"UPDATE_9_PAUSED_CAMPAIGNS_AND_PERSIST_REPLY_ROUTING"));
 await test("no leads upload",()=>assert.strictEqual(report.leadsUploaded,0));
 await test("no emails send",()=>assert.strictEqual(report.emailsSent,false));
 await test("no campaigns launch",()=>assert.strictEqual(report.campaignsLaunched,false));
 await test("campaign pause requirement remains",()=>assert.strictEqual(report.allCampaignsMustRemainPaused,true));
 await test("backup hashes are recorded",()=>assert.ok(Object.values(JSON.parse(fs.readFileSync(service.progressPath)).routes).every(x=>x.backupSha256)));
 await test("manifest exists",()=>assert.ok(fs.existsSync(report.artifact.filePath)));
 await test("apply fingerprint is recorded",()=>assert.match(report.applyFingerprint,/^[A-F0-9]{64}$/));
 const second=await service.apply({apply:true,live:true,authorization:auth});
 await test("rerun is idempotent",()=>assert.strictEqual(second.summary.updatedThisRun,0));
 await test("rerun creates no extra updates",()=>assert.strictEqual(updates.length,9));
 await test("rerun creates no extra pauses",()=>assert.strictEqual(pauses.length,9));
 await test("CLI defaults safely",()=>assert.deepStrictEqual(parseArguments([]),{apply:false,live:false,authorization:null}));
 await test("CLI parses exact authorization",()=>assert.deepStrictEqual(parseArguments(["--apply","--live","--authorization="+auth]),{apply:true,live:true,authorization:auth}));
 const dry=new Service({rootDir:root,planPath,proposedRoutingPath:routingPath,replyRoutingPath:path.join(root,"dry-routing.json"),outputRoot:path.join(root,"dry"),readProvider:async()=>({id:"x"}),updateProvider:async()=>({dryRun:true,mutationExecuted:false}),pauseProvider:async()=>({id:"x"})});
 await test("dry-run provider update fails closed",()=>assert.rejects(()=>dry.apply({apply:true,live:true,authorization:auth}),/did not confirm/));
 console.log("REVENUE_OUTBOUND_REMEDIATION_APPLY_TEST_PASS "+passed+"/33");
 fs.rmSync(root,{recursive:true,force:true});
})().catch(e=>{console.error(e.stack||e.message);process.exitCode=1;});
