'use strict';

const fs=require('fs');
const path=require('path');
const https=require('https');

const KEY_ENV_NAMES=['SAM_API_KEY','SAM_GOV_API_KEY'];
function presentKeys(env,names=KEY_ENV_NAMES){return names.map(name=>({envName:name,value:String(env[name]||'').trim()})).filter(x=>x.value).map(x=>({...x,length:x.value.length}));}
function firstPresentEnv(env,names){const first=presentKeys(env,names)[0];return first?{present:true,...first}:{present:false,envName:null,length:0,value:null};}
function mmddyyyy(date){const d=new Date(date);return `${String(d.getUTCMonth()+1).padStart(2,'0')}/${String(d.getUTCDate()).padStart(2,'0')}/${d.getUTCFullYear()}`;}
function probeJson(url,timeoutMs=20000){return new Promise(resolve=>{const started=Date.now();let settled=false;const done=v=>{if(settled)return;settled=true;resolve({...v,durationMs:Date.now()-started});};const req=https.get(url,{headers:{'user-agent':'MILES-P2GC-FEDERAL-SOURCE-READINESS/1.2','accept':'application/json'}},res=>{const chunks=[];let bytes=0;res.on('data',c=>{if(bytes<65536){chunks.push(c);bytes+=c.length;}});res.on('end',()=>{const text=Buffer.concat(chunks).toString('utf8');let json=null;try{json=JSON.parse(text);}catch{}done({ok:res.statusCode>=200&&res.statusCode<300,statusCode:res.statusCode,contentType:res.headers['content-type']||null,responseKeys:json&&typeof json==='object'?Object.keys(json).slice(0,20):[],errorHint:res.statusCode>=400?(json?.message||json?.error||text.slice(0,180)||null):null});});});req.setTimeout(timeoutMs,()=>req.destroy(new Error('HTTP_TIMEOUT')));req.on('error',e=>done({ok:false,statusCode:null,contentType:null,responseKeys:[],errorHint:e.message}));});}
function sanitizedProbe(probe){return probe?{ok:probe.ok,statusCode:probe.statusCode,contentType:probe.contentType,responseKeys:probe.responseKeys,errorHint:probe.errorHint,durationMs:probe.durationMs}:null;}

class FederalSourceReadinessAuditService{
  constructor(options={}){this.rootDir=path.resolve(options.rootDir||process.env.MILES_ROOT||process.cwd());this.env=options.env||process.env;this.now=options.now?new Date(options.now):new Date();this.timeoutMs=Math.max(5000,Number(options.timeoutMs||20000));this.reportPath=path.join(this.rootDir,'DATA','orion_refresh','latest_federal_source_readiness.json');}
  async probeCandidate(candidate){const to=new Date(this.now),from=new Date(this.now);from.setUTCDate(from.getUTCDate()-1);const opp=new URL('https://api.sam.gov/opportunities/v2/search');opp.searchParams.set('api_key',candidate.value);opp.searchParams.set('postedFrom',mmddyyyy(from));opp.searchParams.set('postedTo',mmddyyyy(to));opp.searchParams.set('limit','1');opp.searchParams.set('offset','0');const opportunity=await probeJson(opp,this.timeoutMs);const ent=new URL('https://api.sam.gov/entity-information/v3/entities');ent.searchParams.set('api_key',candidate.value);ent.searchParams.set('registrationStatus','A');ent.searchParams.set('includeSections','entityRegistration');ent.searchParams.set('page','0');ent.searchParams.set('size','1');const entity=await probeJson(ent,this.timeoutMs);return{envName:candidate.envName,length:candidate.length,opportunity:sanitizedProbe(opportunity),entity:sanitizedProbe(entity),bothGreen:opportunity.ok===true&&entity.ok===true};}
  async run(){const candidates=presentKeys(this.env);const attempts=[];let selected=null;for(const candidate of candidates){const attempt=await this.probeCandidate(candidate);attempts.push(attempt);if(attempt.bothGreen){selected=attempt;break;}}
    const opportunity={officialEndpoint:'https://api.sam.gov/opportunities/v2/search',apiKeyRequired:true,keyPresent:candidates.length>0,keyEnvName:selected?.envName||candidates[0]?.envName||null,probe:selected?.opportunity||attempts[0]?.opportunity||null,scope:'Current published federal contract opportunities from SAM.gov'};
    const entity={officialEndpoint:'https://api.sam.gov/entity-information/v3/entities',apiKeyRequired:true,keyPresent:candidates.length>0,keyEnvName:selected?.envName||candidates[0]?.envName||null,probe:selected?.entity||attempts[0]?.entity||null,scope:'Current SAM entity/registration truth',bulkStrategyRequired:true,note:'Per-entity polling is not an acceptable refresh strategy for the full ORION contractor population; use a permitted SAM bulk extract/system-account path when available.'};
    const gsaMas={source:'GSA eLibrary',officialSite:'https://www.gsaelibrary.gsa.gov/ElibMain/home.do',apiKeyRequired:false,sourceMethod:'Schedule/SIN-driven public eLibrary retrieval',retrieval:'Use MAS schedule/category/SIN pages and contractor download links (CSV/XLS when offered) to resolve awarded SINs, schedule participation, contractor records, and related GSA MAS facts.',rules:{doNotTreatGsaApiKeyAsSamCredential:true,doNotUseSamApiForGsaMasAwardedSinTruth:true,verifyContractorPricelistForSpecificAwardedOfferings:true}};
    const blockers=[];if(!candidates.length)blockers.push('SAM_API_KEY_NOT_PRESENT');else if(!selected){blockers.push('NO_PRESENT_SAM_API_KEY_PASSED_OFFICIAL_PROBES');if(!attempts.some(x=>x.opportunity?.ok))blockers.push('SAM_OPPORTUNITIES_API_PROBE_NOT_GREEN');if(!attempts.some(x=>x.entity?.ok))blockers.push('SAM_ENTITY_API_PROBE_NOT_GREEN');}
    const result={ok:blockers.length===0,service:'FEDERAL_SOURCE_READINESS_AUDIT',generatedAt:new Date().toISOString(),credentials:{samApiKeyPresent:candidates.length>0,presentKeyEnvNames:candidates.map(x=>x.envName),selectedKeyEnvName:selected?.envName||null,keyValuesExposed:false,candidateAttempts:attempts.map(x=>({envName:x.envName,length:x.length,bothGreen:x.bothGreen,opportunity:x.opportunity,entity:x.entity}))},opportunity,entity,gsaMas,blockers,nextStep:!candidates.length?'CONFIGURE_SAM_API_KEY_WITHOUT_EXPOSING_SECRET':!selected?'REPAIR_OR_REPLACE_SAM_API_CREDENTIALS':'BUILD_GOVERNED_SAM_REFRESH_AND_GSA_ELIBRARY_SIN_SCHEDULE_REFRESH',safety:{readOnly:true,secretValuesLogged:false,requestsMade:attempts.length*2,productionDatabaseModified:false,credentialsModified:false,webScraping:false,officialApisOnly:true,staleCredentialCannotMaskAlternatePresentCredential:true,gsaMasSourceSeparatedFromSamApi:true}};
    fs.mkdirSync(path.dirname(this.reportPath),{recursive:true});fs.writeFileSync(this.reportPath,JSON.stringify(result,null,2),'utf8');return result;}
}
module.exports=FederalSourceReadinessAuditService;module.exports.firstPresentEnv=firstPresentEnv;module.exports.presentKeys=presentKeys;module.exports.mmddyyyy=mmddyyyy;
