'use strict';
const fs=require('fs');
const path=require('path');
const https=require('https');

const MAS_URL='https://www.gsaelibrary.gsa.gov/ElibMain/home.do/scheduleSummary.do?fromPage=techContract&scheduleNumber=MAS';

function fetchText(url,timeoutMs=20000){return new Promise(resolve=>{const started=Date.now();let settled=false;const done=v=>{if(settled)return;settled=true;resolve({...v,durationMs:Date.now()-started});};const req=https.get(url,{headers:{'user-agent':'MILES-P2GC-GSA-ELIBRARY-READINESS/1.0','accept':'text/html,application/xhtml+xml'}},res=>{const chunks=[];let bytes=0;res.on('data',c=>{if(bytes<250000){chunks.push(c);bytes+=c.length;}});res.on('end',()=>done({ok:res.statusCode>=200&&res.statusCode<300,statusCode:res.statusCode,contentType:res.headers['content-type']||null,text:Buffer.concat(chunks).toString('utf8')}));});req.setTimeout(timeoutMs,()=>req.destroy(new Error('HTTP_TIMEOUT')));req.on('error',e=>done({ok:false,statusCode:null,contentType:null,text:'',errorHint:e.message}));});}
function extractLinks(html){const out=[];const re=/href=["']([^"']+)["']/gi;let m;while((m=re.exec(String(html||''))))out.push(m[1]);return [...new Set(out)];}

class GsaElibraryReadinessAuditService{
 constructor(options={}){this.rootDir=path.resolve(options.rootDir||process.env.MILES_ROOT||process.cwd());this.timeoutMs=Math.max(5000,Number(options.timeoutMs||20000));this.reportPath=path.join(this.rootDir,'DATA','orion_refresh','latest_gsa_elibrary_readiness.json');}
 async run(){const probe=await fetchText(MAS_URL,this.timeoutMs);const html=probe.text||'';const links=extractLinks(html);const csvLinks=links.filter(x=>/csv/i.test(x));const xlsLinks=links.filter(x=>/xls/i.test(x));const hasMas=/Multiple Award Schedule|scheduleNumber=MAS/i.test(html);const hasSin=/\bSIN\b|Special Item Number/i.test(html);const hasDownload=/Download Contractors/i.test(html)||csvLinks.length>0||xlsLinks.length>0;const blockers=[];if(!probe.ok)blockers.push('GSA_ELIBRARY_MAS_PAGE_UNREACHABLE');if(probe.ok&&!hasMas)blockers.push('GSA_ELIBRARY_MAS_MARKER_NOT_FOUND');if(probe.ok&&!hasDownload)blockers.push('GSA_ELIBRARY_CONTRACTOR_DOWNLOAD_NOT_DISCOVERED');const result={ok:blockers.length===0,service:'GSA_ELIBRARY_READINESS_AUDIT',generatedAt:new Date().toISOString(),source:{name:'GSA eLibrary',officialUrl:MAS_URL,apiKeyRequired:false,method:'MAS schedule and SIN-driven public retrieval',probe:{ok:probe.ok,statusCode:probe.statusCode,contentType:probe.contentType,durationMs:probe.durationMs,errorHint:probe.errorHint||null},markers:{masDetected:hasMas,sinLanguageDetected:hasSin,contractorDownloadDetected:hasDownload},downloadLinkCounts:{csv:csvLinks.length,xls:xlsLinks.length},sampleDownloadLinks:[...csvLinks,...xlsLinks].slice(0,10)},governance:{useGsaApi:false,useSamApiForGsaMasTruth:false,verifySpecificOfferingsAgainstContractorPricelist:true,stageBeforeCutover:true,recordSourceUrlTimestampAndHash:true},blockers,nextStep:blockers.length?'RETRY_GSA_ELIBRARY_PUBLIC_READINESS_WITH_BACKOFF':'BUILD_GSA_ELIBRARY_SIN_SCHEDULE_STAGING_REFRESH',safety:{readOnly:true,officialPublicSourceOnly:true,credentialsUsed:false,credentialsModified:false,productionOrionModified:false,campaignsModified:false}};fs.mkdirSync(path.dirname(this.reportPath),{recursive:true});fs.writeFileSync(this.reportPath,JSON.stringify(result,null,2),'utf8');return result;}
}
module.exports=GsaElibraryReadinessAuditService;module.exports.extractLinks=extractLinks;
