'use strict';
const fs=require('fs');
const path=require('path');
const https=require('https');
const crypto=require('crypto');

const ENTITY_LIST='https://sam.gov/api/prod/fileextractservices/v1/api/listfiles?domain=Entity%20Registration/Public%20V2&privacy=Public';
const ENTITY_DOMAIN='Entity%20Registration/Public%20V2';
const OPPORTUNITY_URL='https://sam.gov/api/prod/fileextractservices/v1/api/download/Contract%20Opportunities/datagov/ContractOpportunitiesFullCSV.csv?privacy=Public';

function freeBytes(target){try{const s=fs.statfsSync(path.parse(path.resolve(target)).root);return Number(s.bavail??s.bfree??0)*Number(s.bsize??s.frsize??0);}catch{return null;}}
function getJson(url,timeout=30000){return new Promise((resolve,reject)=>{const r=https.get(url,{headers:{'user-agent':'MILES-P2GC-SAM-BULK/1.0','accept':'application/json'}},res=>{const chunks=[];res.on('data',c=>chunks.push(c));res.on('end',()=>{if(res.statusCode<200||res.statusCode>=300)return reject(new Error(`HTTP_${res.statusCode}`));try{resolve(JSON.parse(Buffer.concat(chunks).toString('utf8')));}catch(e){reject(e);}});});r.setTimeout(timeout,()=>r.destroy(new Error('HTTP_TIMEOUT')));r.on('error',reject);});}
function latestEntity(data){const rows=data?._embedded?.customS3ObjectSummaryList||[];return rows.filter(x=>/SAM_PUBLIC_UTF-8_MONTHLY_V2_\d{8}\.ZIP$/i.test(String(x.displayKey||''))).sort((a,b)=>String(b.dateModified||'').localeCompare(String(a.dateModified||'')))[0]||null;}
function streamDownload(url,dest,{timeout=120000,maxBytes=12*1024*1024*1024,redirects=0}={}){return new Promise((resolve,reject)=>{if(redirects>5)return reject(new Error('TOO_MANY_REDIRECTS'));const req=https.get(url,{headers:{'user-agent':'MILES-P2GC-SAM-BULK/1.0'}},res=>{if(res.statusCode>=300&&res.statusCode<400&&res.headers.location){res.resume();return resolve(streamDownload(new URL(res.headers.location,url).toString(),dest,{timeout,maxBytes,redirects:redirects+1}));}if(res.statusCode<200||res.statusCode>=300){res.resume();return reject(new Error(`DOWNLOAD_HTTP_${res.statusCode}`));}const declared=Number(res.headers['content-length']||0)||null;if(declared&&declared>maxBytes){res.destroy();return reject(new Error(`DOWNLOAD_DECLARED_TOO_LARGE:${declared}`));}fs.mkdirSync(path.dirname(dest),{recursive:true});const partial=`${dest}.partial`;const out=fs.createWriteStream(partial,{flags:'w'});const hash=crypto.createHash('sha256');let bytes=0,settled=false;const fail=e=>{if(settled)return;settled=true;try{out.destroy();}catch{}try{fs.unlinkSync(partial);}catch{}reject(e);};res.on('data',c=>{bytes+=c.length;if(bytes>maxBytes){res.destroy(new Error(`DOWNLOAD_STREAM_TOO_LARGE:${bytes}`));return;}hash.update(c);});res.pipe(out);res.on('error',fail);out.on('error',fail);out.on('finish',()=>{if(settled)return;settled=true;out.close(()=>{fs.renameSync(partial,dest);resolve({url,finalUrl:res.responseUrl||url,bytes,declaredBytes:declared,sha256:hash.digest('hex'),contentType:res.headers['content-type']||null});});});});req.setTimeout(timeout,()=>req.destroy(new Error('DOWNLOAD_TIMEOUT')));req.on('error',reject);});}

class SamBulkExtractAcquisitionService{
 constructor(options={}){this.rootDir=path.resolve(options.rootDir||process.env.MILES_ROOT||process.cwd());this.stageDir=path.join(this.rootDir,'DATA','orion_refresh','sam_bulk_staging');this.reportPath=path.join(this.rootDir,'DATA','orion_refresh','latest_sam_bulk_acquisition.json');this.minReserve=Math.max(4*1024*1024*1024,Number(options.minReserve||process.env.SAM_BULK_MIN_FREE_RESERVE||8*1024*1024*1024));this.maxFileBytes=Math.max(1024*1024*1024,Number(options.maxFileBytes||process.env.SAM_BULK_MAX_FILE_BYTES||12*1024*1024*1024));}
 async run(){fs.mkdirSync(this.stageDir,{recursive:true});const before=freeBytes(this.stageDir);if(before!=null&&before<this.minReserve)throw new Error(`SAM_BULK_INSUFFICIENT_FREE_SPACE:${before}`);const listing=await getJson(ENTITY_LIST);const entity=latestEntity(listing);if(!entity)throw new Error('SAM_ENTITY_UTF8_MONTHLY_EXTRACT_NOT_DISCOVERED');const entityUrl=`https://sam.gov/api/prod/fileextractservices/v1/api/download/${ENTITY_DOMAIN}/${encodeURIComponent(entity.displayKey)}?privacy=Public`;const files=[];
   for(const spec of [{role:'entity_registration',name:entity.displayKey,url:entityUrl},{role:'contract_opportunities',name:'ContractOpportunitiesFullCSV.csv',url:OPPORTUNITY_URL}]){
     const target=path.join(this.stageDir,spec.name);let info;if(fs.existsSync(target)){const st=fs.statSync(target);info={skippedExisting:true,bytes:st.size,sha256:null};}else{const free=freeBytes(this.stageDir);if(free!=null&&free<this.minReserve)throw new Error(`SAM_BULK_RESERVE_BREACH_BEFORE_${spec.role}:${free}`);info=await streamDownload(spec.url,target,{maxBytes:this.maxFileBytes});}
     files.push({role:spec.role,fileName:spec.name,path:target,sourceUrl:spec.url,...info});
   }
   const after=freeBytes(this.stageDir);const result={ok:true,service:'SAM_BULK_EXTRACT_ACQUISITION',generatedAt:new Date().toISOString(),entitySource:{listingEndpoint:ENTITY_LIST,displayKey:entity.displayKey,dateModified:entity.dateModified||null,reportedSize:entity.size||null},files,storage:{freeBefore:before,freeAfter:after,minReserve:this.minReserve,maxFileBytes:this.maxFileBytes},nextStep:'INSPECT_SCHEMA_AND_BUILD_SAM_ENTITY_AND_OPPORTUNITY_SIDECARS',safety:{publicDataServicesOnly:true,samApiKeyUsed:false,loginAutomation:false,authenticatedScraping:false,productionDatabaseModified:false,credentialsModified:false,stagingOnly:true}};fs.writeFileSync(this.reportPath,JSON.stringify(result,null,2),'utf8');console.log(JSON.stringify(result,null,2));return result;}
}
module.exports=SamBulkExtractAcquisitionService;module.exports.latestEntity=latestEntity;module.exports.streamDownload=streamDownload;
