'use strict';

const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const instantly=require('../../CONNECTORS/INSTANTLY/instantly');
const GlobalSuppressionService=require('../revenue/GlobalSuppressionService');

function now(){return new Date().toISOString();}
function clean(v){return String(v??'').trim();}
function emailKey(v){return clean(v).toLowerCase();}
function ueiKey(v){return clean(v).toUpperCase();}
function unwrap(v){if(Array.isArray(v))return v;if(Array.isArray(v?.items))return v.items;if(Array.isArray(v?.data))return v.data;if(Array.isArray(v?.leads))return v.leads;return [];}
function nextCursor(v){return clean(v?.next_starting_after||v?.nextStartingAfter||v?.next_cursor||v?.nextCursor||v?.pagination?.next_starting_after||v?.pagination?.next_cursor)||null;}
function hash(v){return crypto.createHash('sha256').update(String(v||'')).digest('hex').slice(0,16);}
function leadUei(lead={}){const cv=lead.custom_variables||lead.customVariables||{};return ueiKey(lead.uei||lead.unique_entity_identifier||cv.uei||cv.UEI||cv.unique_entity_identifier||cv.uniqueEntityIdentifier);}

class SamCurrentSendCollisionAuditService{
 constructor(options={}){this.rootDir=path.resolve(options.rootDir||process.env.MILES_ROOT||process.cwd());this.buildReport=path.join(this.rootDir,'DATA','orion_refresh','latest_sam_qualified_universe_build.json');this.output=path.join(this.rootDir,'DATA','orion_refresh','latest_sam_current_send_collision_audit.json');this.maxPages=Math.max(1,Number(options.maxPages||2000));this.pageSize=Math.max(1,Math.min(100,Number(options.pageSize||100)));}
 loadJson(file){return JSON.parse(fs.readFileSync(file,'utf8').replace(/^\uFEFF/,''));}
 async fetchProviderLeads(){const emails=new Set(),ueis=new Set();let cursor=null,pages=0,rows=0,truncated=false;const seenCursors=new Set();for(;pages<this.maxPages;pages++){const body={limit:this.pageSize,distinct_contacts:false};if(cursor)body.starting_after=cursor;const response=await instantly.listLeads(body);const batch=unwrap(response);for(const lead of batch){rows++;const e=emailKey(lead.email||lead.contact);if(e)emails.add(e);const u=leadUei(lead);if(u)ueis.add(u);}const next=nextCursor(response);if(!next||batch.length===0){cursor=null;break;}if(seenCursors.has(next)){truncated=true;break;}seenCursors.add(next);cursor=next;}if(pages>=this.maxPages&&cursor)truncated=true;return{emails,ueis,pages:pages+(cursor===null?1:0),rows,truncated};}
 async run(){if(!fs.existsSync(this.buildReport))throw new Error('SAM_QUALIFIED_BUILD_REPORT_MISSING');const build=this.loadJson(this.buildReport),dbPath=build?.output?.database;if(!dbPath||!fs.existsSync(dbPath))throw new Error('SAM_QUALIFIED_DATABASE_MISSING');const provider=await this.fetchProviderLeads();const suppression=new GlobalSuppressionService({rootDir:this.rootDir}).load();const suppressedEmails=new Set((suppression.entries||[]).filter(x=>x?.active!==false).map(x=>emailKey(x.email)).filter(Boolean));const Database=require('better-sqlite3');const db=new Database(dbPath,{readonly:true,fileMustExist:true});let counts;const collisionSamples=[];try{const rows=db.prepare(`SELECT uei,email,email_verification_status FROM sam_qualified_companies WHERE (email IS NOT NULL AND TRIM(email)<>'') OR (uei IS NOT NULL AND TRIM(uei)<>'')`).iterate();let qualified=0,emailPresent=0,verified=0,providerEmailCollision=0,providerUeiCollision=0,suppressionCollision=0,anyCollision=0,verifiedWithoutCollision=0;for(const row of rows){qualified++;const e=emailKey(row.email),u=ueiKey(row.uei),isVerified=row.email_verification_status==='VERIFIED';if(e)emailPresent++;if(isVerified)verified++;const byEmail=!!e&&provider.emails.has(e),byUei=!!u&&provider.ueis.has(u),supp=!!e&&suppressedEmails.has(e),any=byEmail||byUei||supp;if(byEmail)providerEmailCollision++;if(byUei)providerUeiCollision++;if(supp)suppressionCollision++;if(any)anyCollision++;if(isVerified&&!any)verifiedWithoutCollision++;if(any&&collisionSamples.length<25)collisionSamples.push({ueiHash:hash(u),emailHash:e?hash(e):null,providerEmailCollision:byEmail,providerUeiCollision:byUei,suppressed:supp});}counts={rowsInspected:qualified,emailPresent,verifiedDeliverable:verified,providerEmailCollision,providerUeiCollision,suppressionCollision,anyCollision,verifiedWithoutCollision};}finally{db.close();}
 const result={ok:true,service:'SAM_CURRENT_SEND_COLLISION_AUDIT',generatedAt:now(),qualifiedDatabase:dbPath,provider:{source:'Instantly API v2',readOnly:true,leadRowsObserved:provider.rows,uniqueEmailsObserved:provider.emails.size,uniqueUeisObserved:provider.ueis.size,pages:provider.pages,truncated:provider.truncated},suppression:{source:'GlobalSuppressionService',activeEntries:suppressedEmails.size},counts,collisionSamplesHashed:collisionSamples,nextStep:provider.truncated?'REPAIR_PROVIDER_PAGINATION_BEFORE_DEDUPE':'APPLY_COLLISION_FLAGS_AFTER_EMAIL_VERIFICATION_AND_BEFORE_SEGMENT_CUTOVER',safety:{readOnly:true,providerMutations:false,campaignsModified:false,currentSendSegmentsModified:false,qualifiedDatabaseModified:false,productionOrionModified:false,oldSamDeleted:false,credentialsModified:false,emailValuesLogged:false,samplesHashed:true,globalSuppressionRespected:true,verifiedEmailStillRequired:true}};fs.mkdirSync(path.dirname(this.output),{recursive:true});fs.writeFileSync(this.output,JSON.stringify(result,null,2),'utf8');console.log(JSON.stringify(result,null,2));return result;}
}

module.exports=SamCurrentSendCollisionAuditService;
module.exports.helpers={unwrap,nextCursor,leadUei,emailKey,ueiKey};
