'use strict';
const fs=require('fs');
const path=require('path');
const zlib=require('zlib');
const readline=require('readline');
const crypto=require('crypto');
const Eligibility=require('./SamLeadEligibilityService');

function now(){return new Date().toISOString();}
function splitCodes(v){return String(v||'').split('~').map(x=>x.trim()).filter(Boolean);}
function naicsCodes(v){const out=[];for(const token of splitCodes(v)){const m=token.match(/^(\d{6})/);if(m)out.push(m[1]);}return [...new Set(out)];}
function sbaCodes(v){return splitCodes(v).map(x=>x.slice(0,2)).filter(Boolean);}
function sourceDateFromName(name){return (String(name).match(/(20\d{6})/)||[])[1]||null;}
function findEocd(fd,size){const len=Math.min(size,65557);const buf=Buffer.alloc(len);fs.readSync(fd,buf,0,len,size-len);for(let i=len-22;i>=0;i--)if(buf.readUInt32LE(i)===0x06054b50)return{buf,offset:size-len+i};throw new Error('ZIP_EOCD_NOT_FOUND');}
function zipEntries(zipPath){const fd=fs.openSync(zipPath,'r');try{const size=fs.fstatSync(fd).size;const {buf,offset}=findEocd(fd,size);const local=offset-(size-buf.length);const total=buf.readUInt16LE(local+10),centralSize=buf.readUInt32LE(local+12),centralOffset=buf.readUInt32LE(local+16);if(total===0xffff||centralSize===0xffffffff||centralOffset===0xffffffff)throw new Error('ZIP64_NOT_SUPPORTED');const cd=Buffer.alloc(centralSize);fs.readSync(fd,cd,0,centralSize,centralOffset);const out=[];let p=0;for(let n=0;n<total&&p+46<=cd.length;n++){if(cd.readUInt32LE(p)!==0x02014b50)throw new Error(`ZIP_CENTRAL_SIGNATURE_INVALID:${p}`);const method=cd.readUInt16LE(p+10),compressedSize=cd.readUInt32LE(p+20),uncompressedSize=cd.readUInt32LE(p+24),nameLen=cd.readUInt16LE(p+28),extraLen=cd.readUInt16LE(p+30),commentLen=cd.readUInt16LE(p+32),localHeaderOffset=cd.readUInt32LE(p+42),fileName=cd.subarray(p+46,p+46+nameLen).toString('utf8');out.push({fileName,method,compressedSize,uncompressedSize,localHeaderOffset});p+=46+nameLen+extraLen+commentLen;}return out;}finally{fs.closeSync(fd);}}
function entryStream(zipPath,entry){const fd=fs.openSync(zipPath,'r');const h=Buffer.alloc(30);try{fs.readSync(fd,h,0,30,entry.localHeaderOffset);}finally{fs.closeSync(fd);}if(h.readUInt32LE(0)!==0x04034b50)throw new Error('ZIP_LOCAL_HEADER_INVALID');const start=entry.localHeaderOffset+30+h.readUInt16LE(26)+h.readUInt16LE(28),end=start+entry.compressedSize-1;const raw=fs.createReadStream(zipPath,{start,end});if(entry.method===0)return raw;if(entry.method===8){const inflate=zlib.createInflateRaw();raw.pipe(inflate);return inflate;}throw new Error(`ZIP_COMPRESSION_METHOD_UNSUPPORTED:${entry.method}`);}
function parseRecord(fields){const businessTypes=splitCodes(fields[31]);const naics=naicsCodes(fields[34]);const sba=sbaCodes(fields[117]);return{
  uei:String(fields[0]||'').trim(), duns:String(fields[1]||'').trim(), cage:String(fields[3]||'').trim(), registrationStatus:String(fields[5]||'').trim(), purposeOfRegistration:String(fields[6]||'').trim(), initialRegistrationDate:String(fields[7]||'').trim(), registrationExpirationDate:String(fields[8]||'').trim(), lastUpdateDate:String(fields[9]||'').trim(), activationDate:String(fields[10]||'').trim(), legalBusinessName:String(fields[11]||'').trim(), dbaName:String(fields[12]||'').trim(), address1:String(fields[15]||'').trim(), address2:String(fields[16]||'').trim(), city:String(fields[17]||'').trim(), state:String(fields[18]||'').trim(), zip:String(fields[19]||'').trim(), country:String(fields[21]||'').trim(), website:String(fields[26]||'').trim(), entityStructure:String(fields[27]||'').trim(), businessTypeCodes:businessTypes, primaryNaics:String(fields[32]||'').trim(), naicsCodes:naics, exclusionStatusFlag:String(fields[115]||'').trim(), sbaBusinessTypeCodes:sba, forProfit:businessTypes.includes('2X')
};}
function sha256(file){const h=crypto.createHash('sha256');const fd=fs.openSync(file,'r');try{const b=Buffer.alloc(1024*1024);let n,pos=0;while((n=fs.readSync(fd,b,0,b.length,pos))>0){h.update(b.subarray(0,n));pos+=n;}}finally{fs.closeSync(fd);}return h.digest('hex');}
class SamQualifiedUniverseBuildService{
 constructor(options={}){this.rootDir=path.resolve(options.rootDir||process.env.MILES_ROOT||process.cwd());this.stageDir=path.join(this.rootDir,'DATA','orion_refresh','sam_bulk_staging');this.outDir=path.join(this.rootDir,'DATA','orion_refresh','sam_qualified_staging');this.reportPath=path.join(this.rootDir,'DATA','orion_refresh','latest_sam_qualified_universe_build.json');this.eligibility=new Eligibility({rootDir:this.rootDir});this.batchSize=Math.max(100,Number(options.batchSize||5000));}
 async run(){fs.mkdirSync(this.outDir,{recursive:true});const names=fs.existsSync(this.stageDir)?fs.readdirSync(this.stageDir):[];const sourceName=names.filter(x=>/^SAM_PUBLIC_UTF-8_MONTHLY_V2_\d{8}\.ZIP$/i.test(x)).sort().reverse()[0];if(!sourceName)throw new Error('SAM_ENTITY_BULK_SOURCE_MISSING');const sourcePath=path.join(this.stageDir,sourceName);const entries=zipEntries(sourcePath);const entry=entries.filter(e=>e.uncompressedSize>0&&!/\/$/.test(e.fileName)).sort((a,b)=>b.uncompressedSize-a.uncompressedSize)[0];if(!entry)throw new Error('SAM_ENTITY_DATA_ENTRY_MISSING');const Database=require('better-sqlite3');const stamp=now().replace(/[:.]/g,'-'),sourceDate=sourceDateFromName(sourceName);const final=path.join(this.outDir,`SAM_QUALIFIED_${sourceDate||'unknown'}_${stamp}.db`),partial=`${final}.partial`;try{fs.unlinkSync(partial);}catch{}const db=new Database(partial);db.pragma('journal_mode = WAL');db.pragma('synchronous = NORMAL');db.exec(`CREATE TABLE sam_qualified_companies(uei TEXT PRIMARY KEY,duns TEXT,cage TEXT,legal_name TEXT NOT NULL,dba TEXT,purpose_registration TEXT,registration_expiration_date TEXT,last_update_date TEXT,activation_date TEXT,website TEXT,entity_structure TEXT,business_type_codes TEXT,primary_naics TEXT,naics_codes TEXT,sba_business_type_codes TEXT,address1 TEXT,address2 TEXT,city TEXT,state TEXT,zip TEXT,country TEXT,email TEXT,email_status TEXT NOT NULL DEFAULT 'ENRICHMENT_REQUIRED',email_source TEXT,email_verified_at TEXT,source_file TEXT NOT NULL,source_date TEXT,loaded_at TEXT NOT NULL);CREATE INDEX idx_samq_name ON sam_qualified_companies(legal_name);CREATE INDEX idx_samq_cage ON sam_qualified_companies(cage);CREATE INDEX idx_samq_primary_naics ON sam_qualified_companies(primary_naics);CREATE TABLE sam_qualification_manifest(key TEXT PRIMARY KEY,value TEXT NOT NULL);`);
 const insert=db.prepare(`INSERT OR REPLACE INTO sam_qualified_companies(uei,duns,cage,legal_name,dba,purpose_registration,registration_expiration_date,last_update_date,activation_date,website,entity_structure,business_type_codes,primary_naics,naics_codes,sba_business_type_codes,address1,address2,city,state,zip,country,email,email_status,email_source,email_verified_at,source_file,source_date,loaded_at) VALUES(@uei,@duns,@cage,@legalName,@dba,@purpose,@expiration,@updated,@activation,@website,@entityStructure,@businessTypes,@primaryNaics,@naics,@sba,@address1,@address2,@city,@state,@zip,@country,NULL,'ENRICHMENT_REQUIRED',NULL,NULL,@sourceFile,@sourceDate,@loadedAt)`);
 const tx=db.transaction(rows=>{for(const r of rows)insert.run(r);});let batch=[],rawRecords=0,dataRecords=0,malformed=0,qualified=0,rejected=0,review=0,expired=0;const reasons={},reviews={};const rl=readline.createInterface({input:entryStream(sourcePath,entry),crlfDelay:Infinity});for await(const line of rl){if(!line||/^BOF PUBLIC/i.test(line)||/^EOF PUBLIC/i.test(line))continue;rawRecords++;const f=line.split('|');if(f.length<116){malformed++;continue;}dataRecords++;const c=parseRecord(f);if(c.registrationStatus!=='A')expired++;const ev=this.eligibility.evaluate(c);if(ev.eligible){qualified++;batch.push({uei:c.uei,duns:c.duns,cage:c.cage,legalName:c.legalBusinessName||'(UNKNOWN)',dba:c.dbaName,purpose:c.purposeOfRegistration,expiration:c.registrationExpirationDate,updated:c.lastUpdateDate,activation:c.activationDate,website:c.website,entityStructure:c.entityStructure,businessTypes:c.businessTypeCodes.join('~'),primaryNaics:c.primaryNaics,naics:c.naicsCodes.join('~'),sba:c.sbaBusinessTypeCodes.join('~'),address1:c.address1,address2:c.address2,city:c.city,state:c.state,zip:c.zip,country:c.country,sourceFile:sourceName,sourceDate,loadedAt:now()});if(batch.length>=this.batchSize){tx(batch);batch=[];}}else if(ev.status==='REVIEW_REQUIRED'){review++;for(const r of ev.reviewReasons)reviews[r]=(reviews[r]||0)+1;}else{rejected++;for(const r of ev.reasons)reasons[r]=(reasons[r]||0)+1;}}
 if(batch.length)tx(batch);const stored=Number(db.prepare('SELECT COUNT(*) n FROM sam_qualified_companies').get().n);const manifest={sourceFile:sourceName,sourceDate,sourceBytes:fs.statSync(sourcePath).size,sourceSha256:sha256(sourcePath),entry:entry.fileName,entryUncompressedBytes:entry.uncompressedSize,policyId:this.eligibility.policy.policyId,policyVersion:this.eligibility.policy.version,rawRecords,dataRecords,malformed,qualified,stored,rejected,reviewRequired:review,expiredObserved:expired,rejectionReasons:reasons,reviewReasons:reviews,emailRequired:stored,emailPresent:0,emailEnrichmentRequired:stored,campaignEligible:0};const m=db.prepare('INSERT OR REPLACE INTO sam_qualification_manifest(key,value) VALUES(?,?)');for(const [k,v] of Object.entries(manifest))m.run(k,typeof v==='string'?v:JSON.stringify(v));db.pragma('wal_checkpoint(TRUNCATE)');db.close();fs.renameSync(partial,final);const result={ok:stored===qualified&&stored>0,service:'SAM_QUALIFIED_UNIVERSE_BUILD',generatedAt:now(),source:{file:sourcePath,fileName:sourceName,date:sourceDate,entry:entry.fileName,bytes:fs.statSync(sourcePath).size},output:{database:final,bytes:fs.statSync(final).size,storedQualifiedCompanies:stored},waterfall:manifest,nextStep:'DISCOVER_AND_REUSE_INTERNAL_EMAIL_CONTACT_TRUTH_THEN_GLOBAL_DEDUPE_AND_SEGMENT',safety:{productionDatabaseModified:false,oldSamActiveVersionDeleted:false,oldSamRetainedForEmailReuse:true,campaignsModified:false,emailsFabricated:false,allStoredLeadsBlockedFromOutboundUntilVerifiedEmail:true,stagingOnly:true}};fs.writeFileSync(this.reportPath,JSON.stringify(result,null,2),'utf8');console.log(JSON.stringify(result,null,2));return result;
 }catch(e){try{db?.close();}catch{}try{fs.unlinkSync(partial);}catch{}throw e;}}
}
module.exports=SamQualifiedUniverseBuildService;module.exports.parseRecord=parseRecord;module.exports.naicsCodes=naicsCodes;module.exports.splitCodes=splitCodes;
