'use strict';
const fs=require('fs');
const path=require('path');
const zlib=require('zlib');
const readline=require('readline');
const Eligibility=require('./SamLeadEligibilityService');

function now(){return new Date().toISOString();}
function splitCodes(v){return String(v||'').split('~').map(x=>x.trim()).filter(Boolean);}
function naicsCodes(v){const out=[];for(const token of splitCodes(v)){const m=token.match(/^(\d{6})/);if(m)out.push(m[1]);}return [...new Set(out)];}
function sbaCodes(v){return splitCodes(v).map(x=>x.slice(0,2)).filter(Boolean);}
function sourceDateFromName(name){return (String(name).match(/(20\d{6})/)||[])[1]||null;}
function findEocd(fd,size){const len=Math.min(size,65557),buf=Buffer.alloc(len);fs.readSync(fd,buf,0,len,size-len);for(let i=len-22;i>=0;i--)if(buf.readUInt32LE(i)===0x06054b50)return{buf,offset:size-len+i};throw new Error('ZIP_EOCD_NOT_FOUND');}
function zipEntries(zipPath){const fd=fs.openSync(zipPath,'r');try{const size=fs.fstatSync(fd).size,{buf,offset}=findEocd(fd,size),local=offset-(size-buf.length),total=buf.readUInt16LE(local+10),centralSize=buf.readUInt32LE(local+12),centralOffset=buf.readUInt32LE(local+16);if(total===0xffff||centralSize===0xffffffff||centralOffset===0xffffffff)throw new Error('ZIP64_NOT_SUPPORTED');const cd=Buffer.alloc(centralSize);fs.readSync(fd,cd,0,centralSize,centralOffset);const out=[];let p=0;for(let n=0;n<total&&p+46<=cd.length;n++){if(cd.readUInt32LE(p)!==0x02014b50)throw new Error(`ZIP_CENTRAL_SIGNATURE_INVALID:${p}`);const method=cd.readUInt16LE(p+10),compressedSize=cd.readUInt32LE(p+20),uncompressedSize=cd.readUInt32LE(p+24),nameLen=cd.readUInt16LE(p+28),extraLen=cd.readUInt16LE(p+30),commentLen=cd.readUInt16LE(p+32),localHeaderOffset=cd.readUInt32LE(p+42),fileName=cd.subarray(p+46,p+46+nameLen).toString('utf8');out.push({fileName,method,compressedSize,uncompressedSize,localHeaderOffset});p+=46+nameLen+extraLen+commentLen;}return out;}finally{fs.closeSync(fd);}}
function entryStream(zipPath,entry){const fd=fs.openSync(zipPath,'r'),h=Buffer.alloc(30);try{fs.readSync(fd,h,0,30,entry.localHeaderOffset);}finally{fs.closeSync(fd);}if(h.readUInt32LE(0)!==0x04034b50)throw new Error('ZIP_LOCAL_HEADER_INVALID');const start=entry.localHeaderOffset+30+h.readUInt16LE(26)+h.readUInt16LE(28),end=start+entry.compressedSize-1,raw=fs.createReadStream(zipPath,{start,end});if(entry.method===0)return raw;if(entry.method===8){const inflate=zlib.createInflateRaw();raw.pipe(inflate);return inflate;}throw new Error(`ZIP_COMPRESSION_METHOD_UNSUPPORTED:${entry.method}`);}
function parseRecord(f){const businessTypes=splitCodes(f[31]),naics=naicsCodes(f[34]),sba=sbaCodes(f[117]);return{uei:String(f[0]||'').trim(),duns:String(f[1]||'').trim(),cage:String(f[3]||'').trim(),registrationStatus:String(f[5]||'').trim(),purposeOfRegistration:String(f[6]||'').trim(),initialRegistrationDate:String(f[7]||'').trim(),registrationExpirationDate:String(f[8]||'').trim(),lastUpdateDate:String(f[9]||'').trim(),activationDate:String(f[10]||'').trim(),legalBusinessName:String(f[11]||'').trim(),dbaName:String(f[12]||'').trim(),address1:String(f[15]||'').trim(),address2:String(f[16]||'').trim(),city:String(f[17]||'').trim(),state:String(f[18]||'').trim(),zip:String(f[19]||'').trim(),country:String(f[21]||'').trim(),website:String(f[26]||'').trim(),entityStructure:String(f[27]||'').trim(),businessTypeCodes:businessTypes,primaryNaics:String(f[32]||'').trim(),naicsCodes:naics,exclusionStatusFlag:String(f[115]||'').trim(),sbaBusinessTypeCodes:sba,forProfit:businessTypes.includes('2X')};}

class SamQualifiedUniverseBuildService{
 constructor(options={}){this.rootDir=path.resolve(options.rootDir||process.env.MILES_ROOT||process.cwd());this.stageDir=path.join(this.rootDir,'DATA','orion_refresh','sam_bulk_staging');this.outDir=path.join(this.rootDir,'DATA','orion_refresh','sam_qualified_staging');this.reportPath=path.join(this.rootDir,'DATA','orion_refresh','latest_sam_qualified_universe_build.json');this.eligibility=new Eligibility({rootDir:this.rootDir});this.batchSize=Math.max(100,Number(options.batchSize||5000));}
 async run(){
  fs.mkdirSync(this.outDir,{recursive:true});const names=fs.existsSync(this.stageDir)?fs.readdirSync(this.stageDir):[],sourceName=names.filter(x=>/^SAM_PUBLIC_UTF-8_MONTHLY_V2_\d{8}\.ZIP$/i.test(x)).sort().reverse()[0];if(!sourceName)throw new Error('SAM_ENTITY_BULK_SOURCE_MISSING');const sourcePath=path.join(this.stageDir,sourceName),entry=zipEntries(sourcePath).filter(e=>e.uncompressedSize>0&&!/\/$/.test(e.fileName)).sort((a,b)=>b.uncompressedSize-a.uncompressedSize)[0];if(!entry)throw new Error('SAM_ENTITY_DATA_ENTRY_MISSING');const Database=require('better-sqlite3'),stamp=now().replace(/[:.]/g,'-'),sourceDate=sourceDateFromName(sourceName),final=path.join(this.outDir,`SAM_QUALIFIED_${sourceDate||'unknown'}_${stamp}.db`),partial=`${final}.partial`;try{fs.unlinkSync(partial);}catch{}
  let db=null;try{
   db=new Database(partial);db.pragma('journal_mode = DELETE');db.pragma('synchronous = NORMAL');db.exec(`CREATE TABLE sam_qualified_companies(uei TEXT PRIMARY KEY,duns TEXT,cage TEXT,legal_name TEXT NOT NULL,dba TEXT,purpose_registration TEXT,registration_expiration_date TEXT,last_update_date TEXT,activation_date TEXT,website TEXT,entity_structure TEXT,business_type_codes TEXT,primary_naics TEXT,naics_codes TEXT,sba_business_type_codes TEXT,address1 TEXT,address2 TEXT,city TEXT,state TEXT,zip TEXT,country TEXT,email TEXT,email_status TEXT NOT NULL DEFAULT 'ENRICHMENT_REQUIRED',email_source TEXT,email_verified_at TEXT,source_file TEXT NOT NULL,source_date TEXT,loaded_at TEXT NOT NULL);CREATE INDEX idx_samq_name ON sam_qualified_companies(legal_name);CREATE INDEX idx_samq_cage ON sam_qualified_companies(cage);CREATE INDEX idx_samq_primary_naics ON sam_qualified_companies(primary_naics);CREATE TABLE sam_qualification_manifest(key TEXT PRIMARY KEY,value TEXT NOT NULL);`);
   const insert=db.prepare(`INSERT OR REPLACE INTO sam_qualified_companies(uei,duns,cage,legal_name,dba,purpose_registration,registration_expiration_date,last_update_date,activation_date,website,entity_structure,business_type_codes,primary_naics,naics_codes,sba_business_type_codes,address1,address2,city,state,zip,country,email,email_status,email_source,email_verified_at,source_file,source_date,loaded_at) VALUES(@uei,@duns,@cage,@legalName,@dba,@purpose,@expiration,@updated,@activation,@website,@entityStructure,@businessTypes,@primaryNaics,@naics,@sba,@address1,@address2,@city,@state,@zip,@country,NULL,'ENRICHMENT_REQUIRED',NULL,NULL,@sourceFile,@sourceDate,@loadedAt)`),tx=db.transaction(rows=>{for(const r of rows)insert.run(r);});let batch=[],rawRecords=0,dataRecords=0,malformed=0,qualified=0,rejected=0,review=0,expired=0;const reasons={},reviews={},loadedAt=now(),rl=readline.createInterface({input:entryStream(sourcePath,entry),crlfDelay:Infinity});
   for await(const line of rl){if(!line||/^BOF PUBLIC/i.test(line)||/^EOF PUBLIC/i.test(line))continue;rawRecords++;const f=line.split('|');if(f.length<118){malformed++;continue;}dataRecords++;const c=parseRecord(f);if(!c.uei){malformed++;continue;}if(c.registrationStatus!=='A')expired++;const ev=this.eligibility.evaluate(c);if(ev.eligible){qualified++;batch.push({uei:c.uei,duns:c.duns,cage:c.cage,legalName:c.legalBusinessName||'(UNKNOWN)',dba:c.dbaName,purpose:c.purposeOfRegistration,expiration:c.registrationExpirationDate,updated:c.lastUpdateDate,activation:c.activationDate,website:c.website,entityStructure:c.entityStructure,businessTypes:c.businessTypeCodes.join('~'),primaryNaics:c.primaryNaics,naics:c.naicsCodes.join('~'),sba:c.sbaBusinessTypeCodes.join('~'),address1:c.address1,address2:c.address2,city:c.city,state:c.state,zip:c.zip,country:c.country,sourceFile:sourceName,sourceDate,loadedAt});if(batch.length>=this.batchSize){tx(batch);batch=[];}}else if(ev.status==='REVIEW_REQUIRED'){review++;for(const r of ev.reviewReasons)reviews[r]=(reviews[r]||0)+1;}else{rejected++;for(const r of ev.reasons)reasons[r]=(reasons[r]||0)+1;}}
   if(batch.length)tx(batch);const stored=Number(db.prepare('SELECT COUNT(*) n FROM sam_qualified_companies').get().n),manifest={sourceFile:sourceName,sourceDate,sourceBytes:fs.statSync(sourcePath).size,entry:entry.fileName,entryUncompressedBytes:entry.uncompressedSize,policyId:this.eligibility.policy.policyId,policyVersion:this.eligibility.policy.version,rawRecords,dataRecords,malformed,qualified,uniqueQualified:stored,duplicateQualifiedRecords:Math.max(0,qualified-stored),stored,rejected,reviewRequired:review,expiredObserved:expired,rejectionReasons:reasons,reviewReasons:reviews,emailRequired:stored,emailPresent:0,emailEnrichmentRequired:stored,campaignEligible:0};const m=db.prepare('INSERT OR REPLACE INTO sam_qualification_manifest(key,value) VALUES(?,?)');for(const [k,v] of Object.entries(manifest))m.run(k,typeof v==='string'?v:JSON.stringify(v));const integrity=db.pragma('integrity_check',{simple:true});db.close();db=null;if(integrity!=='ok'||stored<=0||stored>qualified)throw new Error(`SAM_QUALIFIED_VALIDATION_FAILED:${integrity}:${stored}:${qualified}`);fs.renameSync(partial,final);const result={ok:true,service:'SAM_QUALIFIED_UNIVERSE_BUILD',generatedAt:now(),source:{file:sourcePath,fileName:sourceName,date:sourceDate,entry:entry.fileName,bytes:fs.statSync(sourcePath).size},output:{database:final,bytes:fs.statSync(final).size,sqliteIntegrity:integrity,storedQualifiedCompanies:stored},waterfall:manifest,nextStep:'DISCOVER_AND_REUSE_INTERNAL_EMAIL_CONTACT_TRUTH_THEN_GLOBAL_DEDUPE_AND_SEGMENT',safety:{productionDatabaseModified:false,oldSamActiveVersionDeleted:false,oldSamRetainedForEmailReuse:true,campaignsModified:false,emailsFabricated:false,allStoredLeadsBlockedFromOutboundUntilVerifiedEmail:true,stagingOnly:true}};fs.writeFileSync(this.reportPath,JSON.stringify(result,null,2),'utf8');console.log(JSON.stringify(result,null,2));return result;
  }catch(e){try{db?.close();}catch{}try{fs.unlinkSync(partial);}catch{}throw e;}
 }
}
module.exports=SamQualifiedUniverseBuildService;module.exports.parseRecord=parseRecord;module.exports.naicsCodes=naicsCodes;module.exports.splitCodes=splitCodes;
