'use strict';
/*
 P1.5K7B — Canonical Federal Master rebuild + source promotion gate.
 Purpose:
 - Recover the freshest usable GSA / VA-FSS / certification / SAM / award evidence already on disk.
 - Join only by UEI.
 - Produce ONE canonical federal contractor master + tier counts.
 - Register exact source lineage and freshness.
 - Never mutate Instantly.

 This service deliberately refuses to promote a source merely because a filename exists.
 A promoted source must demonstrate usable UEIs and category-specific evidence.
*/
const fs=require('fs');
const path=require('path');
const readline=require('readline');
const ROOT=process.cwd();
const OUTDIR=path.join(ROOT,'DATA','OUTBOUND','CANONICAL_FEDERAL_MASTER_K7B');
const MASTER=path.join(OUTDIR,'CANONICAL_FEDERAL_CONTRACTOR_MASTER.csv');
const SUMMARY=path.join(OUTDIR,'CANONICAL_FEDERAL_MASTER_K7B_SUMMARY.json');
const REGISTRY=path.join(OUTDIR,'CANONICAL_SOURCE_REGISTRY.json');
const ROOTS=['D:\\P2GC_Intelligence'];
const EXCLUDE_RE=/(\\_BACKUPS\\|\\node_modules\\|\\\.git\\|\\DATA\\OUTBOUND\\CANONICAL_FEDERAL_MASTER_K7B\\)/i;
const MAX_FILES=2200;
const SAMPLE_ROWS=3000;
const STALE_DAYS=45;
const FAMS=['GSA','VA_FSS','SDVOSB','VOSB','WOSB','HUBZONE','8A','SBS_SAM'];
const TIERS=['NO_SALES','ONE_TO_LT_3M','THREE_TO_LT_10M','TEN_M_PLUS','UNKNOWN'];
function s(v){return String(v??'').trim()}
function low(v){return s(v).toLowerCase()}
function k(v){return low(v).replace(/[^a-z0-9]/g,'')}
function esc(v){const x=s(v);return /[",\r\n]/.test(x)?'"'+x.replace(/"/g,'""')+'"':x}
function money(v){if(v==null||s(v)==='')return null;const n=Number(String(v).replace(/[$,]/g,''));return Number.isFinite(n)?n:null}
function tier(n){return n==null?'UNKNOWN':n===0?'NO_SALES':n<3000000?'ONE_TO_LT_3M':n<10000000?'THREE_TO_LT_10M':'TEN_M_PLUS'}
function truthy(v){return /^(1|true|yes|y|active|certified|current|eligible)$/i.test(s(v))}
function parseLine(line){const out=[];let f='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(q){if(c==='"'&&line[i+1]==='"'){f+='"';i++}else if(c==='"')q=false;else f+=c}else{if(c==='"')q=true;else if(c===','){out.push(f);f=''}else f+=c}}out.push(f);return out}
function fm(headers,vals){const m={};for(let i=0;i<headers.length;i++)m[k(headers[i])]=vals[i]??'';return m}
function first(m,names){for(const n of names){const v=m[k(n)];if(s(v)!=='')return v}return null}
function uei(m){return s(first(m,['uei','recipient uei','uei_sam','norm_uei','uei_clean','UEI (Unique Entity Identifier)'])).toUpperCase()||null}
function name(m){return s(first(m,['legal_name','recipient name','business name','company','company_name','company_clean','name_clean']))}
function daysOld(ms){return (Date.now()-ms)/86400000}
async function walk(dir,out){if(out.length>=MAX_FILES||!fs.existsSync(dir))return;let ents;try{ents=fs.readdirSync(dir,{withFileTypes:true})}catch{return}for(const e of ents){if(out.length>=MAX_FILES)return;const p=path.join(dir,e.name);if(EXCLUDE_RE.test(p))continue;if(e.isDirectory())await walk(p,out);else if(/\.csv$/i.test(e.name)){try{const st=fs.statSync(p);out.push({path:p,size:st.size,mtimeMs:st.mtimeMs,mtime:new Date(st.mtimeMs).toISOString()})}catch{}}}}
async function sampleCsv(file,maxRows=SAMPLE_ROWS){const rs=fs.createReadStream(file,{encoding:'utf8'});const rl=readline.createInterface({input:rs,crlfDelay:Infinity});let headers=null,rows=0,ueiCount=0,gsa=0,va=0,revenueNumeric=0,revenuePositive=0,cert=0,sam=0;for await(const line of rl){if(!headers){headers=parseLine(line).map(s);continue}if(!line.trim())continue;const vals=parseLine(line),m=fm(headers,vals),id=uei(m);if(id)ueiCount++;const veh=s(first(m,['vehicle','fed_vehicle','vehicle_hint','contract_vehicle'])).toUpperCase();const seg=s(first(m,['segment','existing_segment','govcon_performance_segment'])).toUpperCase();const contract=s(first(m,['gsa_contract_number','contract_number'])).toUpperCase();if(/\bGSA\b|\bMAS\b|MULTIPLE AWARD SCHEDULE/.test(veh+' '+seg+' '+contract))gsa++;
if(/\bVA\b|\bFSS\b|VETERANS AFFAIRS|FEDERAL SUPPLY SCHEDULE/.test(veh+' '+seg))va++;
const rv=money(first(m,['Federal_Total_Revenue','NORMALIZED_REVENUE','federal_total_revenue','federal_revenue','total_revenue']));if(rv!=null){revenueNumeric++;if(rv>0)revenuePositive++}
const blob=(s(first(m,['Active SBA certifications']))+' '+s(first(m,['Business type and self-certifications']))+' '+seg).toUpperCase();if(/SDVOSB|VOSB|WOSB|HUB ?ZONE|8\(A\)|(^|\W)8A(\W|$)/.test(blob)||['is_sdvosb','is_vosb','is_wosb','is_hubzone','is_8a'].some(x=>truthy(first(m,[x]))))cert++;
if(truthy(first(m,['Small_Business_Flag']))||/SMALL BUSINESS|SBS|SAM/.test(seg+' '+veh))sam++;
rows++;if(rows>=maxRows){rl.close();rs.destroy();break}}
return{headers:headers||[],rows,ueiCount,gsa,va,revenueNumeric,revenuePositive,cert,sam}}
function sourceScore(meta,sm,kind){const age=daysOld(meta.mtimeMs);let x=Math.max(0,80-age);x+=Math.min(40,sm.ueiCount/100);if(kind==='vehicle')x+=Math.min(100,(sm.gsa+sm.va)/20);if(kind==='revenue')x+=Math.min(100,sm.revenueNumeric/20)+Math.min(50,sm.revenuePositive/10);if(kind==='certification')x+=Math.min(100,sm.cert/10);if(kind==='sam')x+=Math.min(100,sm.sam/20);if(/archive/i.test(meta.path))x-=15;if(/email_ready|campaign/i.test(meta.path))x-=20;return Math.round(x*100)/100}
function qualifies(sm,kind){if(sm.ueiCount<10)return false;if(kind==='vehicle')return sm.gsa+sm.va>=10;if(kind==='revenue')return sm.revenueNumeric>=10;if(kind==='certification')return sm.cert>=5;if(kind==='sam')return sm.sam>=10;return false}
async function discover(){const files=[];for(const r of ROOTS)await walk(r,files);const inspected=[];for(const meta of files){let sm;try{sm=await sampleCsv(meta.path)}catch{continue}if(!sm.headers.length)continue;const entry={...meta,ageDays:Math.round(daysOld(meta.mtimeMs)*10)/10,sample:sm,scores:{}};for(const kind of ['vehicle','revenue','certification','sam'])entry.scores[kind]=sourceScore(meta,sm,kind);inspected.push(entry)}
const selected={};for(const kind of ['vehicle','revenue','certification','sam']){const pool=inspected.filter(x=>qualifies(x.sample,kind)).sort((a,b)=>b.scores[kind]-a.scores[kind]||b.mtimeMs-a.mtimeMs);selected[kind]=pool[0]||null}
return{filesFound:files.length,filesInspected:inspected.length,selected,topCandidates:Object.fromEntries(['vehicle','revenue','certification','sam'].map(kind=>[kind,inspected.filter(x=>qualifies(x.sample,kind)).sort((a,b)=>b.scores[kind]-a.scores[kind]).slice(0,10).map(x=>({path:x.path,mtime:x.mtime,ageDays:x.ageDays,score:x.scores[kind],sample:{rows:x.sample.rows,uei:x.sample.ueiCount,gsa:x.sample.gsa,va:x.sample.va,revenueNumeric:x.sample.revenueNumeric,revenuePositive:x.sample.revenuePositive,cert:x.sample.cert,sam:x.sample.sam}}))]))}}
function ensure(rec,id){if(!rec.has(id))rec.set(id,{uei:id,name:'',families:new Set(),revenueValues:[],awardCount:null,sources:new Set()});return rec.get(id)}
async function stream(file,onRow){const rs=fs.createReadStream(file,{encoding:'utf8'});const rl=readline.createInterface({input:rs,crlfDelay:Infinity});let headers=null,rows=0;for await(const line of rl){if(!headers){headers=parseLine(line).map(s);continue}if(!line.trim())continue;const vals=parseLine(line),m=fm(headers,vals);await onRow(m);rows++}return rows}
async function loadVehicle(rec,file){return stream(file,m=>{const id=uei(m);if(!id)return;const r=ensure(rec,id),nm=name(m);if(nm&&!r.name)r.name=nm;r.sources.add(file);const txt=(s(first(m,['vehicle','fed_vehicle','vehicle_hint','contract_vehicle']))+' '+s(first(m,['segment','existing_segment']))+' '+s(first(m,['gsa_contract_number']))).toUpperCase();if(/\bGSA\b|\bMAS\b|MULTIPLE AWARD SCHEDULE/.test(txt))r.families.add('GSA');if(/\bVA\b|\bFSS\b|VETERANS AFFAIRS|FEDERAL SUPPLY SCHEDULE/.test(txt))r.families.add('VA_FSS')})}
async function loadRevenue(rec,file){return stream(file,m=>{const id=uei(m);if(!id)return;const r=ensure(rec,id),nm=name(m);if(nm&&!r.name)r.name=nm;r.sources.add(file);const rv=money(first(m,['Federal_Total_Revenue','NORMALIZED_REVENUE','federal_total_revenue','federal_revenue','total_revenue']));if(rv!=null)r.revenueValues.push(rv);const ac=money(first(m,['Federal_Award_Count','NORMALIZED_AWARD_COUNT','award_count']));if(ac!=null)r.awardCount=Math.max(r.awardCount??0,ac)})}
async function loadCert(rec,file){return stream(file,m=>{const id=uei(m);if(!id)return;const r=ensure(rec,id),nm=name(m);if(nm&&!r.name)r.name=nm;r.sources.add(file);const blob=(s(first(m,['Active SBA certifications']))+' '+s(first(m,['Business type and self-certifications']))+' '+s(first(m,['segment','existing_segment']))).toUpperCase();const tests=[['SDVOSB',/SDVOSB|SERVICE[- ]DISABLED VETERAN/,['is_sdvosb']],['VOSB',/(^|\W)VOSB(\W|$)|VETERAN[- ]OWNED/,['is_vosb']],['WOSB',/WOSB|WOMEN[- ]OWNED/,['is_wosb']],['HUBZONE',/HUB ?ZONE/,['is_hubzone']],['8A',/8\(A\)|(^|\W)8A(\W|$)/,['is_8a']]];for(const [fam,re,fields] of tests)if(re.test(blob)||fields.some(f=>truthy(first(m,[f]))))r.families.add(fam)})}
async function loadSam(rec,file){return stream(file,m=>{const id=uei(m);if(!id)return;const r=ensure(rec,id),nm=name(m);if(nm&&!r.name)r.name=nm;r.sources.add(file);if(truthy(first(m,['Small_Business_Flag']))||/SMALL BUSINESS|SBS|SAM/.test((s(first(m,['segment','industry_segment','vehicle']))).toUpperCase()))r.families.add('SBS_SAM')})}
function summarize(rec){const counts={};for(const f of FAMS)counts[f]=Object.fromEntries(TIERS.map(t=>[t,0]));let unknown=0,conflicts=0;for(const r of rec.values()){const vals=[...new Set(r.revenueValues.filter(Number.isFinite))];if(vals.length>1)conflicts++;const rev=vals.length?Math.max(...vals):null;const t=tier(rev);if(t==='UNKNOWN'&&r.families.size)unknown++;for(const f of r.families)counts[f][t]++}return{uniqueEntities:rec.size,counts,unknownRevenueEntities:unknown,conflictingRevenueEntities:conflicts}}
function writeMaster(rec){const ws=fs.createWriteStream(MASTER,{encoding:'utf8'});ws.write('uei,legal_name,families,federal_revenue,award_count,revenue_tier,source_files\n');for(const r of rec.values()){if(!r.families.size)continue;const vals=[...new Set(r.revenueValues.filter(Number.isFinite))],rev=vals.length?Math.max(...vals):null;ws.write([r.uei,r.name,[...r.families].join('|'),rev==null?'':rev,r.awardCount==null?'':r.awardCount,tier(rev),[...r.sources].join('|')].map(esc).join(',')+'\n')}ws.end()}
async function run(){fs.mkdirSync(OUTDIR,{recursive:true});const discovery=await discover();const selected=Object.fromEntries(Object.entries(discovery.selected).map(([k,v])=>[k,v?{path:v.path,mtime:v.mtime,ageDays:v.ageDays,score:v.scores[k],sample:v.sample}:null]));const missing=Object.entries(selected).filter(([,v])=>!v).map(([k])=>k);const stale=Object.entries(selected).filter(([,v])=>v&&v.ageDays>STALE_DAYS).map(([k])=>k);const rec=new Map();const loadStats={};if(selected.vehicle)loadStats.vehicle=await loadVehicle(rec,selected.vehicle.path);if(selected.revenue)loadStats.revenue=await loadRevenue(rec,selected.revenue.path);if(selected.certification)loadStats.certification=await loadCert(rec,selected.certification.path);if(selected.sam)loadStats.sam=await loadSam(rec,selected.sam.path);const summary=summarize(rec);writeMaster(rec);const gates={allSourcesSelected:missing.length===0,sourcesFreshWithin30DayProgram:stale.length===0,gsaPresent:Object.values(summary.counts.GSA).reduce((a,b)=>a+b,0)>0,vaFssPresent:Object.values(summary.counts.VA_FSS).reduce((a,b)=>a+b,0)>0,revenueTierHasPositiveDistribution:FAMS.some(f=>summary.counts[f].ONE_TO_LT_3M+summary.counts[f].THREE_TO_LT_10M+summary.counts[f].TEN_M_PLUS>0),noRevenueConflicts:summary.conflictingRevenueEntities===0};const authoritativeEnoughToResegment=Object.values(gates).every(Boolean);const registry={version:'1.0',promotedAt:new Date().toISOString(),refreshPolicyDays:30,staleThresholdDays:STALE_DAYS,joinKey:'UEI',selectedSources:selected,gates,authoritativeEnoughToResegment};fs.writeFileSync(REGISTRY,JSON.stringify(registry,null,2));const result={ok:true,gate:'P1.5K7B_CANONICAL_FEDERAL_MASTER_REBUILD',version:'1.0-source-promotion-gated',generatedAt:new Date().toISOString(),discovery:{filesFound:discovery.filesFound,filesInspected:discovery.filesInspected,topCandidates:discovery.topCandidates},selectedSources:selected,missingSources:missing,staleSources:stale,loadStats,reconstruction:summary,gates,authoritativeEnoughToResegment,liveCampaignsMutated:false,refreshControl:{requiredCadenceDays:30,proofArtifact:REGISTRY,nextDueRule:'selected source evidence must be <=45 days old before promotion'},outputs:{master:MASTER,registry:REGISTRY,summary:SUMMARY},nextAction:authoritativeEnoughToResegment?'BUILD_GOVERNED_SEGMENT_FILES_FROM_CANONICAL_MASTER':'DO_NOT_TOUCH_INSTANTLY; FIX_STALE_OR_WEAK_PROMOTED_SOURCE(S) AND RERUN'};fs.writeFileSync(SUMMARY,JSON.stringify(result,null,2));return result}
module.exports={run};if(require.main===module)run().then(r=>console.dir(r,{depth:8,maxArrayLength:20})).catch(e=>{console.error(e);process.exit(1)});
