'use strict';
const fs=require('fs');const path=require('path');
const ROOT='D:\\P2GC_Intelligence';
const OUT=path.join(process.cwd(),'DATA','OUTBOUND','FEDERAL_REFRESH_RECOVERY_K7C');
const MAX_FILES=2500, MAX_BYTES=1024*1024, MAX_ROWS=2500;
const SKIP=/node_modules|\\\.git|CANONICAL_FEDERAL_MASTER_K7B|FEDERAL_REFRESH_RECOVERY_K7C|PRODUCTION_CHECKPOINTS|_BACKUPS/i;
const WANT=/(gsa|mas|fss|\\va|award|spending|sam|sbs|contract)/i;
function walk(d,a=[]){if(a.length>=MAX_FILES)return a;let es;try{es=fs.readdirSync(d,{withFileTypes:true});}catch{return a;}for(const e of es){if(a.length>=MAX_FILES)break;const p=path.join(d,e.name);if(e.isDirectory()){if(!SKIP.test(p))walk(p,a);}else if(/\.csv$/i.test(e.name)&&WANT.test(p))a.push(p);}return a;}
function csvLine(s){let a=[],x='',q=false;for(let i=0;i<s.length;i++){let c=s[i];if(c==='"'){if(q&&s[i+1]==='"'){x+='"';i++;}else q=!q;}else if(c===','&&!q){a.push(x);x='';}else x+=c;}a.push(x);return a;}
function headText(p,bytes){let fd;try{fd=fs.openSync(p,'r');let b=Buffer.alloc(bytes),n=fs.readSync(fd,b,0,bytes,0);return b.subarray(0,n).toString('utf8');}catch{return null;}finally{if(fd!==undefined)try{fs.closeSync(fd);}catch{}}}
function inspect(p){let st;try{st=fs.statSync(p);}catch{return null;}let txt=headText(p,Math.min(MAX_BYTES,st.size));if(!txt)return null;let ls=txt.split(/\r?\n/).filter(Boolean).slice(0,MAX_ROWS+1);if(ls.length<2)return null;let h=csvLine(ls[0]).map(x=>x.trim()),hl=h.map(x=>x.toLowerCase()),idx=(re)=>hl.findIndex(x=>re.test(x));let ui=idx(/^(uei|recipient uei|uei \(unique entity identifier\))$/),vi=idx(/^(vehicle|vehicle_name|vehicle_hint|fed_vehicle)$/),ri=idx(/^(federal_revenue|federal_total_revenue|normalized_revenue|total_obligated_amount|federal_total_revenue_x)$/),si=idx(/^(segment|existing_segment|govcon_performance_segment)$/),src=idx(/source/);let g=0,v=0,u=0,pos=0,zero=0;for(let i=1;i<ls.length;i++){let r=csvLine(ls[i]),ue=ui>=0?(r[ui]||'').trim():'';if(ue)u++;let z=((vi>=0?r[vi]:'')+' '+(si>=0?r[si]:'')+' '+(src>=0?r[src]:'')).toUpperCase();if(/\bGSA\b|\bMAS\b/.test(z))g++;if(/\bVA\b|\bFSS\b/.test(z))v++;if(ri>=0){let raw=String(r[ri]||'').replace(/[$,]/g,'').trim();if(raw!==''){let n=Number(raw);if(Number.isFinite(n)){if(n>0)pos++;else zero++;}}}}let age=(Date.now()-st.mtimeMs)/86400000;return{path:p,mtime:st.mtime.toISOString(),ageDays:+age.toFixed(1),size:st.size,bytesSampled:Math.min(MAX_BYTES,st.size),rowsSampled:ls.length-1,uei:u,gsa:g,va:v,revenuePositive:pos,revenueZero:zero,headers:h.slice(0,60)};}
function score(x,type){let n=x.path.toLowerCase(),s=Math.max(0,120-x.ageDays)+(x.uei?30:0);if(type==='GSA')s+=x.gsa?80:0;if(type==='VA')s+=x.va?80:0;if(type==='AWARD')s+=x.revenuePositive?80:0;if(/raw|download|export|master|contract_award|usa spending|sam_public|clean_gsa_va/.test(n))s+=20;if(/outbound|segment|no_sales|expired|email_ready|archive/.test(n))s-=45;return+s.toFixed(2);}
async function run(){fs.mkdirSync(OUT,{recursive:true});let files=walk(ROOT,[]),cand=[];for(let i=0;i<files.length;i++){let x=inspect(files[i]);if(x)cand.push(x);if((i+1)%250===0)console.error(`[K7C] inspected ${i+1}/${files.length}`);}let rank=t=>[...cand].sort((a,b)=>score(b,t)-score(a,t)).slice(0,25);let top={GSA:rank('GSA'),VA:rank('VA'),AWARD:rank('AWARD')};let fresh={GSA:top.GSA.filter(x=>x.ageDays<=45&&x.gsa>0),VA:top.VA.filter(x=>x.ageDays<=45&&x.va>0),AWARD:top.AWARD.filter(x=>x.ageDays<=45&&x.revenuePositive>0)};let proven=!!(fresh.GSA.length&&fresh.VA.length&&fresh.AWARD.length);let result={ok:true,gate:'P1.5K7C_FEDERAL_REFRESH_RECOVERY',version:'1.1-bounded-io',generatedAt:new Date().toISOString(),limits:{maxFiles:MAX_FILES,maxBytesPerFile:MAX_BYTES,maxRowsPerFile:MAX_ROWS},filesScanned:files.length,candidatesInspected:cand.length,topCandidates:top,freshAuthoritativeCandidates:{GSA:fresh.GSA.slice(0,10),VA:fresh.VA.slice(0,10),AWARD:fresh.AWARD.slice(0,10)},refreshStatus:{gsaFresh:!!fresh.GSA.length,vaFssFresh:!!fresh.VA.length,awardFresh:!!fresh.AWARD.length,monthlyProgramProven:proven},liveCampaignsMutated:false,nextAction:proven?'REVIEW_FRESH_CANDIDATES_FOR_CANONICAL_PROMOTION':'REFRESH_MISSING_AUTHORITATIVE_SOURCE_NOW; DO_NOT_TOUCH_INSTANTLY'};fs.writeFileSync(path.join(OUT,'K7C_REFRESH_RECOVERY.json'),JSON.stringify(result,null,2));return result;}module.exports={run};