'use strict';
const fs=require('fs');
const path=require('path');
const AwardHistoryTruthService=require('./orion/AwardHistoryTruthService');
const OUT=path.join(process.cwd(),'DATA','staging','government_data','K7F_VA_FSS_BULK_AWARD_REFRESH');
const CCST='https://www.vendorportal.ecms.va.gov';
const SEARCH='/NAC/Search';
function sleep(ms){return new Promise(r=>setTimeout(r,ms));}
function clean(s){return String(s||'').replace(/&amp;/g,'&').replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();}
function norm(s){return clean(s).toUpperCase().replace(/[^A-Z0-9]+/g,' ').replace(/\s+/g,' ').trim();}
function csv(v){v=String(v??'');return /[",\n]/.test(v)?'"'+v.replace(/"/g,'""')+'"':v;}
async function fetchText(url,tries=3){let last;for(let i=0;i<tries;i++){try{let r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 MILES-P2GC/1.0'}});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return await r.text();}catch(e){last=e;await sleep(800*(i+1));}}throw last;}
function extractSinValues(html){let vals=new Set();for(const m of html.matchAll(/<option[^>]+value=["']([^"']+)["'][^>]*>/gi)){let v=clean(m[1]);if(v&&v.length<=32&&/[A-Z0-9]/i.test(v)&&!/^select$/i.test(v))vals.add(v);}return [...vals];}
function parseVendorRows(html,sin){let out=[];let rows=[...html.matchAll(/<tr[^>]*>([\s\S]*?)<\/tr>/gi)].map(x=>x[1]);for(const row of rows){let cells=[...row.matchAll(/<t[dh][^>]*>([\s\S]*?)<\/t[dh]>/gi)].map(x=>clean(x[1]));if(cells.length<2)continue;let vendor=cells[0],contract=cells[1];if(!vendor||!contract||/contractor name/i.test(vendor)||!/\d|V797|36F797/i.test(contract))continue;out.push({vendor,contractNumber:contract,sin,small:cells[2]||'',veteranOwned:cells[3]||'',sdvosb:cells[4]||'',sdb:cells[5]||'',eightA:cells[6]||'',womanOwned:cells[7]||'',hubzone:cells[8]||''});}return out;}
async function buildVaRoster(opts={}){fs.mkdirSync(OUT,{recursive:true});let html=await fetchText(CCST+SEARCH);let sins=extractSinValues(html);if(opts.maxSins)sins=sins.slice(0,opts.maxSins);let all=[];let checkpoint=path.join(OUT,'VA_FSS_CONTRACT_ROSTER_PARTIAL.json');let done=new Set();if(fs.existsSync(checkpoint)){try{let j=JSON.parse(fs.readFileSync(checkpoint,'utf8'));all=j.rows||[];done=new Set(j.completedSins||[]);}catch{}}
for(let i=0;i<sins.length;i++){let sin=sins[i];if(done.has(sin))continue;try{let page=await fetchText(`${CCST}/NAC/Vendor/List?sin=${encodeURIComponent(sin)}`);all.push(...parseVendorRows(page,sin));done.add(sin);}catch(e){console.error(`[K7F] VA SIN ${sin} failed: ${e.message}`);}if((i+1)%20===0){console.log(`[K7F] VA SIN progress ${i+1}/${sins.length}; rows=${all.length}`);fs.writeFileSync(checkpoint,JSON.stringify({completedSins:[...done],rows:all},null,2));}await sleep(Number(opts.vaDelayMs)||120);}
let map=new Map();for(const r of all){let k=`${r.contractNumber}|${norm(r.vendor)}`;if(!map.has(k))map.set(k,r);}let rows=[...map.values()];fs.writeFileSync(path.join(OUT,'VA_FSS_CONTRACT_ROSTER.csv'),['vendor,contract_number,sin,small,veteran_owned,sdvosb,sdb,eight_a,woman_owned,hubzone',...rows.map(r=>[r.vendor,r.contractNumber,r.sin,r.small,r.veteranOwned,r.sdvosb,r.sdb,r.eightA,r.womanOwned,r.hubzone].map(csv).join(','))].join('\n'));
return {sinsDiscovered:sins.length,contracts:rows.length,rows};}
async function resolveVaUeis(rows,opts={}){let svc=new AwardHistoryTruthService({requestTimeoutMs:20000});let out=[];let checkpoint=path.join(OUT,'VA_FSS_UEI_RESOLUTION.json');let done=new Map();if(fs.existsSync(checkpoint)){try{for(const r of JSON.parse(fs.readFileSync(checkpoint,'utf8')).rows||[])done.set(`${r.contractNumber}|${norm(r.vendor)}`,r);}catch{}}
for(let i=0;i<rows.length;i++){let r=rows[i],k=`${r.contractNumber}|${norm(r.vendor)}`;if(done.has(k)){out.push(done.get(k));continue;}let rec={...r,uei:'',ueiStatus:'UNRESOLVED'};try{let candidates=await svc.resolveRecipientByKeyword(r.vendor);let exact=candidates.filter(x=>norm(x?.name)===norm(r.vendor)&&String(x?.uei||'').trim());let unique=[...new Map(exact.map(x=>[String(x.uei).trim().toUpperCase(),x])).values()];if(unique.length===1){rec.uei=String(unique[0].uei).trim().toUpperCase();rec.ueiStatus='USASPENDING_EXACT_LEGAL_NAME';}else rec.ueiStatus=unique.length>1?'AMBIGUOUS_EXACT_NAME':'NO_EXACT_NAME_MATCH';}catch(e){rec.ueiStatus='LOOKUP_ERROR';rec.error=e.message;}out.push(rec);done.set(k,rec);if((i+1)%25===0){console.log(`[K7F] VA UEI progress ${i+1}/${rows.length}`);fs.writeFileSync(checkpoint,JSON.stringify({rows:out},null,2));}await sleep(Number(opts.identityDelayMs)||180);}
fs.writeFileSync(path.join(OUT,'VA_FSS_UEI_RESOLVED.csv'),['vendor,contract_number,sin,uei,uei_status',...out.map(r=>[r.vendor,r.contractNumber,r.sin,r.uei,r.ueiStatus].map(csv).join(','))].join('\n'));return out;}
function loadGsaUeis(){let root=path.join(process.cwd(),'DATA','staging','government_data','gsa_holder_snapshot');let dirs=[];try{dirs=fs.readdirSync(root).map(n=>path.join(root,n)).filter(p=>fs.statSync(p).isDirectory()).sort((a,b)=>fs.statSync(b).mtimeMs-fs.statSync(a).mtimeMs);}catch{}for(const d of dirs){let p=path.join(d,'gsa_elibrary_schedule_MAS.csv');if(!fs.existsSync(p))continue;let txt=fs.readFileSync(p,'utf8'),ls=txt.split(/\r?\n/);let h=(ls[0]||'').split(',').map(x=>x.replace(/^"|"$/g,'').trim());let i=h.findIndex(x=>/^SAM UEI$/i.test(x));if(i<0)continue;let s=new Set();for(let n=1;n<ls.length;n++){let cols=ls[n].match(/("(?:[^"]|"")*"|[^,]*)(?:,|$)/g)?.map(x=>x.replace(/,$/,'').replace(/^"|"$/g,'').replace(/""/g,'"'))||[];let u=String(cols[i]||'').trim().toUpperCase();if(u)s.add(u);}return [...s];}return [];}
async function bulkAwards(ueis,opts={}){let svc=new AwardHistoryTruthService({requestTimeoutMs:30000});let cp=path.join(OUT,'BULK_AWARD_TRUTH_CHECKPOINT.json');let state={completed:{},errors:{}};if(fs.existsSync(cp)){try{state=JSON.parse(fs.readFileSync(cp,'utf8'));}catch{}}let limit=Number(opts.awardLimit)||ueis.length;let todo=ueis.filter(u=>!state.completed[u]&&!state.errors[u]).slice(0,limit);for(let i=0;i<todo.length;i++){let u=todo[i];try{let r=await svc.auditByUei(u,{pageSize:100,maxPages:Number(opts.maxPages)||25});state.completed[u]={uei:u,ok:r.ok,status:r.status,federalRevenue:r.federalRevenue||0,awardCount:r.awardCount||0,primeAwardedRevenue:r.primeAwardedRevenue||0,subcontractedRevenue:r.subcontractedRevenue||0,generatedAt:r.generatedAt||new Date().toISOString()};}catch(e){state.errors[u]={uei:u,error:e.message,at:new Date().toISOString()};}if((i+1)%10===0){console.log(`[K7F] award progress ${i+1}/${todo.length}; totalCompleted=${Object.keys(state.completed).length}`);fs.writeFileSync(cp,JSON.stringify(state,null,2));}await sleep(Number(opts.awardDelayMs)||220);}fs.writeFileSync(cp,JSON.stringify(state,null,2));let rows=Object.values(state.completed);fs.writeFileSync(path.join(OUT,'BULK_AWARD_TRUTH.csv'),['uei,federal_revenue,award_count,prime_revenue,subcontract_revenue,status,generated_at',...rows.map(r=>[r.uei,r.federalRevenue,r.awardCount,r.primeAwardedRevenue,r.subcontractedRevenue,r.status,r.generatedAt].map(csv).join(','))].join('\n'));return {completed:rows.length,errors:Object.keys(state.errors).length,remaining:Math.max(0,ueis.length-rows.length-Object.keys(state.errors).length),output:path.join(OUT,'BULK_AWARD_TRUTH.csv')};}
async function run(opts={}){fs.mkdirSync(OUT,{recursive:true});let va=await buildVaRoster(opts);let vaResolved=await resolveVaUeis(va.rows,opts);let vaUeis=[...new Set(vaResolved.map(x=>x.uei).filter(Boolean))];let gsaUeis=loadGsaUeis();let targets=[...new Set([...gsaUeis,...vaUeis])];let award=await bulkAwards(targets,opts);let result={ok:true,gate:'P1.5K7F_AUTHORITATIVE_VA_FSS_AND_BULK_AWARD_REFRESH',version:'1.0-checkpointed',generatedAt:new Date().toISOString(),vaFss:{source:'VA NAC CCST',sinsDiscovered:va.sinsDiscovered,contracts:va.contracts,ueiResolved:vaUeis.length,ueiResolutionRate:va.contracts?+(vaUeis.length/va.contracts).toFixed(4):0,authoritativeRoster:true},gsa:{uniqueUei:gsaUeis.length},awardTargets:targets.length,award,monthlyProgramProven:false,liveCampaignsMutated:false,nextAction:award.remaining===0?'VALIDATE_COUNTS_AND_PROMOTE_CANONICAL_MASTER':'CONTINUE_K7F_FROM_CHECKPOINT_UNTIL_AWARD_REFRESH_COMPLETE'};fs.writeFileSync(path.join(OUT,'K7F_SUMMARY.json'),JSON.stringify(result,null,2));return result;}module.exports={run};