'use strict';
/* P1.5K3 v1.1 — Bounded federal master discovery + mailbox lifecycle truth. READ ONLY. */
const fs=require('fs'), path=require('path'); require('dotenv').config();
const masterInstantly=require('./MasterInstantlyRevenueReconciliationService');
const ROOT=process.cwd();
const OUT=path.join(ROOT,'DATA','OUTBOUND','INSTANTLY_MASTER_RECONCILIATION','FEDERAL_REVENUE_SEGMENTATION_AND_MAILBOX_AUDIT_K3_LATEST.json');
const TARGET=['pathways2gc.co','pathwaysfederal.com','pathwaysgov.com','pathwaysgovcon.com','pathwaysgsa.com','pathwaystogc.com'];
const PRIMARY='pathways2gc.com', FAMS=['GSA','VA_FSS','SDVOSB','VOSB','WOSB','HUBZONE','8A','SBS_SAM'];
function s(v){return String(v??'').trim()} function low(v){return s(v).toLowerCase()} function key(v){return low(v).replace(/[^a-z0-9]/g,'')}
function parseCsv(t){let a=[],r=[],f='',q=false;for(let i=0;i<t.length;i++){let c=t[i];if(q){if(c==='"'&&t[i+1]==='"'){f+='"';i++}else if(c==='"')q=false;else f+=c}else if(c==='"')q=true;else if(c===','){r.push(f);f=''}else if(c==='\n'){r.push(f);a.push(r);r=[];f=''}else if(c!=='\r')f+=c}if(f||r.length){r.push(f);a.push(r)}if(!a.length)return[];let h=a[0].map((x,i)=>s(x)||`col_${i}`);return a.slice(1).filter(x=>x.some(s)).map(x=>Object.fromEntries(h.map((z,i)=>[z,x[i]??''])))}
function fmap(o){let m={};for(let [k,v] of Object.entries(o||{}))m[key(k)]=v;return m} function first(m,n){for(let x of n)if(s(m[key(x)]))return m[key(x)];return null}
function money(v){if(v==null||v==='')return null;let n=Number(String(v).replace(/[$,]/g,''));return Number.isFinite(n)?n:null} function tier(n){return n==null?'UNKNOWN':n===0?'NO_SALES':n<3e6?'ONE_TO_LT_3M':n<1e7?'THREE_TO_LT_10M':'TEN_M_PLUS'}
const REV=['federal_revenue','federal_sales','federal_award_revenue','award_revenue','total_federal_revenue','prime_award_revenue','prime_revenue','usaspending_revenue','total_obligated_amount','federal_obligated_amount','total_award_amount','award_amount','contract_value','sales'];
const ROOTS=[path.join(ROOT,'DATA','OUTBOUND'),path.join(ROOT,'GOOD_FILES'),path.join(ROOT,'DATASETS')].filter(fs.existsSync);
function walkBounded(d,depth=0,out=[]){if(depth>5||out.length>5000||!fs.existsSync(d))return out;let es=[];try{es=fs.readdirSync(d,{withFileTypes:true})}catch{return out}for(let e of es){if(['node_modules','.git','STATE_SLED','INSTANTLY_MASTER_RECONCILIATION','workforce_results','ARCHIVE','BACKUPS','PRODUCTION_CHECKPOINTS','_LEGACY_BUILDS'].includes(e.name))continue;let p=path.join(d,e.name);if(e.isDirectory())walkBounded(p,depth+1,out);else if(/\.csv$/i.test(e.name))out.push(p)}return out}
function discover(){let files=[...new Set(ROOTS.flatMap(r=>walkBounded(r)))],scored=[];for(let p of files){let b=path.basename(p),score=0;if(/MASTER_DEDUPED_ALL_SEGMENTS/i.test(b))score+=1000;if(/SBS_VALIDATED_EMAIL_TARGETS/i.test(b))score+=500;if(/SBS_FILTERED_TARGETS_OK_ONLY_MILLIONVERIFIER/i.test(b))score+=400;if(/GSA_|VA_|SAM_|SDVOSB|VOSB|WOSB|HUB|8A|SEGMENT/i.test(b))score+=100;let size=0;try{size=fs.statSync(p).size}catch{};if(size>500000&&size<150000000)score+=25;if(score)scored.push({file:p,score,size})}return scored.sort((a,b)=>b.score-a.score||b.size-a.size).slice(0,100)}
function id(r){let m=fmap(r),u=low(first(m,['uei','unique_entity_id','uei_sam']));if(u)return'UEI:'+u;let c=low(first(m,['company_id']));if(c)return'CID:'+c;let n=low(first(m,['legal_name','company','company_name','business_name','entity_name']));return n?'NAME:'+n:null}
function fams(r,file){let x=(Object.values(r).join(' | ')+' '+file).toUpperCase(),o=new Set();if(/\bGSA\b|MULTIPLE AWARD SCHEDULE|\bMAS\b/.test(x))o.add('GSA');if(/\bVA\b|\bFSS\b|VETERANS AFFAIRS|FEDERAL SUPPLY SCHEDULE/.test(x))o.add('VA_FSS');if(/SDVOSB|SERVICE[- ]DISABLED VETERAN/.test(x))o.add('SDVOSB');if(/VOSB|VETERAN[- ]OWNED/.test(x))o.add('VOSB');if(/WOSB|WOMEN[- ]OWNED/.test(x))o.add('WOSB');if(/HUB ?ZONE/.test(x))o.add('HUBZONE');if(/8\(A\)|\b8A\b/.test(x))o.add('8A');if(/\bSBS\b|\bSAM\b|SAM\.GOV|SMALL BUSINESS/.test(x))o.add('SBS_SAM');return[...o]}
function load(){let candidates=discover(),chosen=[],rows=[];for(let c of candidates){try{if(c.size>150000000)continue;let p=parseCsv(fs.readFileSync(c.file,'utf8'));let usable=[];for(let r of p){let i=id(r),f=fams(r,path.basename(c.file));if(i&&f.length)usable.push({r,i,f})}if(usable.length){chosen.push({...c,parsedRows:p.length,usableRows:usable.length});for(let u of usable){let m=fmap(u.r),rv=money(first(m,REV));rows.push({id:u.i,families:u.f,revenue:rv,source:c.file})}if(/MASTER_DEDUPED_ALL_SEGMENTS/i.test(c.file))break}}catch{}}return{candidates,chosen,rows}}
function segment(rows){let by=new Map();for(let r of rows){let x=by.get(r.id)||{f:new Set(),v:[]};r.families.forEach(z=>x.f.add(z));if(r.revenue!=null)x.v.push(r.revenue);by.set(r.id,x)}let cells={};FAMS.forEach(f=>cells[f]={NO_SALES:0,ONE_TO_LT_3M:0,THREE_TO_LT_10M:0,TEN_M_PLUS:0,UNKNOWN:0});let unknown=0,conflict=0;for(let x of by.values()){let vals=[...new Set(x.v.map(Number))];if(vals.length>1)conflict++;let t=tier(vals.length?Math.max(...vals):null);if(t==='UNKNOWN')unknown++;for(let f of x.f)cells[f][t]++}return{uniqueCompanies:by.size,cells,unknownRevenueCompanies:unknown,conflictingRevenueCompanies:conflict}}
async function mailboxes(){let p=path.join(ROOT,'DATA','OUTBOUND','INBOX_STATUS_MASTER.csv'),rows=fs.existsSync(p)?parseCsv(fs.readFileSync(p,'utf8')):[],live=[];try{live=(await masterInstantly.run()).campaigns||[]}catch{}let liveEmails=new Set();for(let c of live)for(let raw of [...(c.senderEmails||[]),...(c.senders||[])]){let e=low(typeof raw==='string'?raw:(raw?.email||raw?.email_address));if(e.includes('@'))liveEmails.add(e)}let obs=new Map();for(let r of rows){let m=fmap(r),e=low(first(m,['email','email_address','sender_email','account','mailbox','inbox']));if(!e.includes('@'))continue;let st=s(first(m,['status','account_status','health','state'])||'UNKNOWN'),lifecycle=liveEmails.has(e)?'ACTIVE_CONNECTED':/planned/i.test(st)?'PLANNED_NOT_CONFIRMED_CREATED':/created|workspace|connected/i.test(st)?'CREATED_NOT_CONFIRMED_CONNECTED':'OBSERVED_UNVERIFIED';obs.set(e,{email:e,status:st,source:liveEmails.has(e)?'MASTER+LIVE_CAMPAIGN':'INBOX_STATUS_MASTER',lifecycle})}for(let e of liveEmails)if(!obs.has(e))obs.set(e,{email:e,status:'LIVE_CAMPAIGN',source:'LIVE_CAMPAIGN',lifecycle:'ACTIVE_CONNECTED'});let domains=TARGET.map(domain=>{let all=[...obs.values()].filter(x=>x.email.endsWith('@'+domain)),active=all.filter(x=>x.lifecycle==='ACTIVE_CONNECTED'),planned=all.filter(x=>x.lifecycle==='PLANNED_NOT_CONFIRMED_CREATED'),created=all.filter(x=>x.lifecycle==='CREATED_NOT_CONFIRMED_CONNECTED');return{domain,target:5,activeConnected:active.length,createdNotConfirmedConnected:created.length,plannedNotConfirmedCreated:planned.length,missingOrUnconfirmed:Math.max(0,5-active.length),accounts:all}});return{masterFile:p,domains,confirmedActiveConnected:domains.reduce((n,d)=>n+d.activeConnected,0),targetMailboxes:30,remainingToConfirmOrProvision:domains.reduce((n,d)=>n+d.missingOrUnconfirmed,0),protectedPrimary:[...obs.values()].filter(x=>x.email.endsWith('@'+PRIMARY))}}
async function run(){let src=load(),seg=segment(src.rows),mb=await mailboxes();let r={ok:true,gate:'P1.5K3_FEDERAL_MASTER_DISCOVERY_AND_MAILBOX_LIFECYCLE_TRUTH',version:'1.1-bounded-memory',generatedAt:new Date().toISOString(),revenueTierPolicy:{NO_SALES:'$0',ONE_TO_LT_3M:'$1 to <$3M',THREE_TO_LT_10M:'$3M to <$10M',TEN_M_PLUS:'$10M+',UNKNOWN:'missing trustworthy award revenue'},federalMasterDiscovery:{candidateFiles:src.candidates,chosenFiles:src.chosen,candidateRowsUsed:src.rows.length,...seg},mailboxLifecycle:mb,decisions:{segmentation:seg.uniqueCompanies?'REVIEW_UNKNOWN_REVENUE_THEN_GOVERNED_RESEGMENTATION':'FEDERAL_MASTER_STILL_NOT_FOUND',mailboxes:'CONFIRM_PLANNED_AND_CREATED_STATES_BEFORE_PROVISIONING'},safety:{readOnly:true,mutateCampaigns:false,createMailboxes:false,sendEmails:false,protectedPrimaryDomainExcluded:true},outputFile:OUT};fs.mkdirSync(path.dirname(OUT),{recursive:true});fs.writeFileSync(OUT,JSON.stringify(r,null,2));return r}module.exports={run};if(require.main===module)run().then(r=>console.dir(r,{depth:10})).catch(e=>{console.error(e);process.exit(1)});