'use strict';
const fs=require('fs');const path=require('path');
const AwardHistoryTruthService=require('./orion/AwardHistoryTruthService');
const ROOT=process.cwd();
const GSA='D:\\P2GC_Intelligence\\MILES_ENTERPRISE\\DATA\\staging\\government_data\\gsa_holder_snapshot\\GSA-HOLDERS-2026-07-2026-07-28T02-41-25-700Z\\gsa_elibrary_schedule_MAS.csv';
const OUT=path.join(ROOT,'DATA','staging','government_data','K7E_MISSING_SOURCE_REFRESH');
const VA_CANDIDATES=[
'D:\\P2GC_Intelligence\\ORION_CORE\\Good Files to use\\VA_CLEAN.csv',
'D:\\P2GC_Intelligence\\CONSOLIDATION OF LEADS\\CLEAN_GSA_VA\\VA_CLEAN.csv',
'D:\\P2GC_Intelligence\\ORION\\Outbound_Segments\\VA_No_Sales.csv'
];
function parse(line){let a=[],x='',q=false;for(let i=0;i<line.length;i++){let c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){x+='"';i++;}else q=!q;}else if(c===','&&!q){a.push(x);x='';}else x+=c;}a.push(x);return a;}
function rows(p,limit=0){let t=fs.readFileSync(p,'utf8').split(/\r?\n/).filter(Boolean);let h=parse(t[0]);let n=limit?Math.min(t.length,limit+1):t.length;return t.slice(1,n).map(l=>{let v=parse(l),o={};h.forEach((k,i)=>o[k]=v[i]??'');return o;});}
function pick(o,ks){for(const k of ks){if(o[k]!==undefined&&String(o[k]).trim())return String(o[k]).trim();}return '';}
function csvEsc(v){let s=String(v??'');return /[",\n\r]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s;}
function writeCsv(p,arr,cols){fs.mkdirSync(path.dirname(p),{recursive:true});let out=[cols.join(',')];for(const r of arr)out.push(cols.map(c=>csvEsc(r[c])).join(','));fs.writeFileSync(p,out.join('\n'));}
function currentVaSeed(){for(const p of VA_CANDIDATES)if(fs.existsSync(p))return p;return null;}
async function run(opts={}){fs.mkdirSync(OUT,{recursive:true});if(!fs.existsSync(GSA))throw new Error('Fresh GSA snapshot missing');let gsa=rows(GSA);let gu=new Set(gsa.map(r=>pick(r,['SAM UEI','UEI','uei'])).filter(Boolean));let vaSeed=currentVaSeed();let va=[];if(vaSeed)va=rows(vaSeed).map(r=>({uei:pick(r,['uei','UEI','SAM UEI']),legal_name:pick(r,['legal_name','company','Vendor']),vehicle:'VA/FSS',source_file:vaSeed})).filter(r=>r.uei);let vaUnique=[...new Map(va.map(r=>[r.uei,r])).values()];let awardTargets=[...new Set([...gu,...vaUnique.map(r=>r.uei)])];let sampleLimit=Math.max(1,Math.min(Number(opts.sampleLimit||process.env.K7E_AWARD_SAMPLE_LIMIT||25),250));let svc=new AwardHistoryTruthService();let awards=[];for(let i=0;i<Math.min(awardTargets.length,sampleLimit);i++){let u=awardTargets[i];try{let a=await svc.auditByUei(u,{pageSize:100,maxPages:10});awards.push({uei:u,ok:a.ok,status:a.status||'',federalRevenue:a.federalRevenue||0,awardCount:a.awardCount||0,primeAwardedRevenue:a.primeAwardedRevenue||0,subcontractedRevenue:a.subcontractedRevenue||0,generatedAt:a.generatedAt||new Date().toISOString()});}catch(e){awards.push({uei:u,ok:false,status:'ERROR:'+e.message,federalRevenue:0,awardCount:0,primeAwardedRevenue:0,subcontractedRevenue:0,generatedAt:new Date().toISOString()});}}
let vaOut=path.join(OUT,'VA_FSS_RECOVERED_SEED.csv');writeCsv(vaOut,vaUnique,['uei','legal_name','vehicle','source_file']);let awOut=path.join(OUT,'AWARD_TRUTH_SAMPLE.csv');writeCsv(awOut,awards,['uei','ok','status','federalRevenue','awardCount','primeAwardedRevenue','subcontractedRevenue','generatedAt']);let result={ok:true,gate:'P1.5K7E_MISSING_SOURCE_REFRESH',version:'1.0',generatedAt:new Date().toISOString(),gsa:{path:GSA,uniqueUei:gu.size},vaFss:{seedPath:vaSeed,uniqueUei:vaUnique.length,authoritativeFresh:false,reason:'NO_FRESH_AUTHORITATIVE_VA_FSS_SOURCE_FOUND; THIS IS RECOVERY SEED ONLY'},award:{targets:awardTargets.length,sampled:awards.length,successful:awards.filter(x=>x.ok).length,output:awOut,source:'USAspending.gov via AwardHistoryTruthService'},monthlyProgramProven:false,liveCampaignsMutated:false,nextAction:'VERIFY_K7E_AWARD_API_RESULTS; THEN EXECUTE/FETCH AUTHORITATIVE VA_FSS ROSTER AND SCALE BULK AWARD REFRESH BEFORE CANONICAL_REBUILD'};fs.writeFileSync(path.join(OUT,'K7E_RESULT.json'),JSON.stringify(result,null,2));return result;}module.exports={run};