'use strict';
/* P1.5K4 — discovered federal-source truth + strict mailbox lifecycle. READ ONLY. */
const fs=require('fs'),path=require('path');require('dotenv').config();
const masterInstantly=require('./MasterInstantlyRevenueReconciliationService');
const ROOT=process.cwd(), OUT=path.join(ROOT,'DATA','OUTBOUND','INSTANTLY_MASTER_RECONCILIATION','FEDERAL_REVENUE_SEGMENTATION_AND_MAILBOX_AUDIT_K4_LATEST.json');
const TARGET=['pathways2gc.co','pathwaysfederal.com','pathwaysgov.com','pathwaysgovcon.com','pathwaysgsa.com','pathwaystogc.com']; const PRIMARY='pathways2gc.com';
const FAMS=['GSA','VA_FSS','SDVOSB','VOSB','WOSB','HUBZONE','8A','SBS_SAM'];
const REV=['federal_revenue','federal_sales','federal_award_revenue','award_revenue','total_federal_revenue','prime_award_revenue','prime_revenue','usaspending_revenue','total_obligated_amount','federal_obligated_amount','total_award_amount','award_amount','contract_value','sales','awarded_amount','total_awards'];
const IDS=['uei','unique_entity_id','uei_sam','company_id','legal_name','company','company_name','business_name','entity_name'];
function s(v){return String(v??'').trim()} function low(v){return s(v).toLowerCase()} function k(v){return low(v).replace(/[^a-z0-9]/g,'')}
function csvLine(line){let a=[],f='',q=false;for(let i=0;i<line.length;i++){let c=line[i];if(q){if(c==='"'&&line[i+1]==='"'){f+='"';i++}else if(c==='"')q=false;else f+=c}else if(c==='"')q=true;else if(c===','){a.push(f);f=''}else f+=c}a.push(f);return a}
function parseCsv(txt){let lines=txt.split(/\r?\n/).filter(Boolean);if(!lines.length)return[];let h=csvLine(lines[0]);return lines.slice(1).map(line=>{let v=csvLine(line),o={};h.forEach((x,i)=>o[x]=v[i]??'');return o})}
function fmap(o){let m={};for(let [a,b] of Object.entries(o||{}))m[k(a)]=b;return m} function first(m,n){for(let x of n)if(s(m[k(x)]))return m[k(x)];return null}
function money(v){if(v==null||v==='')return null;let n=Number(String(v).replace(/[$,]/g,''));return Number.isFinite(n)?n:null} function tier(n){return n==null?'UNKNOWN':n===0?'NO_SALES':n<3e6?'ONE_TO_LT_3M':n<1e7?'THREE_TO_LT_10M':'TEN_M_PLUS'}
function identity(r){let m=fmap(r),u=low(first(m,['uei','unique_entity_id','uei_sam']));if(u)return'UEI:'+u;let c=low(first(m,['company_id']));if(c)return'CID:'+c;let n=low(first(m,['legal_name','company','company_name','business_name','entity_name']));return n?'NAME:'+n:null}
function fams(r,file){let x=(Object.values(r).join(' | ')+' '+file).toUpperCase(),o=new Set();if(/\bGSA\b|MULTIPLE AWARD SCHEDULE|\bMAS\b/.test(x))o.add('GSA');if(/\bVA\b|\bFSS\b|VETERANS AFFAIRS|FEDERAL SUPPLY SCHEDULE/.test(x))o.add('VA_FSS');if(/SDVOSB|SERVICE[- ]DISABLED VETERAN/.test(x))o.add('SDVOSB');if(/VOSB|VETERAN[- ]OWNED/.test(x))o.add('VOSB');if(/WOSB|WOMEN[- ]OWNED/.test(x))o.add('WOSB');if(/HUB ?ZONE/.test(x))o.add('HUBZONE');if(/8\(A\)|\b8A\b/.test(x))o.add('8A');if(/\bSBS\b|\bSAM\b|SAM\.GOV|SMALL BUSINESS/.test(x))o.add('SBS_SAM');return[...o]}
function discoveryPaths(){let p=path.join(ROOT,'SEGMENT_FILE_DISCOVERY.csv');if(!fs.existsSync(p))return[];let rows=parseCsv(fs.readFileSync(p,'utf8'));return rows.map(r=>s(r.FullName||r.fullname||Object.values(r)[0])).filter(Boolean)}
function inspectHeader(p){try{let fd=fs.openSync(p,'r'),buf=Buffer.alloc(65536),n=fs.readSync(fd,buf,0,buf.length,0);fs.closeSync(fd);let firstLine=buf.slice(0,n).toString('utf8').split(/\r?\n/)[0];return csvLine(firstLine)}catch{return[]}}
function scorePath(p){let b=path.basename(p).toUpperCase(),score=0;if(/_ARCHIVE_OLD|BACKUP|OLD_VERSION|CHECKPOINT/i.test(p))return-999;if(/STATE_SLED|STATE_SLED_WAVE/i.test(p))return-999;if(/USA_SEGMENTED_COMPANIES/.test(b))score+=120;if(/SAM_FINAL_SEGMENTED/.test(b))score+=110;if(/P2GC_MASTER_WITH_SEGMENTS/.test(b))score+=100;if(/P2GC_EVAN_SEGMENTED_MASTER_V2/.test(b))score+=95;if(/P2GC_FINAL_SEGMENTED/.test(b))score+=90;if(/P2GC_NON_HOLDERS_SEGMENTED/.test(b))score+=80;if(/SBS_SEGMENTED_TARGETS\.CSV/.test(b))score+=75;if(/SEGMENT|MASTER|GSA|SAM|SBS|USA/.test(b))score+=15;return score}
function chooseSources(){let arr=[];for(let p of discoveryPaths()){if(!/\.csv$/i.test(p)||!fs.existsSync(p))continue;let st;try{st=fs.statSync(p)}catch{continue}if(st.size>250*1024*1024)continue;let headers=inspectHeader(p),hm=headers.map(k),hasId=IDS.some(x=>hm.includes(k(x))),hasRev=REV.some(x=>hm.includes(k(x))),hasSeg=hm.some(x=>/segment|vehicle|certification|socioeconomic/.test(x));let score=scorePath(p)+(hasId?25:0)+(hasRev?50:0)+(hasSeg?25:0);if(score>0)arr.push({file:p,size:st.size,score,hasId,hasRevenueField:hasRev,hasSegmentField:hasSeg,headers:headers.slice(0,80)})}return arr.sort((a,b)=>b.score-a.score||b.size-a.size)}
function loadFederal(){let candidates=chooseSources(),selected=candidates.filter(x=>x.hasId&&x.hasSegmentField).slice(0,3),rows=[];for(let c of selected){try{let txt=fs.readFileSync(c.file,'utf8'),parsed=parseCsv(txt);for(let r of parsed){let id=identity(r),f=fams(r,path.basename(c.file));if(!id||!f.length)continue;let m=fmap(r),rv=money(first(m,REV));rows.push({id,families:f,revenue:rv,source:c.file})}c.parsedRows=parsed.length;c.usableRows=rows.filter(x=>x.source===c.file).length}catch(e){c.error=e.message}}return{candidates:candidates.slice(0,20),selected,rows}}
function segment(rows){let by=new Map();for(let r of rows){let x=by.get(r.id)||{f:new Set(),v:[]};r.families.forEach(z=>x.f.add(z));if(r.revenue!=null)x.v.push(r.revenue);by.set(r.id,x)}let cells={};FAMS.forEach(f=>cells[f]={NO_SALES:0,ONE_TO_LT_3M:0,THREE_TO_LT_10M:0,TEN_M_PLUS:0,UNKNOWN:0});let unknown=0,conflict=0;for(let x of by.values()){let vals=[...new Set(x.v.map(Number))];if(vals.length>1)conflict++;let t=tier(vals.length?Math.max(...vals):null);if(t==='UNKNOWN')unknown++;for(let f of x.f)cells[f][t]++}return{uniqueCompanies:by.size,cells,unknownRevenueCompanies:unknown,conflictingRevenueCompanies:conflict}}
async function mailboxes(){let p=path.join(ROOT,'DATA','OUTBOUND','INBOX_STATUS_MASTER.csv'),rows=fs.existsSync(p)?parseCsv(fs.readFileSync(p,'utf8')):[],live=[];try{live=(await masterInstantly.run()).campaigns||[]}catch{}let liveEmails=new Set();for(let c of live)for(let raw of [...(c.senderEmails||[]),...(c.senders||[])]){let e=low(typeof raw==='string'?raw:(raw?.email||raw?.email_address));if(e.includes('@'))liveEmails.add(e)}let obs=new Map();for(let r of rows){let m=fmap(r),e=low(first(m,['email','email_address','sender_email','account','mailbox','inbox']));if(!e.includes('@'))continue;let st=s(first(m,['status','account_status','health','state'])||'UNKNOWN');let lifecycle=liveEmails.has(e)?'ACTIVE_CONNECTED':/planned/i.test(st)?'PLANNED_NOT_CONFIRMED_CREATED':/created|workspace/i.test(st)?'CREATED_NOT_CONFIRMED_CONNECTED':/active|connected/i.test(st)?'ACTIVE_RECORDED_NOT_LIVE_OBSERVED':'OBSERVED_UNVERIFIED';obs.set(e,{email:e,status:st,source:liveEmails.has(e)?'MASTER+LIVE_CAMPAIGN':'INBOX_STATUS_MASTER',lifecycle})}for(let e of liveEmails)if(!obs.has(e))obs.set(e,{email:e,status:'LIVE_CAMPAIGN',source:'LIVE_CAMPAIGN',lifecycle:'ACTIVE_CONNECTED'});let domains=TARGET.map(domain=>{let all=[...obs.values()].filter(x=>x.email.endsWith('@'+domain)),active=all.filter(x=>x.lifecycle==='ACTIVE_CONNECTED'),created=all.filter(x=>x.lifecycle==='CREATED_NOT_CONFIRMED_CONNECTED'),planned=all.filter(x=>x.lifecycle==='PLANNED_NOT_CONFIRMED_CREATED');return{domain,target:5,activeConnected:active.length,createdNotConfirmedConnected:created.length,plannedNotConfirmedCreated:planned.length,confirmedGapToFive:Math.max(0,5-active.length),accounts:all}});return{masterFile:p,domains,confirmedActiveConnected:domains.reduce((n,d)=>n+d.activeConnected,0),targetMailboxes:30,confirmedGapToThirty:30-domains.reduce((n,d)=>n+d.activeConnected,0),protectedPrimary:[...obs.values()].filter(x=>x.email.endsWith('@'+PRIMARY))}}
async function run(){let src=loadFederal(),seg=segment(src.rows),mb=await mailboxes();let enough=seg.uniqueCompanies>0&&Object.values(seg.cells).some(c=>c.NO_SALES+c.ONE_TO_LT_3M+c.THREE_TO_LT_10M+c.TEN_M_PLUS>0);let r={ok:true,gate:'P1.5K4_DISCOVERED_FEDERAL_SOURCE_AND_STRICT_MAILBOX_TRUTH',version:'1.0-read-only',generatedAt:new Date().toISOString(),revenueTierPolicy:{NO_SALES:'$0',ONE_TO_LT_3M:'$1 to <$3M',THREE_TO_LT_10M:'$3M to <$10M',TEN_M_PLUS:'$10M+',UNKNOWN:'missing trustworthy award revenue'},federalSourceTruth:{candidateFiles:src.candidates,selectedFiles:src.selected,candidateRowsUsed:src.rows.length,...seg,authoritativeEnoughToResegment:enough&&seg.unknownRevenueCompanies<seg.uniqueCompanies},mailboxTruth:mb,decisions:{segmentation:enough?'USE_SELECTED_CURRENT_FEDERAL_SOURCES; ENRICH_ONLY_UNKNOWN_REVENUE BEFORE FINAL MUTATION':'NEED_AWARD_REVENUE_JOIN_SOURCE',mailboxes:'CREATE_NOTHING UNTIL PLANNED ACCOUNTS ARE CONFIRMED IN GOOGLE WORKSPACE; CONNECT ACTIVE/CREATED ACCOUNTS TO INSTANTLY'},safety:{readOnly:true,mutateCampaigns:false,createMailboxes:false,connectMailboxes:false,sendEmails:false,protectedPrimaryExcluded:true},outputFile:OUT};fs.mkdirSync(path.dirname(OUT),{recursive:true});fs.writeFileSync(OUT,JSON.stringify(r,null,2));return r}module.exports={run};if(require.main===module)run().then(r=>console.dir(r,{depth:10})).catch(e=>{console.error(e);process.exit(1)});