'use strict';
const fs=require('fs');
const path=require('path');
const OUT=path.join(process.cwd(),'DATA','OUTBOUND','FEDERAL_ORION_BASELINE_K7L');
const MASTER='D:\\P2GC_Intelligence\\ORION\\MASTER_COMPANY_INDEX\\MASTER_COMPANY_INDEX.csv';
const REVENUE='D:\\P2GC_Intelligence\\ORION_CORE\\Opportunity_Engine\\Input\\contract_award_summary.csv';
const GSA='D:\\P2GC_Intelligence\\MILES_ENTERPRISE\\DATA\\staging\\government_data\\gsa_holder_snapshot\\GSA-HOLDERS-2026-07-2026-07-28T02-41-25-700Z\\gsa_elibrary_schedule_MAS.csv';
const VA_CP=path.join(process.cwd(),'DATA','staging','government_data','K7F_VA_FSS_BULK_AWARD_REFRESH','VA_FSS_UEI_RESOLUTION_CHECKPOINT_V15.json');
function csvLine(s){let a=[],x='',q=false;for(let i=0;i<s.length;i++){const c=s[i];if(c==='"'){if(q&&s[i+1]==='"'){x+='"';i++;}else q=!q;}else if(c===','&&!q){a.push(x);x='';}else x+=c;}a.push(x);return a;}
function norm(s){return String(s||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');}
function num(v){const n=Number(String(v??'').replace(/[$,]/g,'').trim());return Number.isFinite(n)?n:null;}
function tier(r){if(r===null||r===undefined)return'UNKNOWN';if(r<=0)return'NO_SALES';if(r<3000000)return'1_TO_LT3M';if(r<10000000)return'3_TO_LT10M';return'10M_PLUS';}
function esc(v){v=String(v??'');return /[",\n]/.test(v)?'"'+v.replace(/"/g,'""')+'"':v;}
function readCsv(p){if(!fs.existsSync(p))throw new Error('FILE_NOT_FOUND '+p);const ls=fs.readFileSync(p,'utf8').replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);const h=csvLine(ls[0]);const hn=h.map(norm);return{headers:h,hn,rows:ls.slice(1).map(l=>csvLine(l))};}
function idx(hn,names){for(const n of names){const i=hn.indexOf(norm(n));if(i>=0)return i;}return-1;}
function loadRevenue(){const d=readCsv(REVENUE),ui=idx(d.hn,['recipient_uei','uei']),ri=idx(d.hn,['Federal_Total_Revenue','federal_total_revenue']);if(ui<0||ri<0)throw new Error('REVENUE_COLUMNS_MISSING');const m=new Map();let pos=0,zero=0;for(const r of d.rows){const u=String(r[ui]||'').trim().toUpperCase();if(!u)continue;const n=num(r[ri]);if(n===null)continue;m.set(u,n);if(n>0)pos++;else zero++;}if(pos<10000)throw new Error('REVENUE_SOURCE_TOO_WEAK '+pos);return{map:m,rows:d.rows.length,positive:pos,zero};}
function loadGsa(){const d=readCsv(GSA),ui=idx(d.hn,['SAM UEI','uei']);const s=new Set();for(const r of d.rows){const u=String(r[ui]||'').trim().toUpperCase();if(u)s.add(u);}return s;}
function loadVa(){if(!fs.existsSync(VA_CP))return new Set();const j=JSON.parse(fs.readFileSync(VA_CP,'utf8'));return new Set(Object.values(j.rows||{}).map(x=>String(x.uei||'').trim().toUpperCase()).filter(Boolean));}
function markerText(parts){return parts.filter(Boolean).join(' | ').toUpperCase().replace(/[_-]+/g,' ').replace(/\s+/g,' ').trim();}
function classifyMaster(gsa,va){const d=readCsv(MASTER);const ui=idx(d.hn,['uei']);if(ui<0)throw new Error('MASTER_UEI_MISSING');const bi=idx(d.hn,['business_type']),si=idx(d.hn,['set_aside_flags']),sami=idx(d.hn,['sam_status']),src=idx(d.hn,['source_layers']);const fam={GSA:new Set(gsa),VA_FSS:new Set(va),SDVOSB:new Set(),VOSB:new Set(),WOSB:new Set(),HUBZONE:new Set(),EIGHT_A:new Set(),SAM:new Set(),SBS:new Set()};const evidence={rows:d.rows.length,headers:d.headers};for(const r of d.rows){const u=String(r[ui]||'').trim().toUpperCase();if(!u)continue;const b=bi>=0?r[bi]:'',s=si>=0?r[si]:'',sam=sami>=0?r[sami]:'',sl=src>=0?r[src]:'';const text=markerText([b,s,sl]);if(/\bSDVOSB\b|SERVICE DISABLED VETERAN/.test(text))fam.SDVOSB.add(u);if(/\bVOSB\b|VETERAN OWNED/.test(text))fam.VOSB.add(u);if(/\bWOSB\b|WOMEN OWNED|WOMAN OWNED/.test(text))fam.WOSB.add(u);if(/\bHUBZONE\b|HUB ZONE/.test(text))fam.HUBZONE.add(u);if(/\b8\s*\(?A\)?\b|EIGHT\s*\(?A\)?/.test(text))fam.EIGHT_A.add(u);const samText=String(sam||'').trim();if(samText&&!/inactive|expired|none|null|unknown|not active/i.test(samText))fam.SAM.add(u);if(/\bSBS\b|\bDSBS\b|DYNAMIC SMALL BUSINESS SEARCH|SMALL BUSINESS SEARCH/.test(text))fam.SBS.add(u);}return{families:fam,evidence};}
function summarize(label,set,rev){const c={family:label,NO_SALES:0,'1_TO_LT3M':0,'3_TO_LT10M':0,'10M_PLUS':0,UNKNOWN:0,total:set.size,matchedRevenueTruth:0,matchRate:0};for(const u of set){const has=rev.has(u);if(has)c.matchedRevenueTruth++;c[tier(has?rev.get(u):null)]++;}c.matchRate=c.total?c.matchedRevenueTruth/c.total:0;return c;}
function writeFamily(label,set,rev){const rows=['uei,revenue,tier,source_status'];for(const u of set){const has=rev.has(u),r=has?rev.get(u):null;rows.push([u,r??'',tier(r),'ORION_BASELINE_NOT_FULLY_CURRENT'].map(esc).join(','));}fs.writeFileSync(path.join(OUT,`${label}_MASTER.csv`),rows.join('\n'));}
function overlaps(fam){const names=Object.keys(fam),out={};for(let i=0;i<names.length;i++)for(let j=i+1;j<names.length;j++){let n=0;const a=fam[names[i]],b=fam[names[j]];const small=a.size<=b.size?a:b,large=a.size<=b.size?b:a;for(const u of small)if(large.has(u))n++;if(n)out[`${names[i]}__${names[j]}`]=n;}return out;}
async function run(){fs.mkdirSync(OUT,{recursive:true});const rev=loadRevenue(),gsa=loadGsa(),va=loadVa(),m=classifyMaster(gsa,va),summaries={};for(const[k,s]of Object.entries(m.families)){summaries[k]=summarize(k,s,rev.map);writeFamily(k,s,rev.map);}if(summaries.GSA.total!==gsa.size)throw new Error(`GSA_BOUNDARY_VIOLATION ${summaries.GSA.total} != ${gsa.size}`);if(summaries.VA_FSS.total!==va.size)throw new Error(`VA_BOUNDARY_VIOLATION ${summaries.VA_FSS.total} != ${va.size}`);const result={ok:true,gate:'P1.5K7L_FULL_ORION_BASELINE_FEDERAL_SEGMENTATION',version:'1.1-fixed-authoritative-boundaries',generatedAt:new Date().toISOString(),dataPolicy:'TEMPORARY_BASELINE; ORION CONTRACT AWARD SUMMARY FOR REVENUE; CURRENT GSA + K7F VA ROSTERS; FEB_2026_FORWARD_CATCHUP_DEFERRED',sourceTruth:{revenue:{path:REVENUE,rows:rev.rows,positive:rev.positive,zero:rev.zero,status:'VALIDATED_ORION_BASELINE_NOT_FULLY_CURRENT'},master:{path:MASTER,rows:m.evidence.rows,status:'ORION_FAMILY_MEMBERSHIP_BASELINE'},gsa:{path:GSA,uniqueUei:gsa.size,status:'FRESH_ROSTER_AUTHORITATIVE_BOUNDARY'},vaFss:{path:VA_CP,uniqueUei:va.size,status:'AUTHORITATIVE_ROSTER_PARTIAL_UEI_RESOLUTION_BOUNDARY'}},familyRules:{GSA:'membership ONLY from fresh GSA roster; ORION has_gsa cannot expand it',VA_FSS:'membership ONLY from K7F resolved VA roster; ORION has_va cannot expand it',SDVOSB:'normalized business_type/set_aside_flags/source_layers contains SDVOSB or service disabled veteran',VOSB:'normalized markers contain VOSB or veteran owned',WOSB:'normalized markers contain WOSB / women owned / woman owned',HUBZONE:'normalized markers contain HUBZONE / HUB ZONE',EIGHT_A:'normalized markers contain 8(a)/8a/eight(a)',SAM:'sam_status present and not inactive/expired/unknown/not active',SBS:'normalized markers contain SBS/DSBS/Dynamic Small Business Search'},segments:summaries,overlapCounts:overlaps(m.families),outputDir:OUT,liveCampaignsMutated:false,authoritativeEnoughToResegment:false,nextAction:'VALIDATE_NONZERO_CERT_SAM_SBS_COUNTS_AND_OVERLAPS; THEN BUILD_DEDUPED_PRIORITY_ROUTING_PLAN_BEFORE_LIVE_INSTANTLY_MUTATION'};fs.writeFileSync(path.join(OUT,'K7L_SUMMARY.json'),JSON.stringify(result,null,2));return result;}module.exports={run};