'use strict';
const fs=require('fs');
const path=require('path');
const AwardHistoryTruthService=require('./orion/AwardHistoryTruthService');
const OUT=path.join(process.cwd(),'DATA','staging','government_data','K7F_VA_FSS_BULK_AWARD_REFRESH');
const VA_VENDOR_LIST='https://www.vendorportal.ecms.va.gov/NAC/Vendor/List';
function sleep(ms){return new Promise(r=>setTimeout(r,ms));}
function clean(s){return String(s||'').replace(/&amp;/g,'&').replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();}
function norm(s){return clean(s).toUpperCase().replace(/\b(INCORPORATED|INC|CORPORATION|CORP|COMPANY|CO|LIMITED|LTD|LLC|L L C|LP|L P|PLLC|PC)\b/g,' ').replace(/[^A-Z0-9]+/g,' ').replace(/\s+/g,' ').trim();}
function tokens(s){return new Set(norm(s).split(' ').filter(x=>x.length>1));}
function similarity(a,b){const A=tokens(a),B=tokens(b);if(!A.size||!B.size)return 0;let inter=0;for(const x of A)if(B.has(x))inter++;let union=new Set([...A,...B]).size;return union?inter/union:0;}
function csv(v){v=String(v??'');return /[",\n]/.test(v)?'"'+v.replace(/"/g,'""')+'"':v;}
function parseCsvLine(s){let a=[],x='',q=false;for(let i=0;i<s.length;i++){let c=s[i];if(c==='"'){if(q&&s[i+1]==='"'){x+='"';i++;}else q=!q;}else if(c===','&&!q){a.push(x);x='';}else x+=c;}a.push(x);return a;}
async function fetchText(url){let r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 MILES-P2GC/1.5'}});if(!r.ok)throw new Error(`${r.status} ${r.statusText} ${url}`);return r.text();}
function findConfirmedGsaSnapshot(){const rel=path.join('MILES_ENTERPRISE','DATA','staging','government_data','gsa_holder_snapshot','GSA-HOLDERS-2026-07-2026-07-28T02-41-25-700Z','gsa_elibrary_schedule_MAS.csv');const candidates=[path.join('D:\\P2GC_Intelligence',rel),path.join('C:\\P2GC_Intelligence',rel),path.join(process.cwd(),'DATA','staging','government_data','gsa_holder_snapshot','GSA-HOLDERS-2026-07-2026-07-28T02-41-25-700Z','gsa_elibrary_schedule_MAS.csv')];for(const p of candidates){if(fs.existsSync(p))return p;}return null;}
function loadGsaUeis(){let snapshot=findConfirmedGsaSnapshot();if(!snapshot)throw new Error('CONFIRMED_GSA_SNAPSHOT_MISSING');let ls=fs.readFileSync(snapshot,'utf8').split(/\r?\n/).filter(Boolean);let h=parseCsvLine(ls[0]).map(x=>x.trim());let i=h.findIndex(x=>/^SAM UEI$/i.test(x));if(i<0)throw new Error('CONFIRMED_GSA_SNAPSHOT_SAM_UEI_COLUMN_MISSING');let s=new Set();for(let n=1;n<ls.length;n++){let u=String(parseCsvLine(ls[n])[i]||'').trim().toUpperCase();if(u)s.add(u);}if(s.size<10000)throw new Error(`CONFIRMED_GSA_SNAPSHOT_COUNT_TOO_LOW:${s.size}`);return {ueis:[...s],snapshot};}
function extractVaSinOptions(html){let sins=new Set();for(const m of html.matchAll(/<option[^>]*value=["']([^"']+)["'][^>]*>([\s\S]*?)<\/option>/gi)){let v=clean(m[1]);if(!v||/^(select|all|0|-1)$/i.test(v))continue;if(/^[A-Z0-9][A-Z0-9-]{1,20}$/i.test(v)&&(/[A-Z]/i.test(v)||/-/.test(v)))sins.add(v);}return [...sins];}
function parseVendorRows(html,sin){let out=[];for(const m of html.matchAll(/<tr[^>]*>([\s\S]*?)<\/tr>/gi)){let cells=[...m[1].matchAll(/<t[dh][^>]*>([\s\S]*?)<\/t[dh]>/gi)].map(x=>clean(x[1]));if(cells.length<2)continue;let vendor=cells[0],contract=cells[1];if(!vendor||!contract||/contractor name/i.test(vendor)||!/(36F797|V797|VA\d)/i.test(contract))continue;out.push({vendor,contractNumber:contract,sin,small:cells[2]||'',veteranOwned:cells[3]||'',sdvosb:cells[4]||'',sdb:cells[5]||'',eightA:cells[6]||'',womanOwned:cells[7]||'',hubzone:cells[8]||''});}return out;}
async function buildVaRoster(opts={}){fs.mkdirSync(OUT,{recursive:true});let html=await fetchText(VA_VENDOR_LIST);let sins=extractVaSinOptions(html);console.log(`[K7F] VA SIN options discovered=${sins.length}`);if(sins.length<5)return {authoritative:false,reason:`VA_CCST_SELECTOR_INSUFFICIENT_SINS:${sins.length}`,sinsDiscovered:sins.length,contracts:0,rows:[]};if(opts.maxSins)sins=sins.slice(0,opts.maxSins);let all=[];for(let i=0;i<sins.length;i++){let sin=sins[i];let page=await fetchText(`${VA_VENDOR_LIST}?sin=${encodeURIComponent(sin)}`);all.push(...parseVendorRows(page,sin));if((i+1)%20===0)console.log(`[K7F] VA SIN progress ${i+1}/${sins.length}; rows=${all.length}`);await sleep(Number(opts.vaDelayMs)||120);}let map=new Map();for(const r of all){let k=`${r.contractNumber}|${norm(r.vendor)}`;if(!map.has(k))map.set(k,r);}let rows=[...map.values()];if(rows.length<500)return {authoritative:false,reason:`VA_CCST_CONTRACT_COUNT_TOO_LOW:${rows.length}`,sinsDiscovered:sins.length,contracts:rows.length,rows};fs.writeFileSync(path.join(OUT,'VA_FSS_CONTRACT_ROSTER.csv'),['vendor,contract_number,sin,small,veteran_owned,sdvosb,sdb,eight_a,woman_owned,hubzone',...rows.map(r=>[r.vendor,r.contractNumber,r.sin,r.small,r.veteranOwned,r.sdvosb,r.sdb,r.eightA,r.womanOwned,r.hubzone].map(csv).join(','))].join('\n'));return {authoritative:true,sinsDiscovered:sins.length,contracts:rows.length,rows};}
function chooseCandidate(vendor,candidates){let usable=candidates.filter(x=>String(x?.uei||'').trim()&&x?.name);let exact=usable.filter(x=>norm(x.name)===norm(vendor));let byUei=a=>[...new Map(a.map(x=>[String(x.uei).trim().toUpperCase(),x])).values()];let eu=byUei(exact);if(eu.length===1)return {match:eu[0],status:'USASPENDING_NORMALIZED_LEGAL_NAME',score:1};let scored=usable.map(x=>({x,score:similarity(vendor,x.name)})).sort((a,b)=>b.score-a.score);if(!scored.length)return null;let top=scored[0],second=scored[1];if(top.score>=0.82&&(!second||top.score-second.score>=0.18))return {match:top.x,status:'USASPENDING_CONSERVATIVE_TOKEN_MATCH',score:+top.score.toFixed(4)};return null;}
async function resolveVaUeis(rows,opts={}){let svc=new AwardHistoryTruthService({requestTimeoutMs:20000});let cp=path.join(OUT,'VA_FSS_UEI_RESOLUTION_CHECKPOINT_V15.json');let state={rows:{}};if(fs.existsSync(cp)){try{state=JSON.parse(fs.readFileSync(cp,'utf8'));if(!state.rows)state={rows:{}};}catch{state={rows:{}};}}let out=[];for(let i=0;i<rows.length;i++){let r=rows[i],k=`${r.contractNumber}|${norm(r.vendor)}`;if(state.rows[k]){out.push(state.rows[k]);continue;}let rec={...r,uei:'',ueiStatus:'UNRESOLVED',matchScore:null};try{let candidates=await svc.resolveRecipientByKeyword(r.vendor);let chosen=chooseCandidate(r.vendor,candidates);if(chosen){rec.uei=String(chosen.match.uei).trim().toUpperCase();rec.ueiStatus=chosen.status;rec.matchScore=chosen.score;}else rec.ueiStatus='NO_UNAMBIGUOUS_AUTHORITATIVE_MATCH';}catch(e){rec.ueiStatus='LOOKUP_ERROR';rec.error=e.message;}state.rows[k]=rec;out.push(rec);if((i+1)%25===0){console.log(`[K7F] VA UEI progress ${i+1}/${rows.length}`);fs.writeFileSync(cp,JSON.stringify(state,null,2));}await sleep(Number(opts.identityDelayMs)||180);}fs.writeFileSync(cp,JSON.stringify(state,null,2));fs.writeFileSync(path.join(OUT,'VA_FSS_UEI_RESOLVED_V15.csv'),['vendor,contract_number,sin,uei,uei_status,match_score',...out.map(r=>[r.vendor,r.contractNumber,r.sin,r.uei,r.ueiStatus,r.matchScore??''].map(csv).join(','))].join('\n'));return out;}
async function bulkAwards(ueis,opts={}){let svc=new AwardHistoryTruthService({requestTimeoutMs:30000});let cp=path.join(OUT,'BULK_AWARD_TRUTH_CHECKPOINT.json');let state={completed:{},errors:{}};if(fs.existsSync(cp)){try{state=JSON.parse(fs.readFileSync(cp,'utf8'));}catch{}}let limit=Number(opts.awardLimit)||ueis.length;let todo=ueis.filter(u=>!state.completed[u]&&!state.errors[u]).slice(0,limit);for(let i=0;i<todo.length;i++){let u=todo[i];try{let r=await svc.auditByUei(u,{pageSize:100,maxPages:Number(opts.maxPages)||25});state.completed[u]={uei:u,ok:r.ok,status:r.status,federalRevenue:r.federalRevenue||0,awardCount:r.awardCount||0,primeAwardedRevenue:r.primeAwardedRevenue||0,subcontractedRevenue:r.subcontractedRevenue||0,generatedAt:r.generatedAt||new Date().toISOString()};}catch(e){state.errors[u]={uei:u,error:e.message,at:new Date().toISOString()};}if((i+1)%10===0){console.log(`[K7F] award progress ${i+1}/${todo.length}; totalCompleted=${Object.keys(state.completed).length}`);fs.writeFileSync(cp,JSON.stringify(state,null,2));}await sleep(Number(opts.awardDelayMs)||220);}fs.writeFileSync(cp,JSON.stringify(state,null,2));let rows=Object.values(state.completed);fs.writeFileSync(path.join(OUT,'BULK_AWARD_TRUTH.csv'),['uei,federal_revenue,award_count,prime_revenue,subcontract_revenue,status,generated_at',...rows.map(r=>[r.uei,r.federalRevenue,r.awardCount,r.primeAwardedRevenue,r.subcontractedRevenue,r.status,r.generatedAt].map(csv).join(','))].join('\n'));return {completed:rows.length,errors:Object.keys(state.errors).length,remaining:Math.max(0,ueis.length-rows.length-Object.keys(state.errors).length),output:path.join(OUT,'BULK_AWARD_TRUTH.csv')};}
async function run(opts={}){fs.mkdirSync(OUT,{recursive:true});let gsa=loadGsaUeis();console.log(`[K7F] confirmed GSA UEIs=${gsa.ueis.length}`);console.log(`[K7F] GSA source=${gsa.snapshot}`);let va=await buildVaRoster(opts);if(!va.authoritative){let result={ok:false,gate:'P1.5K7F_AUTHORITATIVE_VA_FSS_AND_BULK_AWARD_REFRESH',version:'1.5-conservative-va-uei',generatedAt:new Date().toISOString(),gsa:{uniqueUei:gsa.ueis.length,source:gsa.snapshot},vaFss:{source:'VA NAC CCST /NAC/Vendor/List selector',authoritativeRoster:false,sinsDiscovered:va.sinsDiscovered,contracts:va.contracts,reason:va.reason},awardTargets:0,award:{completed:0,errors:0,remaining:0},monthlyProgramProven:false,liveCampaignsMutated:false,nextAction:'VA_CCST_EXTRACTION_FAILED_CLOSED'};fs.writeFileSync(path.join(OUT,'K7F_SUMMARY.json'),JSON.stringify(result,null,2));return result;}let vaResolved=await resolveVaUeis(va.rows,opts);let vaUeis=[...new Set(vaResolved.map(x=>x.uei).filter(Boolean))];let resolutionRate=va.contracts?vaUeis.length/va.contracts:0;let conservativeMatches=vaResolved.filter(x=>x.ueiStatus==='USASPENDING_CONSERVATIVE_TOKEN_MATCH').length;let normalizedMatches=vaResolved.filter(x=>x.ueiStatus==='USASPENDING_NORMALIZED_LEGAL_NAME').length;let vaResolutionAuthoritative=vaUeis.length>=400&&resolutionRate>=0.25;let targets=[...new Set([...gsa.ueis,...vaUeis])];let award=await bulkAwards(targets,opts);let result={ok:true,gate:'P1.5K7F_AUTHORITATIVE_VA_FSS_AND_BULK_AWARD_REFRESH',version:'1.5-conservative-va-uei',generatedAt:new Date().toISOString(),vaFss:{source:'VA NAC CCST',sinsDiscovered:va.sinsDiscovered,contracts:va.contracts,ueiResolved:vaUeis.length,ueiResolutionRate:+resolutionRate.toFixed(4),normalizedMatches,conservativeMatches,authoritativeRoster:true,ueiResolutionAuthoritative:vaResolutionAuthoritative,unresolvedContracts:va.contracts-vaUeis.length},gsa:{uniqueUei:gsa.ueis.length,source:gsa.snapshot},awardTargets:targets.length,award,monthlyProgramProven:false,liveCampaignsMutated:false,nextAction:!vaResolutionAuthoritative?'IMPROVE_VA_UEI_RESOLUTION_BEFORE_CANONICAL_PROMOTION':award.remaining===0?'VALIDATE_COUNTS_AND_PROMOTE_CANONICAL_MASTER':'CONTINUE_K7F_FROM_CHECKPOINT_UNTIL_AWARD_REFRESH_COMPLETE'};fs.writeFileSync(path.join(OUT,'K7F_SUMMARY.json'),JSON.stringify(result,null,2));return result;}module.exports={run};