'use strict';
const fs=require('fs');const path=require('path');
const OUT=path.join(process.cwd(),'DATA','OUTBOUND','FEDERAL_AUTHORITATIVE_SOURCE_GATE_K7D');
const ROOT='D:\\P2GC_Intelligence'; const MAX_BYTES=2*1024*1024; const MAX_ROWS=5000;
function walk(d,a=[]){let es;try{es=fs.readdirSync(d,{withFileTypes:true});}catch{return a;}for(const e of es){const p=path.join(d,e.name);if(e.isDirectory()){if(!/node_modules|\.git|BACKUP|_BACKUPS|archive/i.test(p))walk(p,a);}else if(/\.csv$/i.test(e.name))a.push(p);}return a;}
function readHead(p){let fd=fs.openSync(p,'r');try{let st=fs.fstatSync(fd),n=Math.min(st.size,MAX_BYTES),b=Buffer.alloc(n);fs.readSync(fd,b,0,n,0);return {text:b.toString('utf8'),st};}finally{fs.closeSync(fd);}}
function csv(s){let a=[],x='',q=false;for(let i=0;i<s.length;i++){let c=s[i];if(c==='"'){if(q&&s[i+1]==='"'){x+='"';i++;}else q=!q;}else if(c===','&&!q){a.push(x);x='';}else x+=c;}a.push(x);return a;}
function inspect(p){let o;try{o=readHead(p);}catch{return null;}let ls=o.text.split(/\r?\n/).filter(Boolean);if(ls.length<2)return null;let h=csv(ls[0]).map(x=>x.trim()),hl=h.map(x=>x.toLowerCase());let ix=(arr)=>hl.findIndex(x=>arr.includes(x));let ui=ix(['uei','sam uei','recipient uei','uei (unique entity identifier)']);let ri=ix(['federal_revenue','federal total revenue','federal_total_revenue','normalized_revenue','award amount','total_obligated_amount']);let vi=ix(['vehicle','vehicle_name','vehicle_hint']);let si=ix(['segment','existing_segment']);let u=new Set(),g=0,v=0,pos=0,zero=0;for(let i=1;i<Math.min(ls.length,MAX_ROWS+1);i++){let r=csv(ls[i]);let ue=ui>=0?String(r[ui]||'').trim().toUpperCase():'';if(ue)u.add(ue);let z=((vi>=0?r[vi]:'')+' '+(si>=0?r[si]:'')+' '+path.basename(p)).toUpperCase();if(/GSA|MAS/.test(z))g++;if(/(^|[^A-Z])VA([^A-Z]|$)|FSS/.test(z))v++;if(ri>=0){let n=Number(String(r[ri]||'').replace(/[$,]/g,''));if(Number.isFinite(n)){if(n>0)pos++;else zero++;}}}return{path:p,mtime:o.st.mtime.toISOString(),ageDays:+((Date.now()-o.st.mtimeMs)/86400000).toFixed(1),size:o.st.size,headers:h,ueiUniqueSample:u.size,gsa:g,va:v,revenuePositive:pos,revenueZero:zero};}
function authoritative(x,type){if(!x||x.ageDays>45||x.ueiUniqueSample===0)return false;let p=x.path.toLowerCase();if(/campaign_status|instantly|outbound|upload_delta|email_ready/.test(p))return false;if(type==='GSA')return x.gsa>0 && /(gsa|elibrary|mas)/.test(p);if(type==='VA')return x.va>0 && /(va|fss)/.test(p);if(type==='AWARD')return x.revenuePositive>0 && /(award|usaspending|spending|contract_award)/.test(p);return false;}
async function run(){fs.mkdirSync(OUT,{recursive:true});let files=walk(ROOT,[]),ins=[];for(const p of files){let n=p.toLowerCase();if(!/(gsa|elibrary|mas|va|fss|award|usaspending|spending|contract)/.test(n))continue;let x=inspect(p);if(x)ins.push(x);}let pick=t=>ins.filter(x=>authoritative(x,t)).sort((a,b)=>a.ageDays-b.ageDays||b.ueiUniqueSample-a.ueiUniqueSample);let GSA=pick('GSA'),VA=pick('VA'),AWARD=pick('AWARD');let result={ok:true,gate:'P1.5K7D_FEDERAL_AUTHORITATIVE_SOURCE_GATE',version:'1.0',generatedAt:new Date().toISOString(),rules:{freshnessDays:45,ueiRequired:true,rejectDerivedCampaignArtifacts:true,gsaPathEvidenceRequired:true,vaFssPathEvidenceRequired:true,awardPathAndPositiveRevenueRequired:true},accepted:{GSA:GSA.slice(0,10),VA_FSS:VA.slice(0,10),AWARD:AWARD.slice(0,10)},status:{gsaAuthoritativeFresh:GSA.length>0,vaFssAuthoritativeFresh:VA.length>0,awardAuthoritativeFresh:AWARD.length>0,monthlyProgramProven:GSA.length>0&&VA.length>0&&AWARD.length>0},liveCampaignsMutated:false,nextAction:(!VA.length||!AWARD.length)?'EXECUTE_MISSING_VA_FSS_AND_OR_AWARD_REFRESH_BEFORE_CANONICAL_REBUILD':'PROMOTE_ACCEPTED_SOURCES_AND_REBUILD_CANONICAL_MASTER'};fs.writeFileSync(path.join(OUT,'K7D_AUTHORITATIVE_SOURCE_GATE.json'),JSON.stringify(result,null,2));return result;}module.exports={run};