'use strict';
const fs=require('fs');
const path=require('path');
const AwardHistoryTruthService=require('./orion/AwardHistoryTruthService');
const OUT=path.join(process.cwd(),'DATA','staging','government_data','K7F_VA_FSS_BULK_AWARD_REFRESH');
const CP=path.join(OUT,'BULK_AWARD_TRUTH_CHECKPOINT.json');
function sleep(ms){return new Promise(r=>setTimeout(r,ms));}
function csv(v){v=String(v??'');return /[",\n]/.test(v)?'"'+v.replace(/"/g,'""')+'"':v;}
function isTransientErrorText(text){return /timed out|ECONNRESET|ECONNREFUSED|ENETUNREACH|EAI_AGAIN|fetch failed|socket|429|\b5\d\d\b|408|425|temporar|rate limit|too many requests/i.test(String(text||''));}
function loadState(){if(!fs.existsSync(CP))throw new Error(`AWARD_CHECKPOINT_MISSING: ${CP}`);let state=JSON.parse(fs.readFileSync(CP,'utf8'));state.completed=state.completed||{};state.errors=state.errors||{};state.transientErrors=state.transientErrors||{};let requeued=0;for(const [u,e] of Object.entries(state.errors)){if(isTransientErrorText(e?.error)){state.transientErrors[u]={...e,requeuedAt:new Date().toISOString()};delete state.errors[u];requeued++;}}return {state,requeued};}
function writeOutputs(state){fs.mkdirSync(OUT,{recursive:true});fs.writeFileSync(CP,JSON.stringify(state,null,2));let rows=Object.values(state.completed);fs.writeFileSync(path.join(OUT,'BULK_AWARD_TRUTH.csv'),['uei,federal_revenue,award_count,prime_revenue,subcontract_revenue,status,generated_at',...rows.map(r=>[r.uei,r.federalRevenue||0,r.awardCount||0,r.primeAwardedRevenue||0,r.subcontractedRevenue||0,r.status||'',r.generatedAt||''].map(csv).join(','))].join('\n'));}
async function run(opts={}){let {state,requeued}=loadState();let pending=Object.keys(state.transientErrors).filter(u=>!state.completed[u]&&!state.errors[u]);let limit=Math.max(0,Number(opts.limit)||100);let batch=pending.slice(0,limit);let svc=new AwardHistoryTruthService({requestTimeoutMs:Number(opts.requestTimeoutMs)||30000,maxRetries:Number(opts.maxRetries)||5,retryBaseMs:Number(opts.retryBaseMs)||2000});let recovered=0,stillTransient=0,terminalAdded=0;console.log(`[K7G] transient queue start=${pending.length}; batch=${batch.length}; requeued=${requeued}`);for(let i=0;i<batch.length;i++){let u=batch[i];try{let r=await svc.auditByUei(u,{pageSize:100,maxPages:Number(opts.maxPages)||25});state.completed[u]={uei:u,ok:r.ok,status:r.status,federalRevenue:r.federalRevenue||0,awardCount:r.awardCount||0,primeAwardedRevenue:r.primeAwardedRevenue||0,subcontractedRevenue:r.subcontractedRevenue||0,generatedAt:r.generatedAt||new Date().toISOString()};delete state.transientErrors[u];recovered++;}catch(e){let rec={uei:u,error:e.message,at:new Date().toISOString(),transient:Boolean(e?.transient)||isTransientErrorText(e?.message)};if(rec.transient){state.transientErrors[u]=rec;stillTransient++;}else{delete state.transientErrors[u];state.errors[u]=rec;terminalAdded++;}}if((i+1)%10===0||i===batch.length-1){console.log(`[K7G] progress ${i+1}/${batch.length}; recovered=${recovered}; transientPending=${Object.keys(state.transientErrors).length}; terminalErrors=${Object.keys(state.errors).length}`);writeOutputs(state);}await sleep(Number(opts.delayMs)||1500);}writeOutputs(state);let result={ok:true,gate:'P1.5K7G_AWARD_TRANSIENT_DRAIN',version:'1.0',generatedAt:new Date().toISOString(),processed:batch.length,recovered,stillTransient,terminalAdded,completedTotal:Object.keys(state.completed).length,terminalErrorsTotal:Object.keys(state.errors).length,transientPending:Object.keys(state.transientErrors).length,requeuedLegacyTransient:requeued,liveCampaignsMutated:false,nextAction:Object.keys(state.transientErrors).length?'CONTINUE_K7G_DRAIN':'RETURN_TO_K7F_FRESH_TARGET_BATCHES'};fs.writeFileSync(path.join(OUT,'K7G_SUMMARY.json'),JSON.stringify(result,null,2));return result;}
module.exports={run};