'use strict';
const fs=require('fs');
const path=require('path');
const cp=require('child_process');
const readline=require('readline');
const OUT=path.join(process.cwd(),'DATA','staging','government_data','K7H_BULK_AWARD_RECONSTRUCTION');
const FRESH_DAYS=45;
function csvLine(s){let a=[],x='',q=false;for(let i=0;i<s.length;i++){let c=s[i];if(c==='"'){if(q&&s[i+1]==='"'){x+='"';i++;}else q=!q;}else if(c===','&&!q){a.push(x);x='';}else x+=c;}a.push(x);return a;}
function csv(v){v=String(v??'');return /[",\n]/.test(v)?'"'+v.replace(/"/g,'""')+'"':v;}
function normHeader(s){return String(s||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');}
function walk(d,a=[],depth=0){if(depth>3||a.length>5000)return a;let es;try{es=fs.readdirSync(d,{withFileTypes:true});}catch{return a;}for(const e of es){let p=path.join(d,e.name);if(e.isDirectory()){if(!/node_modules|\.git|backup|archive|checkpoint|expanded/i.test(p))walk(p,a,depth+1);}else if(/\.(csv|zip)$/i.test(e.name))a.push(p);}return a;}
function candidateRoots(){let r=[process.env.USERPROFILE?path.join(process.env.USERPROFILE,'Downloads'):null,path.join(process.cwd(),'DATA','staging','government_data'),path.join(process.cwd(),'DATA','downloads'),path.join('D:\\P2GC_Intelligence','downloads'),path.join('D:\\P2GC_Intelligence','DATA','downloads')].filter(Boolean);return [...new Set(r)].filter(p=>fs.existsSync(p));}
function isFresh(p){try{return (Date.now()-fs.statSync(p).mtimeMs)/86400000<=FRESH_DAYS;}catch{return false;}}
function looksAwardFile(p){let n=path.basename(p).toLowerCase();return /(usaspending|prime.*transaction|prime.*award|subaward|subcontract|award.*download|contracts.*transactions|all_prime|all_sub)/i.test(n);}
function expandFreshZips(files){fs.mkdirSync(OUT,{recursive:true});let expanded=[];for(const z of files.filter(p=>/\.zip$/i.test(p)&&isFresh(p)&&looksAwardFile(p))){let dest=path.join(OUT,'expanded',path.basename(z,'.zip').replace(/[^A-Za-z0-9_.-]+/g,'_'));if(!fs.existsSync(dest)||!fs.readdirSync(dest).length){fs.mkdirSync(dest,{recursive:true});try{cp.execFileSync('powershell.exe',['-NoProfile','-Command',`Expand-Archive -LiteralPath '${z.replace(/'/g,"''")}' -DestinationPath '${dest.replace(/'/g,"''")}' -Force`],{stdio:'ignore'});}catch{continue;}}walk(dest,expanded);}return expanded.filter(p=>/\.csv$/i.test(p));}
function detect(h){let H=h.map(normHeader),find=(arr)=>{for(const x of arr){let i=H.indexOf(x);if(i>=0)return i;}return -1;};return {uei:find(['recipient_uei','recipient_uei_number','uei','awardee_or_recipient_uei','recipient_uei_sam','subawardee_uei','sub_recipient_uei']),amount:find(['federal_action_obligation','federal_action_obligation_amount','award_amount','current_total_value_of_award','total_obligated_amount','subaward_amount','sub_award_amount']),awardId:find(['award_id_piid','award_id','piid','prime_award_id','subaward_id','sub_award_id']),actionDate:find(['action_date','subaward_action_date','sub_award_date']),recipientName:find(['recipient_name','recipient_name_raw','awardee_or_recipient_legal_business_name','subawardee_name','sub_awardee_name'])};}
async function parseAwardCsv(p,agg,stats){let st;try{st=fs.statSync(p);}catch{return;}let stream=fs.createReadStream(p,{encoding:'utf8'});let rl=readline.createInterface({input:stream,crlfDelay:Infinity});let header=null,d=null,fileRows=0,usable=0;try{for await(const line of rl){if(!line)continue;if(!header){header=csvLine(line);d=detect(header);if(d.uei<0||d.amount<0){stats.rejected.push({path:p,reason:'MISSING_UEI_OR_AMOUNT',headers:header.slice(0,60)});rl.close();stream.destroy();return;}continue;}let r=csvLine(line);let u=String(r[d.uei]||'').trim().toUpperCase();if(!u)continue;let n=Number(String(r[d.amount]||'').replace(/[$,]/g,''));if(!Number.isFinite(n))continue;fileRows++;let cur=agg.get(u)||{uei:u,revenue:0,awardIds:new Set(),rows:0,latestActionDate:null,name:null};cur.revenue+=n;cur.rows++;if(d.awardId>=0&&r[d.awardId])cur.awardIds.add(String(r[d.awardId]).trim());if(d.actionDate>=0&&r[d.actionDate]&&(!cur.latestActionDate||String(r[d.actionDate])>cur.latestActionDate))cur.latestActionDate=String(r[d.actionDate]);if(!cur.name&&d.recipientName>=0&&r[d.recipientName])cur.name=String(r[d.recipientName]).trim();agg.set(u,cur);usable++;if(fileRows%250000===0)console.log(`[K7H] ${path.basename(p)} rows=${fileRows}; aggregateUEIs=${agg.size}`);}stats.accepted.push({path:p,mtime:st.mtime.toISOString(),rows:fileRows,usable});}finally{rl.close();}}
function tier(rev){if(rev===0)return 'NO_SALES';if(rev>0&&rev<3000000)return 'ONE_TO_LT_3M';if(rev>=3000000&&rev<10000000)return 'THREE_TO_LT_10M';if(rev>=10000000)return 'TEN_M_PLUS';return 'UNKNOWN';}
function findGsa(){let roots=['D:\\P2GC_Intelligence','C:\\P2GC_Intelligence'];for(const root of roots){let base=path.join(root,'MILES_ENTERPRISE','DATA','staging','government_data','gsa_holder_snapshot');if(!fs.existsSync(base))continue;let ds=fs.readdirSync(base).map(n=>path.join(base,n,'gsa_elibrary_schedule_MAS.csv')).filter(p=>fs.existsSync(p)).sort((a,b)=>fs.statSync(b).mtimeMs-fs.statSync(a).mtimeMs);if(ds.length)return ds[0];}return null;}
function loadUeisFromCsv(p,names){if(!p||!fs.existsSync(p))return new Set();let ls=fs.readFileSync(p,'utf8').split(/\r?\n/).filter(Boolean);if(!ls.length)return new Set();let h=csvLine(ls[0]).map(normHeader),idx=-1;for(const n of names){idx=h.indexOf(normHeader(n));if(idx>=0)break;}let s=new Set();if(idx<0)return s;for(let i=1;i<ls.length;i++){let u=String(csvLine(ls[i])[idx]||'').trim().toUpperCase();if(u)s.add(u);}return s;}
function loadVaResolved(){let p=path.join(process.cwd(),'DATA','staging','government_data','K7F_VA_FSS_BULK_AWARD_REFRESH','VA_FSS_UEI_RESOLUTION_CHECKPOINT_V15.json');if(!fs.existsSync(p))return new Set();let j;try{j=JSON.parse(fs.readFileSync(p,'utf8'));}catch{return new Set();}return new Set(Object.values(j.rows||{}).map(x=>String(x.uei||'').trim().toUpperCase()).filter(Boolean));}
function summarizeFamily(label,ueis,agg,coverageAvailable){let c={NO_SALES:0,ONE_TO_LT_3M:0,THREE_TO_LT_10M:0,TEN_M_PLUS:0,UNKNOWN:0,total:ueis.size};for(const u of ueis){let a=agg.get(u);let t=a?tier(a.revenue):(coverageAvailable?'NO_SALES':'UNKNOWN');c[t]=(c[t]||0)+1;}return {family:label,...c};}
async function run(){fs.mkdirSync(OUT,{recursive:true});let roots=candidateRoots();console.log(`[K7H] scan roots=${roots.join(' | ')||'NONE'}`);let files=[];for(const r of roots)walk(r,files);let fresh=files.filter(p=>isFresh(p)&&looksAwardFile(p));console.log(`[K7H] fresh candidate files=${fresh.length}`);let expanded=expandFreshZips(fresh);let csvs=[...new Set([...fresh.filter(p=>/\.csv$/i.test(p)),...expanded])];console.log(`[K7H] candidate CSVs=${csvs.length}`);let agg=new Map(),stats={accepted:[],rejected:[]};for(let i=0;i<csvs.length;i++){console.log(`[K7H] parsing ${i+1}/${csvs.length}: ${csvs[i]}`);await parseAwardCsv(csvs[i],agg,stats);}let coverageAvailable=stats.accepted.length>0;let gsaPath=findGsa(),gsa=loadUeisFromCsv(gsaPath,['SAM UEI','uei']),va=loadVaResolved();let awardRows=[...agg.values()];fs.writeFileSync(path.join(OUT,'BULK_AWARD_BY_UEI.csv'),['uei,federal_revenue,award_count,source_rows,latest_action_date,recipient_name,tier',...awardRows.map(r=>[r.uei,r.revenue,r.awardIds.size,r.rows,r.latestActionDate||'',r.name||'',tier(r.revenue)].map(csv).join(','))].join('\n'));let result={ok:coverageAvailable,gate:'P1.5K7H_BULK_LOCAL_AWARD_RECONSTRUCTION',version:'1.2-unknown-without-coverage',generatedAt:new Date().toISOString(),scanRoots:roots,freshnessDays:FRESH_DAYS,awardCoverageAvailable:coverageAvailable,awardFilesAccepted:stats.accepted,awardFilesRejected:stats.rejected.slice(0,20),awardUeisAggregated:agg.size,gsa:{source:gsaPath,uei:gsa.size,tiers:summarizeFamily('GSA',gsa,agg,coverageAvailable)},vaFss:{source:'K7F authoritative resolved UEIs',uei:va.size,tiers:summarizeFamily('VA_FSS',va,agg,coverageAvailable)},liveCampaignsMutated:false,nextAction:coverageAvailable?'VALIDATE_BULK_COUNTS_AND_EXPAND_TO_CERTIFICATION_AND_SAM_SBS_FAMILIES':'NO_FRESH_USASPENDING_BULK_EXPORT_FOUND; ALL_UNMATCHED_REVENUE_REMAINS_UNKNOWN; DOWNLOAD_ONE_CURRENT PRIME+SUBAWARD EXPORT TO DOWNLOADS AND RERUN'};fs.writeFileSync(path.join(OUT,'K7H_SUMMARY.json'),JSON.stringify(result,null,2));return result;}module.exports={run};