'use strict';
const fs=require('fs');const path=require('path');
const ROOTS=['D:\\P2GC_Intelligence'];
const OUT=path.join(process.cwd(),'DATA','OUTBOUND','FEDERAL_REFRESH_RECOVERY_K7C');
const MAX=5000;
function walk(d,a=[]){let es;try{es=fs.readdirSync(d,{withFileTypes:true});}catch{return a;}for(const e of es){const p=path.join(d,e.name);if(e.isDirectory()){if(!/node_modules|\.git|CANONICAL_FEDERAL_MASTER_K7B/i.test(p))walk(p,a);}else if(/\.(csv|json)$/i.test(e.name))a.push(p);}return a;}
function csvLine(s){let a=[],x='',q=false;for(let i=0;i<s.length;i++){let c=s[i];if(c==='"'){if(q&&s[i+1]==='"'){x+='"';i++;}else q=!q;}else if(c===','&&!q){a.push(x);x='';}else x+=c;}a.push(x);return a;}
function inspect(p){let st;try{st=fs.statSync(p);}catch{return null;}let txt;try{txt=fs.readFileSync(p,'utf8');}catch{return null;}let ls=txt.split(/\r?\n/).filter(Boolean);if(!ls.length)return null;let h=csvLine(ls[0]).map(x=>x.trim());let hl=h.map(x=>x.toLowerCase());let idx=(re)=>hl.findIndex(x=>re.test(x));let ui=idx(/^(uei|recipient uei)$/),vi=idx(/^(vehicle|vehicle_name|vehicle_hint)$/),ri=idx(/^(federal_revenue|federal_total_revenue|normalized_revenue|total_obligated_amount)$/),si=idx(/^(segment|existing_segment)$/),src=idx(/source/);let g=0,v=0,u=0,pos=0,zero=0;for(let i=1;i<Math.min(ls.length,MAX+1);i++){let r=csvLine(ls[i]);let ue=ui>=0?(r[ui]||'').trim():'';if(ue)u++;let z=((vi>=0?r[vi]:'')+' '+(si>=0?r[si]:'')+' '+(src>=0?r[src]:'')).toUpperCase();if(/GSA|MAS/.test(z))g++;if(/\bVA\b|FSS/.test(z))v++;if(ri>=0){let n=Number(String(r[ri]||'').replace(/[$,]/g,''));if(Number.isFinite(n)){if(n>0)pos++;else zero++;}}}let age=(Date.now()-st.mtimeMs)/86400000;return{path:p,mtime:st.mtime.toISOString(),ageDays:+age.toFixed(1),size:st.size,headers:h,rowsSampled:Math.min(Math.max(ls.length-1,0),MAX),uei:u,gsa:g,va:v,revenuePositive:pos,revenueZero:zero};}
function score(x,type){if(!x)return-1e9;let n=path.basename(x.path).toLowerCase(),s=0;s+=Math.max(0,120-x.ageDays);s+=x.uei?30:0;if(type==='GSA')s+=x.gsa?80:0;if(type==='VA')s+=x.va?80:0;if(type==='AWARD')s+=x.revenuePositive?80:0;if(/raw|download|export|master|contract_award|spending|sam_public|gsa|va|fss/.test(n))s+=15;if(/outbound|segment|no_sales|expired|email_ready/.test(n))s-=35;return+s.toFixed(2);}
async function run(){fs.mkdirSync(OUT,{recursive:true});let files=[];for(const r of ROOTS)walk(r,files);let cand=[];for(const p of files){let n=p.toLowerCase();if(!/(gsa|mas|fss|\\va|award|spending|sam|sbs|contract)/i.test(n))continue;let x=inspect(p);if(x)cand.push(x);}let top={GSA:[...cand].sort((a,b)=>score(b,'GSA')-score(a,'GSA')).slice(0,30),VA:[...cand].sort((a,b)=>score(b,'VA')-score(a,'VA')).slice(0,30),AWARD:[...cand].sort((a,b)=>score(b,'AWARD')-score(a,'AWARD')).slice(0,30)};let fresh={GSA:top.GSA.filter(x=>x.ageDays<=45&&x.gsa>0),VA:top.VA.filter(x=>x.ageDays<=45&&x.va>0),AWARD:top.AWARD.filter(x=>x.ageDays<=45&&x.revenuePositive>0)};let result={ok:true,gate:'P1.5K7C_FEDERAL_REFRESH_RECOVERY',version:'1.0-read-only',generatedAt:new Date().toISOString(),filesScanned:files.length,candidatesInspected:cand.length,topCandidates:top,freshAuthoritativeCandidates:{GSA:fresh.GSA.slice(0,10),VA:fresh.VA.slice(0,10),AWARD:fresh.AWARD.slice(0,10)},refreshStatus:{gsaFresh:fresh.GSA.length>0,vaFssFresh:fresh.VA.length>0,awardFresh:fresh.AWARD.length>0,monthlyProgramProven:fresh.GSA.length>0&&fresh.VA.length>0&&fresh.AWARD.length>0},liveCampaignsMutated:false,nextAction:(fresh.GSA.length&&fresh.VA.length&&fresh.AWARD.length)?'REVIEW_FRESH_CANDIDATES_FOR_CANONICAL_PROMOTION':'REFRESH_MISSING_AUTHORITATIVE_SOURCE_NOW; DO_NOT_TOUCH_INSTANTLY'};fs.writeFileSync(path.join(OUT,'K7C_REFRESH_RECOVERY.json'),JSON.stringify(result,null,2));return result;}module.exports={run};