'use strict';
const fs=require('fs');const path=require('path');
const ROOTS=['D:\\P2GC_Intelligence\\ORION_CORE','D:\\P2GC_Intelligence'];
const OUT=path.join(process.cwd(),'DATA','OUTBOUND','ORION_REVENUE_SOURCE_RECOVERY_K7K');
function csvLine(s){let a=[],x='',q=false;for(let i=0;i<s.length;i++){let c=s[i];if(c==='"'){if(q&&s[i+1]==='"'){x+='"';i++;}else q=!q;}else if(c===','&&!q){a.push(x);x='';}else x+=c;}a.push(x);return a;}
function norm(s){return String(s||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');}
function walk(d,a=[],depth=0){if(depth>4||a.length>4000)return a;let es;try{es=fs.readdirSync(d,{withFileTypes:true});}catch{return a;}for(const e of es){let p=path.join(d,e.name);if(e.isDirectory()){if(!/node_modules|\.git|backup|archive|checkpoint|downloads|staging/i.test(p))walk(p,a,depth+1);}else if(/\.csv$/i.test(e.name))a.push(p);}return a;}
function scoreName(p){let n=path.basename(p).toLowerCase(),s=0;if(/award|revenue|spending|federal|master|segment/.test(n))s+=10;if(/evan|orion|final/.test(n))s+=5;if(/email|outbound|campaign|no_sales/.test(n))s-=10;return s;}
function inspect(p){let st;try{st=fs.statSync(p);}catch{return null;}if(st.size>800*1024*1024)return null;let fd;try{fd=fs.openSync(p,'r');}catch{return null;}let buf=Buffer.alloc(Math.min(st.size,8*1024*1024));let n=0;try{n=fs.readSync(fd,buf,0,buf.length,0);}finally{fs.closeSync(fd);}let txt=buf.slice(0,n).toString('utf8');let lines=txt.split(/\r?\n/).filter(Boolean);if(lines.length<2)return null;let h=csvLine(lines[0]),H=h.map(norm);let ui=H.findIndex(x=>/^(uei|sam_uei|recipient_uei)$/.test(x));let revCandidates=['normalized_revenue','federal_total_revenue','federal_revenue','federal_total_revenue_x','total_obligated_amount','award_amount'];let ris=revCandidates.map(x=>H.indexOf(x)).filter(i=>i>=0);if(ui<0||!ris.length)return null;let best=null;for(const ri of ris){let sampled=0,pos=0,zero=0,blank=0,sum=0;for(let i=1;i<lines.length;i++){let r=csvLine(lines[i]);let u=String(r[ui]||'').trim();if(!u)continue;let raw=String(r[ri]??'').replace(/[$,]/g,'').trim();if(raw===''){blank++;continue;}let v=Number(raw);if(!Number.isFinite(v))continue;sampled++;if(v>0){pos++;sum+=v;}else if(v===0)zero++;}let cand={column:h[ri],sampled,positive:pos,zero,blank,positiveRate:sampled?pos/sampled:0,positiveSum:sum};if(!best||cand.positive>best.positive||(cand.positive===best.positive&&cand.positiveSum>best.positiveSum))best=cand;}
return {path:p,mtime:st.mtime.toISOString(),size:st.size,headers:h.slice(0,80),ueiColumn:h[ui],revenue:best,nameScore:scoreName(p)};}
async function run(){fs.mkdirSync(OUT,{recursive:true});let files=[];for(const r of ROOTS)if(fs.existsSync(r))walk(r,files);files=[...new Set(files)];let cand=[];for(const p of files){let x=inspect(p);if(x)cand.push(x);}cand.sort((a,b)=>(b.revenue.positive-a.revenue.positive)||((b.revenue.positiveRate||0)-(a.revenue.positiveRate||0))||(b.nameScore-a.nameScore));let top=cand.slice(0,30);let result={ok:true,gate:'P1.5K7K_ORION_REVENUE_SOURCE_RECOVERY',version:'1.0-read-only',generatedAt:new Date().toISOString(),filesScanned:files.length,candidates:top,bestCandidate:top[0]||null,liveCampaignsMutated:false,nextAction:top[0]&&top[0].revenue.positive>=100?'USE_BEST_CANDIDATE_FOR_K7J_BASELINE_RESEGMENT':'NO_MEANINGFUL_ORION_REVENUE_SOURCE_FOUND'};fs.writeFileSync(path.join(OUT,'K7K_SUMMARY.json'),JSON.stringify(result,null,2));return result;}module.exports={run};