const fs = require("fs");
const path = require("path");

const ROOT = process.env.MILES_ROOT || path.resolve(__dirname, "..");

function pascal(name) {
  return String(name || "")
    .toLowerCase()
    .split(/[^a-z0-9]+/)
    .filter(Boolean)
    .map(s => s.charAt(0).toUpperCase() + s.slice(1))
    .join("");
}

class ConnectorBuilder {
  run(task = {}) {
    const rawName = task.name || task.connector || process.argv[3];

    if (!rawName) {
      return {
        ok: false,
        action: "BUILD_CONNECTOR",
        error: "Missing connector name. Example: node .\\BUILDER\\index.js BUILD_CONNECTOR ORION"
      };
    }

    const name = String(rawName).toUpperCase();
    const className = `${pascal(name)}Connector`;
    const folder = path.join(ROOT, "CONNECTORS", name);

    fs.mkdirSync(folder, { recursive: true });

    const connectorFile = path.join(folder, "connector.js");
    const readmeFile = path.join(folder, "README.md");

    const connectorCode = `class ${className} {
  async initialize() {
    return { ok: true, service: "${name}", status: "INITIALIZED" };
  }

  async healthCheck() {
    return {
      ok: true,
      service: "${name}",
      status: "OK",
      message: "${name} connector available",
      checkedAt: new Date().toISOString()
    };
  }

  async execute(task = {}) {
    return {
      ok: true,
      service: "${name}",
      status: "EXECUTED",
      task,
      message: "${name} connector received task"
    };
  }

  async shutdown() {
    return { ok: true, service: "${name}", status: "SHUTDOWN" };
  }
}

module.exports = new ${className}();
`;

    const readme = `# ${name} Connector

Generated by MILES Builder.

## Interface

- initialize()
- healthCheck()
- execute(task)
- shutdown()
`;

    if (!fs.existsSync(connectorFile)) {
      fs.writeFileSync(connectorFile, connectorCode);
    }

    if (!fs.existsSync(readmeFile)) {
      fs.writeFileSync(readmeFile, readme);
    }

    return {
      ok: true,
      action: "BUILD_CONNECTOR",
      connector: name,
      files: [
        path.relative(ROOT, connectorFile),
        path.relative(ROOT, readmeFile)
      ]
    };
  }
}

module.exports = new ConnectorBuilder();