'use strict';
const path = require('path');
const root = process.argv[2];
if (!root) throw new Error('MILES root argument is required.');
const plannerPath = path.join(root, 'SERVICES', 'CommandIntentPlannerService.js');
delete require.cache[require.resolve(plannerPath)];
const planner = require(plannerPath);
const mission = planner.plan({ command: 'Review the current business, identify the three highest-priority revenue opportunities, assign work to the appropriate departments, and produce an executive action plan.' });
if (mission.intent !== 'EXECUTIVE_MISSION') throw new Error(`Expected EXECUTIVE_MISSION, received ${mission.intent}`);
if (mission.action !== 'BUSINESS_EXECUTION') throw new Error(`Expected BUSINESS_EXECUTION, received ${mission.action}`);
if (!Array.isArray(mission.steps) || mission.steps.length !== 4) throw new Error('Expected four mission steps.');
const orion = planner.plan({ command: 'Audit ORION system health and produce an executive status report.' });
if (orion.provider !== 'ORION' || orion.action !== 'ORION_SUMMARY') throw new Error('ORION regression failed.');
const chat = planner.plan({ command: 'What can you do?' });
if (chat.intent !== 'CONVERSATION') throw new Error('Conversation regression failed.');
const revenue = planner.plan({ command: 'Own Instantly and expand outbound capacity using campaigns, mailboxes, segments, and verified leads.' });
if (revenue.intent !== 'REVENUE_OPERATIONS') throw new Error('Revenue mission regression failed.');
console.log('[BUILD143 TEST] PASSED');
console.log(JSON.stringify({ mission: { intent: mission.intent, workflow: mission.workflow, action: mission.action, steps: mission.steps.length }, orion: { provider: orion.provider, action: orion.action }, chat: chat.intent, revenue: revenue.intent }, null, 2));
