'use strict';
require('dotenv').config({quiet:true});
const fs=require('fs');
const path=require('path');
const {chromium}=require('playwright');
const ROOT=path.resolve(__dirname,'..');
const SPEC=path.join(ROOT,'DATA','production_specs','p2gc_reusable_demo_master.json');
const OUT_DIR=path.join(ROOT,'DATA','reusable_demo','assets');
const MANIFEST=path.join(ROOT,'DATA','reusable_demo','manifest.json');
const esc=s=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
const money=n=>'$'+(Number(n)>=1000000?(Number(n)/1000000).toFixed(1)+'M':Math.round(Number(n)/1000)+'K');
function write(file,data){fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,data,'utf8');}
function bars(vals,labels,x,y,w,h){const max=Math.max(...vals);const gap=24;const bw=(w-gap*(vals.length-1))/vals.length;return vals.map((v,i)=>{const bh=Math.max(10,h*v/max);const xx=x+i*(bw+gap),yy=y+h-bh;return `<rect x="${xx}" y="${yy}" width="${bw}" height="${bh}" rx="10" fill="#4f8cff"/><text x="${xx+bw/2}" y="${yy-12}" text-anchor="middle" font-size="26" fill="#eaf2ff">${money(v)}</text><text x="${xx+bw/2}" y="${y+h+34}" text-anchor="middle" font-size="22" fill="#9eb3cf">${esc(labels[i])}</text>`;}).join('');}
function card(x,y,w,h,title,value,sub=''){return `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="22" fill="#13243c" stroke="#29496f"/><text x="${x+28}" y="${y+38}" font-size="22" fill="#9eb3cf">${esc(title)}</text><text x="${x+28}" y="${y+88}" font-size="40" font-weight="700" fill="#ffffff">${esc(value)}</text>${sub?`<text x="${x+28}" y="${y+122}" font-size="20" fill="#9eb3cf">${esc(sub)}</text>`:''}`;}
function wrap(lines,x,y,size=32,dy=44,color='#eaf2ff',weight=500){return lines.map((t,i)=>`<text x="${x}" y="${y+i*dy}" font-size="${size}" font-weight="${weight}" fill="${color}">${esc(t)}</text>`).join('');}
function base(title,subtitle=''){return `<svg xmlns="http://www.w3.org/2000/svg" width="1920" height="1080"><rect width="1920" height="1080" fill="#07121f"/><rect x="80" y="64" width="1760" height="952" rx="34" fill="#0b1829" stroke="#1f3654"/><text x="120" y="132" font-size="48" font-weight="800" fill="#ffffff">${esc(title)}</text>${subtitle?`<text x="120" y="176" font-size="24" fill="#8fb5e8">${esc(subtitle)}</text>`:''}<text x="1670" y="1008" font-size="18" text-anchor="end" fill="#6884a8">P2GC • Federal Growth Review</text>`;}
function sceneSvg(scene,spec){const d=spec.fictionalCompany;let s=base(scene.title,scene.scene===3?`${d.name} — ${d.disclaimer}`:'');
 if(scene.scene===1){s+=wrap(['Why are you winning?','Why are you not winning?','Which revenue is exposed?','Are your vehicles producing?','Where should you expand next?','Which opportunities actually fit?'],140,270,36,74);s+=`<rect x="1110" y="270" width="620" height="420" rx="28" fill="#102842" stroke="#3d6fa8"/><text x="1420" y="390" text-anchor="middle" font-size="30" fill="#9eb3cf">FEDERAL DATA</text><text x="1420" y="485" text-anchor="middle" font-size="64" font-weight="800" fill="#ffffff">≠</text><text x="1420" y="585" text-anchor="middle" font-size="34" font-weight="700" fill="#7fc5ff">GROWTH CLARITY</text><text x="960" y="840" text-anchor="middle" font-size="42" font-weight="800" fill="#ffffff">More opportunities ≠ more growth</text>`;}
 if(scene.scene===2){const xs=[250,700,1150,1550];const labs=['Federal Data','P2GC Intelligence','Growth Diagnosis','Growth Pathway'];xs.forEach((x,i)=>{s+=`<rect x="${x-150}" y="380" width="300" height="150" rx="28" fill="#13243c" stroke="#335f90"/><text x="${x}" y="465" text-anchor="middle" font-size="28" font-weight="700" fill="#ffffff">${labs[i]}</text>`;if(i<3)s+=`<text x="${x+230}" y="468" font-size="46" fill="#6eb7ff">→</text>`;});s+=wrap(['POSITION','EXPOSURE','OPPORTUNITY'],500,700,34,0,'#8fb5e8',700);s+=`<text x="960" y="870" text-anchor="middle" font-size="34" font-weight="700" fill="#ffffff">Not another bid-notification service</text>`;}
 if(scene.scene===3){s+=card(120,240,350,150,'5-Year Federal Awards',money(d.fiveYearFederalAwards));s+=card(500,240,350,150,'Trailing 12-Month Revenue',money(d.trailingTwelveMonthRevenue));s+=card(880,240,350,150,'Prime / Sub',`${d.primeSharePct}% / ${d.subSharePct}%`);s+=card(1260,240,350,150,'Current Agencies',String(d.agencyRevenue.length));s+=bars(d.revenueTrend,['Y1','Y2','Y3','Y4','Y5'],140,520,920,260);s+=bars(d.agencyRevenue.map(x=>x.amount),d.agencyRevenue.map(x=>x.agency),1160,520,560,260);s+=`<text x="960" y="910" text-anchor="middle" font-size="32" font-weight="700" fill="#ffffff">Revenue tells us what happened. Buying patterns help explain why.</text>`;}
 if(scene.scene===4){s+=card(140,280,540,220,'GSA MAS','ACTIVE','SINs 54151S • 541611');s+=card(760,280,460,220,'Total Federal Revenue',money(d.trailingTwelveMonthRevenue));s+=card(1280,280,460,220,'GSA Sales',money(d.gsaTrailingSales),'Trailing 12 months');const pct=Math.round(d.gsaTrailingSales/d.trailingTwelveMonthRevenue*100);s+=`<rect x="300" y="640" width="1320" height="46" rx="23" fill="#1c2d44"/><rect x="300" y="640" width="${1320*pct/100}" height="46" rx="23" fill="#4f8cff"/><text x="960" y="735" text-anchor="middle" font-size="36" font-weight="800" fill="#ffffff">Potential underutilization • only ${pct}% of revenue flowing through GSA</text><text x="960" y="830" text-anchor="middle" font-size="31" fill="#8fb5e8">A vehicle creates access. A strategy creates utilization.</text>`;}
 if(scene.scene===5){s+=card(140,260,620,180,'Current Federal Revenue',money(d.trailingTwelveMonthRevenue));s+=card(1160,260,620,180,'Potentially Exposed ≤18 Months',money(d.revenueExposed18Months));s+=`<rect x="250" y="560" width="1420" height="70" rx="35" fill="#1e314a"/><rect x="250" y="560" width="${1420*d.revenueExposed18Months/d.trailingTwelveMonthRevenue}" height="70" rx="35" fill="#ffb45c"/><text x="960" y="705" text-anchor="middle" font-size="36" font-weight="800" fill="#ffffff">Protecting revenue can be as important as finding new revenue.</text>`;d.exposureItems.forEach((it,i)=>{s+=card(230+i*510,790,450,140,it.label,money(it.amount),it.reason);});}
 if(scene.scene===6){const labs=['Active Procurements','Recompetes','Forecasts','Agency Patterns','Vehicles','Prime','Sub / Teaming','VA / VISN','Adjacent NAICS'];labs.forEach((t,i)=>{const col=i%3,row=Math.floor(i/3);s+=`<rect x="170+0" y="0" width="0" height="0"/>`;s+=card(160+col*540,240+row*170,460,130,t,'✓');});s+=`<rect x="1280" y="800" width="420" height="140" rx="28" fill="#133456" stroke="#4f8cff"/><text x="1490" y="858" text-anchor="middle" font-size="28" fill="#9eb3cf">QUALIFIED PATHS</text><text x="1490" y="918" text-anchor="middle" font-size="58" font-weight="800" fill="#ffffff">${d.qualifiedPaths}</text><text x="760" y="930" text-anchor="middle" font-size="30" font-weight="700" fill="#ffffff">The goal is to identify the right opportunities for your company.</text>`;}
 if(scene.scene===7){const rows=spec.competitors;rows.forEach((r,i)=>{const y=250+i*150;const width=700*r.annualAwards/7100000;s+=`<text x="150" y="${y+40}" font-size="26" fill="#ffffff">${esc(r.name)}</text><rect x="580" y="${y}" width="700" height="48" rx="12" fill="#1e314a"/><rect x="580" y="${y}" width="${width}" height="48" rx="12" fill="#4f8cff"/><text x="1310" y="${y+36}" font-size="24" fill="#ffffff">${money(r.annualAwards)}</text><text x="1500" y="${y+36}" font-size="24" fill="#9eb3cf">${r.agencies} agencies • ${r.primeSharePct}% prime</text>`;});s+=wrap(['Where is the gap forming?','Broader agency reach • Higher prime position • Stronger vehicle utilization'],180,900,34,54,'#ffffff',700);}
 if(scene.scene===8){const gs=['GSA underutilized','50% of revenue in one agency','$2.7M entering exposure window','Limited adjacent-buyer reach','Prime position can improve'];gs.forEach((g,i)=>{const a=i*72-144,rad=a*Math.PI/180,cx=960+360*Math.cos(rad),cy=560+250*Math.sin(rad);s+=`<rect x="${cx-220}" y="${cy-62}" width="440" height="124" rx="24" fill="#13243c" stroke="#335f90"/><text x="${cx}" y="${cy+8}" text-anchor="middle" font-size="24" fill="#ffffff">${esc(g)}</text><line x1="960" y1="560" x2="${cx}" y2="${cy}" stroke="#2f659c" stroke-width="4"/>`;});s+=`<circle cx="960" cy="560" r="145" fill="#183d63" stroke="#5ea8ef" stroke-width="5"/><text x="960" y="550" text-anchor="middle" font-size="30" font-weight="700" fill="#ffffff">GROWTH</text><text x="960" y="592" text-anchor="middle" font-size="30" font-weight="700" fill="#ffffff">DIAGNOSIS</text><text x="960" y="930" text-anchor="middle" font-size="31" fill="#8fb5e8">Data becomes useful when the findings connect.</text>`;}
 if(scene.scene===9){const cols=[['PROTECT','Existing revenue','Recompetes','Key buyers'],['EXPAND','Adjacent agencies','Existing vehicles','Prime position'],['CAPTURE','Best-fit opportunities','Teaming paths','Priority pursuits']];cols.forEach((c,i)=>{const x=150+i*590;s+=`<rect x="${x}" y="300" width="500" height="420" rx="32" fill="#13243c" stroke="#335f90"/><text x="${x+250}" y="390" text-anchor="middle" font-size="44" font-weight="800" fill="#ffffff">${c[0]}</text>${wrap(c.slice(1),x+70,490,28,62,'#9eb3cf',500)}${i<2?`<text x="${x+535}" y="525" font-size="60" fill="#6eb7ff">→</text>`:''}`;});s+=`<text x="960" y="860" text-anchor="middle" font-size="38" font-weight="800" fill="#ffffff">Sequence matters.</text>`;}
 if(scene.scene===10){const items=['YOUR COMPANY','Federal Intelligence','Growth Diagnosis','Recommended Pathway','Execution'];items.forEach((t,i)=>{const x=210+i*355;s+=`<rect x="${x-140}" y="410" width="280" height="150" rx="25" fill="#13243c" stroke="#335f90"/><text x="${x}" y="495" text-anchor="middle" font-size="25" font-weight="700" fill="#ffffff">${esc(t)}</text>${i<4?`<text x="${x+160}" y="500" font-size="44" fill="#6eb7ff">→</text>`:''}`;});s+=wrap(['The demonstration shows how the analysis works.','Your engagement applies that process to your actual company, priorities, opportunities and execution path.'],200,770,30,52,'#ffffff',700);}
 if(scene.scene===11){s+=`<text x="960" y="330" text-anchor="middle" font-size="48" font-weight="800" fill="#ffffff">Want to know what this analysis reveals about your company?</text><text x="960" y="450" text-anchor="middle" font-size="58" font-weight="800" fill="#7fc5ff">Review Your Federal Position With Kevin</text><text x="960" y="525" text-anchor="middle" font-size="34" fill="#ffffff">15–20 Minute Discussion</text><rect x="665" y="650" width="590" height="110" rx="28" fill="#2a79d6"/><text x="960" y="720" text-anchor="middle" font-size="34" font-weight="800" fill="#ffffff">REQUEST YOUR REVIEW</text><text x="960" y="835" text-anchor="middle" font-size="28" fill="#9eb3cf">No generic sales presentation. We’ll discuss what we’re seeing in your actual federal position.</text><text x="960" y="925" text-anchor="middle" font-size="30" font-weight="700" fill="#ffffff">pathways2gc.com</text>`;}
 return s+'</svg>';}
async function main(){const spec=JSON.parse(fs.readFileSync(SPEC,'utf8'));fs.mkdirSync(OUT_DIR,{recursive:true});const browser=await chromium.launch({headless:true,channel:'chrome'});const page=await browser.newPage({viewport:{width:1920,height:1080}});const assets=[];for(const scene of spec.scenes){const svg=sceneSvg(scene,spec);const svgFile=path.join(OUT_DIR,`scene_${String(scene.scene).padStart(2,'0')}.svg`);const pngFile=path.join(OUT_DIR,`scene_${String(scene.scene).padStart(2,'0')}.png`);write(svgFile,svg);await page.goto('data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg));await page.screenshot({path:pngFile,fullPage:true});assets.push({scene:scene.scene,title:scene.title,svgFile,pngFile,durationSeconds:scene.durationSeconds,avatarSeconds:scene.avatarSeconds,narration:scene.narration,screen:scene.screen,visual:scene.visual});}await browser.close();const manifest={ok:true,status:'ASSETS_READY',createdAt:new Date().toISOString(),targetRuntimeSeconds:spec.format.targetRuntimeSeconds,assetCount:assets.length,assets};write(MANIFEST,JSON.stringify(manifest,null,2));console.log(JSON.stringify({ok:true,status:'ASSETS_READY',assetCount:assets.length,manifest:MANIFEST,targetRuntimeSeconds:spec.format.targetRuntimeSeconds},null,2));}
if(require.main===module)main().catch(e=>{console.error(e.stack||e);process.exitCode=2;});
