'use strict';
const fs=require('fs');
const path=require('path');
const zlib=require('zlib');
const readline=require('readline');

function csvHeader(line){const out=[];let cur='',q=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(q&&line[i+1]==='"'){cur+='"';i++;}else q=!q;}else if(ch===','&&!q){out.push(cur);cur='';}else cur+=ch;}out.push(cur);return out.map(x=>x.trim());}
async function firstLineFromStream(stream){const rl=readline.createInterface({input:stream,crlfDelay:Infinity});for await(const line of rl){rl.close();return line;}return '';}
async function inspectZip(zipPath){const yauzl=require('yauzl');return new Promise((resolve,reject)=>{yauzl.open(zipPath,{lazyEntries:true},(err,zip)=>{if(err)return reject(err);const entries=[];zip.readEntry();zip.on('entry',e=>{entries.push({fileName:e.fileName,uncompressedSize:e.uncompressedSize,compressedSize:e.compressedSize});if(/\.csv$/i.test(e.fileName)){zip.openReadStream(e,async(err2,s)=>{if(err2)return reject(err2);try{const line=await firstLineFromStream(s);resolve({entries,csvEntry:e.fileName,header:csvHeader(line),sampleHeaderLine:line.slice(0,10000)});}catch(x){reject(x);}finally{try{zip.close();}catch{}}});}else zip.readEntry();});zip.on('end',()=>resolve({entries,csvEntry:null,header:[]}));});});}
async function inspectCsv(csvPath){const line=await firstLineFromStream(fs.createReadStream(csvPath));return{fileName:path.basename(csvPath),bytes:fs.statSync(csvPath).size,header:csvHeader(line),sampleHeaderLine:line.slice(0,10000)};}
async function main(){const root=path.resolve(process.argv[2]||process.env.MILES_ROOT||path.resolve(__dirname,'..'));const dir=path.join(root,'DATA','orion_refresh','sam_bulk_staging');const files=fs.existsSync(dir)?fs.readdirSync(dir):[];const entity=files.filter(x=>/^SAM_PUBLIC_UTF-8_MONTHLY_V2_\d{8}\.ZIP$/i.test(x)).sort().reverse()[0];const opp=files.includes('ContractOpportunitiesFullCSV.csv')?'ContractOpportunitiesFullCSV.csv':null;if(!entity||!opp)throw new Error('SAM_BULK_INPUTS_MISSING');const e=await inspectZip(path.join(dir,entity));const o=await inspectCsv(path.join(dir,opp));const result={ok:true,service:'SAM_BULK_SCHEMA_AUDIT',generatedAt:new Date().toISOString(),entity:{fileName:entity,bytes:fs.statSync(path.join(dir,entity)).size,...e},opportunities:o,nextStep:'BUILD_QUALIFIED_SAM_COMPANY_UNIVERSE_WITH_EMAIL_ENRICHMENT_AND_GLOBAL_DEDUPE',safety:{readOnly:true,filesChanged:0,productionDatabaseModified:false,credentialsRead:false}};const report=path.join(root,'DATA','orion_refresh','latest_sam_bulk_schema_audit.json');fs.writeFileSync(report,JSON.stringify(result,null,2),'utf8');console.log(JSON.stringify(result,null,2));}
main().catch(e=>{console.error(JSON.stringify({ok:false,service:'SAM_BULK_SCHEMA_AUDIT',error:e.message},null,2));process.exitCode=2;});
