'use strict';
const fs=require('fs');
const path=require('path');
const readline=require('readline');
const zlib=require('zlib');

function parseDelimitedHeader(line){const text=String(line||'');const pipeCount=(text.match(/\|/g)||[]).length;const tabCount=(text.match(/\t/g)||[]).length;const commaCount=(text.match(/,/g)||[]).length;const delimiter=pipeCount>=tabCount&&pipeCount>=commaCount?'|':tabCount>=commaCount?'\t':',';if(delimiter!==',')return{delimiter,header:text.split(delimiter).map(x=>x.replace(/^"|"$/g,'').trim())};const out=[];let cur='',q=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(q&&text[i+1]==='"'){cur+='"';i++;}else q=!q;}else if(ch===','&&!q){out.push(cur);cur='';}else cur+=ch;}out.push(cur);return{delimiter:',',header:out.map(x=>x.trim())};}
async function firstLineFromStream(stream){const rl=readline.createInterface({input:stream,crlfDelay:Infinity});for await(const line of rl){rl.close();return line;}return '';}
function findEocd(fd,size){const len=Math.min(size,65557);const buf=Buffer.alloc(len);fs.readSync(fd,buf,0,len,size-len);for(let i=len-22;i>=0;i--){if(buf.readUInt32LE(i)===0x06054b50)return{buf,offset:size-len+i};}throw new Error('ZIP_EOCD_NOT_FOUND');}
function readCentralDirectory(zipPath){const fd=fs.openSync(zipPath,'r');try{const size=fs.fstatSync(fd).size;const {buf,offset}=findEocd(fd,size);const local=offset-(size-buf.length);const total=buf.readUInt16LE(local+10);const centralSize=buf.readUInt32LE(local+12);const centralOffset=buf.readUInt32LE(local+16);if(total===0xffff||centralSize===0xffffffff||centralOffset===0xffffffff)throw new Error('ZIP64_NOT_SUPPORTED_BY_LIGHTWEIGHT_AUDIT');const cd=Buffer.alloc(centralSize);fs.readSync(fd,cd,0,centralSize,centralOffset);const entries=[];let p=0;for(let n=0;n<total&&p+46<=cd.length;n++){if(cd.readUInt32LE(p)!==0x02014b50)throw new Error(`ZIP_CENTRAL_SIGNATURE_INVALID:${p}`);const method=cd.readUInt16LE(p+10);const compressedSize=cd.readUInt32LE(p+20);const uncompressedSize=cd.readUInt32LE(p+24);const nameLen=cd.readUInt16LE(p+28);const extraLen=cd.readUInt16LE(p+30);const commentLen=cd.readUInt16LE(p+32);const localHeaderOffset=cd.readUInt32LE(p+42);const fileName=cd.subarray(p+46,p+46+nameLen).toString('utf8');entries.push({fileName,compressedSize,uncompressedSize,method,localHeaderOffset});p+=46+nameLen+extraLen+commentLen;}return entries;}finally{fs.closeSync(fd);}}
function firstLineFromZipEntry(zipPath,entry){return new Promise((resolve,reject)=>{const fd=fs.openSync(zipPath,'r');const h=Buffer.alloc(30);try{fs.readSync(fd,h,0,30,entry.localHeaderOffset);}finally{fs.closeSync(fd);}if(h.readUInt32LE(0)!==0x04034b50)return reject(new Error('ZIP_LOCAL_HEADER_INVALID'));const nameLen=h.readUInt16LE(26);const extraLen=h.readUInt16LE(28);const start=entry.localHeaderOffset+30+nameLen+extraLen;const end=start+entry.compressedSize-1;const raw=fs.createReadStream(zipPath,{start,end});let stream;if(entry.method===0)stream=raw;else if(entry.method===8){stream=zlib.createInflateRaw();raw.pipe(stream);}else return reject(new Error(`ZIP_COMPRESSION_METHOD_UNSUPPORTED:${entry.method}`));let text='',done=false;const finish=(err,line)=>{if(done)return;done=true;try{raw.destroy();}catch{}try{if(stream!==raw)stream.destroy();}catch{}if(err)reject(err);else resolve(line);};stream.setEncoding('utf8');stream.on('data',chunk=>{text+=chunk;const idx=text.search(/\r?\n/);if(idx>=0)return finish(null,text.slice(0,idx));if(text.length>1024*1024)return finish(new Error('ZIP_HEADER_LINE_TOO_LARGE'));});stream.on('end',()=>finish(null,text));stream.on('error',e=>finish(e));raw.on('error',e=>finish(e));});}
async function inspectZipNode(zipPath){const entries=readCentralDirectory(zipPath);const target=entries.filter(e=>e.uncompressedSize>0&&!/\/$/.test(e.fileName)).sort((a,b)=>b.uncompressedSize-a.uncompressedSize)[0]||null;if(!target)throw new Error('ZIP_HAS_NO_DATA_ENTRIES');const sample=await firstLineFromZipEntry(zipPath,target);const parsed=parseDelimitedHeader(sample);return{entries:entries.map(e=>({fileName:e.fileName,uncompressedSize:e.uncompressedSize,compressedSize:e.compressedSize,method:e.method})),selectedEntry:target.fileName,delimiter:parsed.delimiter,header:parsed.header,sampleHeaderLine:sample.slice(0,12000)};}
async function inspectCsv(csvPath){const line=await firstLineFromStream(fs.createReadStream(csvPath));const parsed=parseDelimitedHeader(line);return{fileName:path.basename(csvPath),bytes:fs.statSync(csvPath).size,delimiter:parsed.delimiter,header:parsed.header,sampleHeaderLine:line.slice(0,12000)};}
async function main(){const root=path.resolve(process.argv[2]||process.env.MILES_ROOT||path.resolve(__dirname,'..'));const dir=path.join(root,'DATA','orion_refresh','sam_bulk_staging');const files=fs.existsSync(dir)?fs.readdirSync(dir):[];const entity=files.filter(x=>/^SAM_PUBLIC_UTF-8_MONTHLY_V2_\d{8}\.ZIP$/i.test(x)).sort().reverse()[0];const opp=files.includes('ContractOpportunitiesFullCSV.csv')?'ContractOpportunitiesFullCSV.csv':null;if(!entity||!opp)throw new Error('SAM_BULK_INPUTS_MISSING');const e=await inspectZipNode(path.join(dir,entity));const o=await inspectCsv(path.join(dir,opp));const result={ok:true,service:'SAM_BULK_SCHEMA_AUDIT',generatedAt:new Date().toISOString(),entity:{fileName:entity,bytes:fs.statSync(path.join(dir,entity)).size,...e},opportunities:o,nextStep:'BUILD_QUALIFIED_SAM_COMPANY_UNIVERSE_WITH_EMAIL_ENRICHMENT_AND_GLOBAL_DEDUPE',safety:{readOnly:true,filesChanged:0,productionDatabaseModified:false,credentialsRead:false,externalNodeZipDependency:false,archiveExtracted:false,nativeZipParser:true}};const report=path.join(root,'DATA','orion_refresh','latest_sam_bulk_schema_audit.json');fs.writeFileSync(report,JSON.stringify(result,null,2),'utf8');console.log(JSON.stringify(result,null,2));}
main().catch(e=>{console.error(JSON.stringify({ok:false,service:'SAM_BULK_SCHEMA_AUDIT',error:e.message},null,2));process.exitCode=2;});
