'use strict';
const fs=require('fs');
const path=require('path');
const readline=require('readline');
const {spawnSync}=require('child_process');

function parseDelimitedHeader(line){const text=String(line||'');const pipeCount=(text.match(/\|/g)||[]).length;const tabCount=(text.match(/\t/g)||[]).length;const commaCount=(text.match(/,/g)||[]).length;const delimiter=pipeCount>=tabCount&&pipeCount>=commaCount?'|':tabCount>=commaCount?'\t':',';if(delimiter!==',')return{delimiter,header:text.split(delimiter).map(x=>x.replace(/^"|"$/g,'').trim())};const out=[];let cur='',q=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(q&&text[i+1]==='"'){cur+='"';i++;}else q=!q;}else if(ch===','&&!q){out.push(cur);cur='';}else cur+=ch;}out.push(cur);return{delimiter:',',header:out.map(x=>x.trim())};}
async function firstLineFromStream(stream){const rl=readline.createInterface({input:stream,crlfDelay:Infinity});for await(const line of rl){rl.close();return line;}return '';}
function inspectZipWindows(zipPath){const ps=`Add-Type -AssemblyName System.IO.Compression.FileSystem; $z=[IO.Compression.ZipFile]::OpenRead($args[0]); try { $entries=@(); foreach($e in $z.Entries){ $entries += ($e.FullName + '|' + $e.Length + '|' + $e.CompressedLength) }; $target=$z.Entries | Where-Object { $_.Length -gt 0 -and $_.FullName -notmatch '/$' } | Sort-Object Length -Descending | Select-Object -First 1; $line=''; if($target){ $s=$target.Open(); try { $r=New-Object IO.StreamReader($s,[Text.Encoding]::UTF8,$true,65536,$false); try{$line=$r.ReadLine()} finally{$r.Dispose()} } finally{$s.Dispose()} }; [pscustomobject]@{entryLines=$entries;selectedEntry=if($target){$target.FullName}else{$null};sampleHeaderLine=$line} | ConvertTo-Json -Depth 4 -Compress } finally { $z.Dispose() }`;
 const r=spawnSync('powershell.exe',['-NoProfile','-NonInteractive','-Command',ps,zipPath],{encoding:'utf8',windowsHide:true,maxBuffer:16*1024*1024});if(r.status!==0)throw new Error(`WINDOWS_ZIP_INSPECTION_FAILED:${String(r.stderr||'').trim()}`);const parsed=JSON.parse(String(r.stdout||'').trim());const raw=Array.isArray(parsed.entryLines)?parsed.entryLines:(parsed.entryLines?[parsed.entryLines]:[]);const entries=raw.map(s=>{const parts=String(s).split('|');return{fileName:parts[0]||null,uncompressedSize:Number(parts[1]||0),compressedSize:Number(parts[2]||0)};});const sample=String(parsed.sampleHeaderLine||'');const parsedHeader=parseDelimitedHeader(sample);return{entries,selectedEntry:parsed.selectedEntry||null,delimiter:parsedHeader.delimiter,header:parsedHeader.header,sampleHeaderLine:sample.slice(0,12000)};}
async function inspectCsv(csvPath){const line=await firstLineFromStream(fs.createReadStream(csvPath));const parsed=parseDelimitedHeader(line);return{fileName:path.basename(csvPath),bytes:fs.statSync(csvPath).size,delimiter:parsed.delimiter,header:parsed.header,sampleHeaderLine:line.slice(0,12000)};}
async function main(){const root=path.resolve(process.argv[2]||process.env.MILES_ROOT||path.resolve(__dirname,'..'));const dir=path.join(root,'DATA','orion_refresh','sam_bulk_staging');const files=fs.existsSync(dir)?fs.readdirSync(dir):[];const entity=files.filter(x=>/^SAM_PUBLIC_UTF-8_MONTHLY_V2_\d{8}\.ZIP$/i.test(x)).sort().reverse()[0];const opp=files.includes('ContractOpportunitiesFullCSV.csv')?'ContractOpportunitiesFullCSV.csv':null;if(!entity||!opp)throw new Error('SAM_BULK_INPUTS_MISSING');if(process.platform!=='win32')throw new Error('SAM_BULK_SCHEMA_AUDIT_REQUIRES_WINDOWS_RUNTIME');const e=inspectZipWindows(path.join(dir,entity));const o=await inspectCsv(path.join(dir,opp));const result={ok:true,service:'SAM_BULK_SCHEMA_AUDIT',generatedAt:new Date().toISOString(),entity:{fileName:entity,bytes:fs.statSync(path.join(dir,entity)).size,...e},opportunities:o,nextStep:'BUILD_QUALIFIED_SAM_COMPANY_UNIVERSE_WITH_EMAIL_ENRICHMENT_AND_GLOBAL_DEDUPE',safety:{readOnly:true,filesChanged:0,productionDatabaseModified:false,credentialsRead:false,externalNodeZipDependency:false,archiveExtracted:false}};const report=path.join(root,'DATA','orion_refresh','latest_sam_bulk_schema_audit.json');fs.writeFileSync(report,JSON.stringify(result,null,2),'utf8');console.log(JSON.stringify(result,null,2));}
main().catch(e=>{console.error(JSON.stringify({ok:false,service:'SAM_BULK_SCHEMA_AUDIT',error:e.message},null,2));process.exitCode=2;});
