'use strict';

const fs=require('fs');
const path=require('path');
const {spawnSync}=require('child_process');
const {chromium}=require('playwright');

const ROOT=path.resolve(__dirname,'..');
const MASTER=path.join(ROOT,'DATA','production_specs','p2gc_reusable_demo_master.json');
const WORK=path.join(ROOT,'DATA','reusable_demo','v4');
const AUDIO=path.join(WORK,'audio');
const FRAMES=path.join(WORK,'frames');
const SEGMENTS=path.join(WORK,'segments');
const EXPORT_DIR=path.join(ROOT,'DATA','reusable_demo','exports');
const OUTPUT=path.join(EXPORT_DIR,'P2GC_Federal_Growth_Review_Demo_V4.mp4');
const STATUS=path.join(ROOT,'DATA','operational_acceptance','latest_p2gc_v4_render.json');
const FFMPEG=path.join(ROOT,'TOOLS','ffmpeg','bin','ffmpeg.exe');
const FFPROBE=path.join(ROOT,'TOOLS','ffmpeg','bin','ffprobe.exe');
const VOICE='en-US-GuyNeural';
const TRANSITION=0.6; // always well under CEO max 2s between slides

const now=()=>new Date().toISOString();
const clean=v=>String(v==null?'':v).trim();
const esc=s=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
function ensure(p){fs.mkdirSync(p,{recursive:true});}
function writeStatus(s){ensure(path.dirname(STATUS));s.updatedAt=now();fs.writeFileSync(STATUS,JSON.stringify(s,null,2),'utf8');}
function run(exe,args,opts={}){const r=spawnSync(exe,args,{cwd:ROOT,encoding:'utf8',windowsHide:true,timeout:opts.timeout||900000,maxBuffer:16*1024*1024});return{ok:r.status===0,code:r.status,stdout:r.stdout||'',stderr:r.stderr||'',error:r.error?r.error.message:null};}
function py(){for(const p of ['py.exe','python.exe','python']){const r=run(p,['--version'],{timeout:10000});if(r.ok)return p;}return null;}
function probeDuration(file){const r=run(FFPROBE,['-v','error','-show_entries','format=duration','-of','default=noprint_wrappers=1:nokey=1',file],{timeout:30000});if(!r.ok)throw new Error('FFPROBE_DURATION_FAILED:'+clean(r.stderr||r.error));const n=Number(clean(r.stdout));if(!Number.isFinite(n)||n<=0)throw new Error('INVALID_MEDIA_DURATION:'+file);return n;}
function ensureEdgeTts(status){const p=py();if(!p)throw new Error('PYTHON_NOT_FOUND_FOR_EDGE_TTS');let r=run(p,['-m','edge_tts','--help'],{timeout:30000});if(!r.ok){status.lastLogActivity={at:now(),event:'Provisioning zero-cost edge-tts neural voice package'};writeStatus(status);r=run(p,['-m','pip','install','--user','edge-tts'],{timeout:300000});if(!r.ok)throw new Error('EDGE_TTS_INSTALL_FAILED:'+clean(r.stderr||r.error).slice(-2500));r=run(p,['-m','edge_tts','--help'],{timeout:30000});if(!r.ok)throw new Error('EDGE_TTS_VERIFY_FAILED:'+clean(r.stderr||r.error).slice(-1500));}return p;}
function tts(pyExe,scene,status){const out=path.join(AUDIO,`scene_${String(scene.scene).padStart(2,'0')}.mp3`);if(fs.existsSync(out)&&fs.statSync(out).size>10000)return{file:out,duration:probeDuration(out)};const rate='+0%';const r=run(pyExe,['-m','edge_tts','--voice',VOICE,'--rate',rate,'--text',scene.narration,'--write-media',out],{timeout:300000});if(!r.ok)throw new Error(`SCENE_${scene.scene}_NEURAL_TTS_FAILED:${clean(r.stderr||r.error).slice(-2500)}`);const duration=probeDuration(out);status.lastSuccessfulStep=`scene_${scene.scene}_neural_audio_created`;status.currentScene=scene.scene;status.lastLogActivity={at:now(),event:`Natural neural narration created for scene ${scene.scene} (${duration.toFixed(2)}s)`};writeStatus(status);return{file:out,duration};}
function groupScreen(scene){const items=(scene.screen||[]).filter(Boolean).filter(x=>clean(x).toLowerCase()!==clean(scene.title).toLowerCase());const groups=[];for(let i=0;i<items.length;i+=3)groups.push(items.slice(i,i+3));return groups.length?groups:[[scene.title]];}
function svgFor(scene,group,stage,total){const y0=270;const cards=group.map((t,i)=>{const y=y0+i*175;const big=/\$|\/100|%|QUALIFIED|PROTECT|EXPAND|CAPTURE|YOUR COMPANY|REQUEST YOUR/i.test(t);return `<g><rect x="170" y="${y}" width="1580" height="128" rx="24" fill="#ffffff" stroke="#d9e2ef" stroke-width="2"/><rect x="170" y="${y}" width="12" height="128" rx="6" fill="#2f6fed"/><text x="225" y="${y+77}" font-family="Arial" font-size="${big?40:32}" font-weight="${big?800:700}" fill="#13233a">${esc(t)}</text></g>`;}).join('');const q=stage===total-1&&scene.selfDiagnosis?`<rect x="170" y="865" width="1580" height="92" rx="24" fill="#eef5ff" stroke="#bfd4f7"/><text x="960" y="922" text-anchor="middle" font-family="Arial" font-size="26" font-weight="700" fill="#214e91">${esc(scene.selfDiagnosis)}</text>`:'';return `<svg xmlns="http://www.w3.org/2000/svg" width="1920" height="1080"><rect width="1920" height="1080" fill="#f6f8fb"/><rect x="0" y="0" width="1920" height="18" fill="#2f6fed"/><text x="170" y="120" font-family="Arial" font-size="48" font-weight="800" fill="#10233f">${esc(scene.title)}</text><text x="170" y="168" font-family="Arial" font-size="22" font-weight="700" fill="#61738b">P2GC FEDERAL GROWTH REVIEW • FICTIONAL DEMONSTRATION</text><line x1="170" y1="205" x2="1750" y2="205" stroke="#d9e2ef" stroke-width="2"/>${cards}${q}<text x="1750" y="1020" text-anchor="end" font-family="Arial" font-size="18" fill="#7b8da6">Pathways 2 Government Contracting</text></svg>`;}
async function renderFrames(master,status){ensure(FRAMES);const browser=await chromium.launch({headless:true,channel:'chrome'});const page=await browser.newPage({viewport:{width:1920,height:1080}});try{for(const scene of master.scenes){const groups=groupScreen(scene);for(let i=0;i<groups.length;i++){const svg=svgFor(scene,groups[i],i,groups.length);await page.setContent(`<html><body style="margin:0;background:#f6f8fb">${svg}</body></html>`,{waitUntil:'domcontentloaded',timeout:120000});const out=path.join(FRAMES,`scene_${String(scene.scene).padStart(2,'0')}_stage_${String(i+1).padStart(2,'0')}.png`);await page.screenshot({path:out,clip:{x:0,y:0,width:1920,height:1080},timeout:120000});}status.lastSuccessfulStep=`scene_${scene.scene}_light_frames_created`;status.currentScene=scene.scene;status.lastLogActivity={at:now(),event:`Light progressive frames created for scene ${scene.scene}`};writeStatus(status);}}finally{await browser.close();}}
function buildScene(scene,audio,status){const groups=groupScreen(scene);const target=Math.max(Number(scene.durationSeconds)||0,audio.duration+0.75);const per=target/groups.length;const parts=[];for(let i=0;i<groups.length;i++){const frame=path.join(FRAMES,`scene_${String(scene.scene).padStart(2,'0')}_stage_${String(i+1).padStart(2,'0')}.png`);const seg=path.join(SEGMENTS,`s${String(scene.scene).padStart(2,'0')}_${String(i+1).padStart(2,'0')}.mp4`);const fadeOut=Math.max(0,per-TRANSITION);const r=run(FFMPEG,['-y','-loop','1','-framerate','30','-i',frame,'-t',per.toFixed(3),'-vf',`scale=1920:1080,format=yuv420p,fade=t=in:st=0:d=${TRANSITION},fade=t=out:st=${fadeOut.toFixed(3)}:d=${TRANSITION}`,'-r','30','-c:v','libx264','-preset','medium','-crf','20','-an',seg],{timeout:600000});if(!r.ok)throw new Error(`SCENE_${scene.scene}_STAGE_${i+1}_VIDEO_FAILED:${clean(r.stderr||r.error).slice(-2500)}`);parts.push(seg);}const list=path.join(SEGMENTS,`scene_${String(scene.scene).padStart(2,'0')}_list.txt`);fs.writeFileSync(list,parts.map(f=>`file '${f.replace(/'/g,"'\\''")}'`).join('\r\n'),'utf8');const visual=path.join(SEGMENTS,`scene_${String(scene.scene).padStart(2,'0')}_visual.mp4`);let r=run(FFMPEG,['-y','-f','concat','-safe','0','-i',list,'-c','copy',visual],{timeout:600000});if(!r.ok)throw new Error(`SCENE_${scene.scene}_VISUAL_CONCAT_FAILED:${clean(r.stderr||r.error).slice(-2500)}`);const final=path.join(SEGMENTS,`scene_${String(scene.scene).padStart(2,'0')}.mp4`);r=run(FFMPEG,['-y','-i',visual,'-i',audio.file,'-filter_complex',`[1:a]apad=pad_dur=${Math.max(0,target-audio.duration).toFixed(3)},atrim=0:${target.toFixed(3)}[a]`,'-map','0:v:0','-map','[a]','-t',target.toFixed(3),'-r','30','-c:v','copy','-c:a','aac','-b:a','192k','-ar','48000','-ac','2','-movflags','+faststart',final],{timeout:600000});if(!r.ok)throw new Error(`SCENE_${scene.scene}_MUX_FAILED:${clean(r.stderr||r.error).slice(-2500)}`);status.lastSuccessfulStep=`scene_${scene.scene}_v4_composed`;status.lastLogActivity={at:now(),event:`Scene ${scene.scene} composed with progressive reveals; transition ${TRANSITION}s`};writeStatus(status);return{file:final,duration:target};}
function concatScenes(files){const list=path.join(SEGMENTS,'final_scene_list.txt');fs.writeFileSync(list,files.map(f=>`file '${f.replace(/'/g,"'\\''")}'`).join('\r\n'),'utf8');let r=run(FFMPEG,['-y','-f','concat','-safe','0','-i',list,'-c','copy',OUTPUT],{timeout:1200000});if(!r.ok)r=run(FFMPEG,['-y','-f','concat','-safe','0','-i',list,'-r','30','-c:v','libx264','-preset','medium','-crf','20','-c:a','aac','-b:a','192k','-movflags','+faststart',OUTPUT],{timeout:1200000});if(!r.ok)throw new Error('FINAL_V4_CONCAT_FAILED:'+clean(r.stderr||r.error).slice(-3000));}
async function main(){const status={ok:false,phase:'V4_PRESENTATION_RENDER',processState:'RUNNING',currentStage:'setup',currentScene:1,startedAt:now(),outputFile:OUTPUT,voice:VOICE,transitionSeconds:TRANSITION,error:null};writeStatus(status);try{if(!fs.existsSync(FFMPEG)||!fs.existsSync(FFPROBE))throw new Error('PROJECT_FFMPEG_OR_FFPROBE_MISSING');ensure(AUDIO);ensure(FRAMES);ensure(SEGMENTS);ensure(EXPORT_DIR);const master=JSON.parse(fs.readFileSync(MASTER,'utf8').replace(/^\uFEFF/,''));if(!Array.isArray(master.scenes)||master.scenes.length!==11)throw new Error('APPROVED_SCENE_COUNT_INVALID');const p=ensureEdgeTts(status);status.currentStage='neural_tts';const audio=[];for(const scene of master.scenes)audio.push(tts(p,scene,status));status.currentStage='light_progressive_assets';await renderFrames(master,status);status.currentStage='composition';const scenes=[];let total=0;for(let i=0;i<master.scenes.length;i++){const c=buildScene(master.scenes[i],audio[i],status);scenes.push(c.file);total+=c.duration;}status.currentStage='export';status.lastLogActivity={at:now(),event:'Concatenating 11 V4 scenes'};writeStatus(status);concatScenes(scenes);if(!fs.existsSync(OUTPUT)||fs.statSync(OUTPUT).size<1000000)throw new Error('FINAL_V4_MP4_MISSING_OR_TOO_SMALL');const actual=probeDuration(OUTPUT);status.ok=true;status.processState='COMPLETED';status.currentStage='complete';status.outputFileExists=true;status.runtimeSeconds=actual;status.all11Scenes='PASS';status.audio='PASS';status.visualTheme='LIGHT_EXECUTIVE';status.progressiveReveal='PASS';status.maxTransitionSeconds=TRANSITION;status.export='1920x1080 H.264 AAC 30fps';status.goGreen=actual>=495&&actual<=525;status.finishedAt=now();status.lastSuccessfulStep='final_v4_mp4_created';status.lastLogActivity={at:now(),event:`Final V4 MP4 created: ${OUTPUT}`};writeStatus(status);console.log(JSON.stringify(status,null,2));}catch(e){status.processState='FAILED';status.error=e.message;status.finishedAt=now();status.outputFileExists=fs.existsSync(OUTPUT);status.lastLogActivity={at:now(),event:e.message};writeStatus(status);console.error(JSON.stringify(status,null,2));process.exitCode=2;}}
if(require.main===module)main();
module.exports={main};
