'use strict';

const fs=require('fs');
const path=require('path');
const {spawnSync}=require('child_process');
const {chromium}=require('playwright');

const ROOT=path.resolve(__dirname,'..');
const MASTER=path.join(ROOT,'DATA','production_specs','p2gc_reusable_demo_master.json');
const WORK=path.join(ROOT,'DATA','reusable_demo','v5');
const AUDIO=path.join(WORK,'audio');
const FRAMES=path.join(WORK,'frames');
const SEGMENTS=path.join(WORK,'segments');
const EXPORT_DIR=path.join(ROOT,'DATA','reusable_demo','exports');
const OUTPUT=path.join(EXPORT_DIR,'P2GC_Federal_Growth_Review_Demo_V5.mp4');
const STATUS=path.join(ROOT,'DATA','operational_acceptance','latest_p2gc_v5_render.json');
const FFMPEG=path.join(ROOT,'TOOLS','ffmpeg','bin','ffmpeg.exe');
const FFPROBE=path.join(ROOT,'TOOLS','ffmpeg','bin','ffprobe.exe');
const VOICE='en-US-GuyNeural';
const RATE='-8%';
const REVEAL_FADE=0.18;
const BETWEEN_CHUNK_HOLD=0.10;
const BETWEEN_SCENE_HOLD=0.18;

const now=()=>new Date().toISOString();
const clean=v=>String(v==null?'':v).trim();
const esc=s=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
function ensure(p){fs.mkdirSync(p,{recursive:true});}
function writeStatus(s){ensure(path.dirname(STATUS));s.updatedAt=now();fs.writeFileSync(STATUS,JSON.stringify(s,null,2),'utf8');}
function run(exe,args,opts={}){const r=spawnSync(exe,args,{cwd:ROOT,encoding:'utf8',windowsHide:true,timeout:opts.timeout||900000,maxBuffer:24*1024*1024});return{ok:r.status===0,code:r.status,stdout:r.stdout||'',stderr:r.stderr||'',error:r.error?r.error.message:null};}
function py(){for(const p of ['py.exe','python.exe','python']){const r=run(p,['--version'],{timeout:10000});if(r.ok)return p;}return null;}
function probeDuration(file){const r=run(FFPROBE,['-v','error','-show_entries','format=duration','-of','default=noprint_wrappers=1:nokey=1',file],{timeout:30000});if(!r.ok)throw new Error('FFPROBE_DURATION_FAILED:'+clean(r.stderr||r.error));const n=Number(clean(r.stdout));if(!Number.isFinite(n)||n<=0)throw new Error('INVALID_MEDIA_DURATION:'+file);return n;}
function ensureEdgeTts(status){const p=py();if(!p)throw new Error('PYTHON_NOT_FOUND_FOR_EDGE_TTS');let r=run(p,['-m','edge_tts','--help'],{timeout:30000});if(!r.ok){status.lastLogActivity={at:now(),event:'Provisioning zero-cost edge-tts neural voice package'};writeStatus(status);r=run(p,['-m','pip','install','--user','edge-tts'],{timeout:300000});if(!r.ok)throw new Error('EDGE_TTS_INSTALL_FAILED:'+clean(r.stderr||r.error).slice(-2500));r=run(p,['-m','edge_tts','--help'],{timeout:30000});if(!r.ok)throw new Error('EDGE_TTS_VERIFY_FAILED:'+clean(r.stderr||r.error).slice(-1500));}return p;}
function splitSentences(text){const a=clean(text).match(/[^.!?]+[.!?]+|[^.!?]+$/g)||[];return a.map(s=>clean(s)).filter(Boolean);}
function splitLongSentence(s){const parts=s.split(/(?<=[,;:])\s+|\s+[—–-]\s+/).map(clean).filter(Boolean);return parts.length>1?parts:[s];}
function narrationChunks(text){let units=splitSentences(text);const out=[];for(const u of units){const words=u.split(/\s+/).filter(Boolean);if(words.length>34){const p=splitLongSentence(u);if(p.length>1){out.push(...p);continue;}}out.push(u);}return out.filter(Boolean);}
function keyLine(text){let s=clean(text);if(s.length<=165)return s;const cut=s.slice(0,165);const i=Math.max(cut.lastIndexOf(','),cut.lastIndexOf(';'),cut.lastIndexOf(' '));return cut.slice(0,i>90?i:165)+'…';}
function bigValue(text){const m=text.match(/(?:\$?\d+(?:\.\d+)?\s*(?:million|thousand|percent|%|out of 100)|\$\d+(?:\.\d+)?[MK]?|\b\d+\s+qualified paths\b)/i);return m?m[0]:null;}
function ttsChunk(pyExe,sceneNo,chunkNo,text,status){const base=`scene_${String(sceneNo).padStart(2,'0')}_chunk_${String(chunkNo).padStart(2,'0')}`;const raw=path.join(AUDIO,base+'_raw.mp3');const trimmed=path.join(AUDIO,base+'.wav');if(fs.existsSync(trimmed)&&fs.statSync(trimmed).size>10000)return{file:trimmed,duration:probeDuration(trimmed),text};let r=run(pyExe,['-m','edge_tts','--voice',VOICE,'--rate',RATE,'--text',text,'--write-media',raw],{timeout:300000});if(!r.ok)throw new Error(`SCENE_${sceneNo}_CHUNK_${chunkNo}_NEURAL_TTS_FAILED:${clean(r.stderr||r.error).slice(-2500)}`);r=run(FFMPEG,['-y','-i',raw,'-af','silenceremove=start_periods=1:start_duration=0.05:start_threshold=-48dB:stop_periods=-1:stop_duration=0.16:stop_threshold=-48dB','-ar','48000','-ac','2','-c:a','pcm_s16le',trimmed],{timeout:120000});if(!r.ok)throw new Error(`SCENE_${sceneNo}_CHUNK_${chunkNo}_SILENCE_TRIM_FAILED:${clean(r.stderr||r.error).slice(-2500)}`);const duration=probeDuration(trimmed);if(duration<0.8)throw new Error(`SCENE_${sceneNo}_CHUNK_${chunkNo}_AUDIO_TOO_SHORT:${duration}`);status.currentScene=sceneNo;status.currentChunk=chunkNo;status.lastSuccessfulStep=`scene_${sceneNo}_chunk_${chunkNo}_audio`;status.lastLogActivity={at:now(),event:`Scene ${sceneNo} chunk ${chunkNo} narration ready (${duration.toFixed(2)}s)`};writeStatus(status);return{file:trimmed,duration,text};}
function svgFor(scene,chunk,chunkNo,total){const primary=keyLine(chunk);const metric=bigValue(chunk);const progressW=1580*(chunkNo/total);const metricBlock=metric?`<rect x="170" y="300" width="520" height="150" rx="28" fill="#eef5ff" stroke="#bed2f7"/><text x="430" y="360" text-anchor="middle" font-family="Arial" font-size="24" font-weight="700" fill="#526987">KEY POINT</text><text x="430" y="420" text-anchor="middle" font-family="Arial" font-size="44" font-weight="800" fill="#214e91">${esc(metric)}</text>`:'';const textX=metric?760:230;const textW=metric?900:1460;const size=primary.length>135?34:primary.length>95?39:46;const q=chunkNo===total&&scene.selfDiagnosis?`<rect x="170" y="855" width="1580" height="98" rx="26" fill="#eef5ff" stroke="#bed2f7"/><text x="960" y="915" text-anchor="middle" font-family="Arial" font-size="26" font-weight="700" fill="#214e91">${esc(scene.selfDiagnosis)}</text>`:'';return `<svg xmlns="http://www.w3.org/2000/svg" width="1920" height="1080"><rect width="1920" height="1080" fill="#f7f9fc"/><rect x="0" y="0" width="1920" height="16" fill="#2f6fed"/><text x="170" y="118" font-family="Arial" font-size="48" font-weight="800" fill="#10233f">${esc(scene.title)}</text><text x="170" y="165" font-family="Arial" font-size="21" font-weight="700" fill="#6c7e94">P2GC FEDERAL GROWTH REVIEW • FICTIONAL DEMONSTRATION</text><line x1="170" y1="205" x2="1750" y2="205" stroke="#d9e2ef" stroke-width="2"/>${metricBlock}<rect x="${textX}" y="${metric?300:290}" width="${textW}" height="${metric?330:370}" rx="30" fill="#ffffff" stroke="#d9e2ef" stroke-width="2"/><rect x="${textX}" y="${metric?300:290}" width="12" height="${metric?330:370}" rx="6" fill="#2f6fed"/><foreignObject x="${textX+60}" y="${metric?350:340}" width="${textW-120}" height="${metric?230:270}"><div xmlns="http://www.w3.org/1999/xhtml" style="font-family:Arial;color:#13233a;font-size:${size}px;font-weight:750;line-height:1.28;display:flex;align-items:center;height:100%;">${esc(primary)}</div></foreignObject>${q}<rect x="170" y="1002" width="1580" height="6" rx="3" fill="#dce5f2"/><rect x="170" y="1002" width="${progressW.toFixed(1)}" height="6" rx="3" fill="#2f6fed"/><text x="1750" y="1035" text-anchor="end" font-family="Arial" font-size="18" fill="#7b8da6">Pathways 2 Government Contracting</text></svg>`;}
async function renderFrame(page,scene,chunk,chunkNo,total){const svg=svgFor(scene,chunk,chunkNo,total);await page.setContent(`<html><body style="margin:0;background:#f7f9fc;overflow:hidden">${svg}</body></html>`,{waitUntil:'domcontentloaded',timeout:120000});const out=path.join(FRAMES,`scene_${String(scene.scene).padStart(2,'0')}_chunk_${String(chunkNo).padStart(2,'0')}.png`);await page.screenshot({path:out,clip:{x:0,y:0,width:1920,height:1080},timeout:120000});return out;}
function buildChunkVideo(sceneNo,chunkNo,frame,audio,audioDuration,isLastInScene){const hold=isLastInScene?BETWEEN_SCENE_HOLD:BETWEEN_CHUNK_HOLD;const duration=audioDuration+hold;const out=path.join(SEGMENTS,`scene_${String(sceneNo).padStart(2,'0')}_chunk_${String(chunkNo).padStart(2,'0')}.mp4`);const fadeOutStart=Math.max(0,duration-0.10);const r=run(FFMPEG,['-y','-loop','1','-framerate','30','-i',frame,'-i',audio,'-filter_complex',`[0:v]scale=1920:1080,format=yuv420p,fade=t=in:st=0:d=${REVEAL_FADE},fade=t=out:st=${fadeOutStart.toFixed(3)}:d=0.10[v];[1:a]apad=pad_dur=${hold.toFixed(3)},atrim=0:${duration.toFixed(3)}[a]`,'-map','[v]','-map','[a]','-t',duration.toFixed(3),'-r','30','-c:v','libx264','-preset','medium','-crf','20','-c:a','aac','-b:a','192k','-ar','48000','-ac','2','-movflags','+faststart',out],{timeout:600000});if(!r.ok)throw new Error(`SCENE_${sceneNo}_CHUNK_${chunkNo}_VIDEO_FAILED:${clean(r.stderr||r.error).slice(-3000)}`);return{file:out,duration};}
function concatFiles(files,out){const list=path.join(SEGMENTS,'v5_concat.txt');fs.writeFileSync(list,files.map(f=>`file '${f.replace(/'/g,"'\\''")}'`).join('\r\n'),'utf8');let r=run(FFMPEG,['-y','-f','concat','-safe','0','-i',list,'-c','copy',out],{timeout:1200000});if(!r.ok)r=run(FFMPEG,['-y','-f','concat','-safe','0','-i',list,'-r','30','-c:v','libx264','-preset','medium','-crf','20','-c:a','aac','-b:a','192k','-ar','48000','-ac','2','-movflags','+faststart',out],{timeout:1200000});if(!r.ok)throw new Error('FINAL_V5_CONCAT_FAILED:'+clean(r.stderr||r.error).slice(-3500));}
async function main(){const status={ok:false,phase:'V5_SPEECH_SYNC_RENDER',processState:'RUNNING',currentStage:'setup',currentScene:1,currentChunk:1,startedAt:now(),outputFile:OUTPUT,voice:VOICE,voiceRate:RATE,revealFadeSeconds:REVEAL_FADE,betweenChunkHoldSeconds:BETWEEN_CHUNK_HOLD,betweenSceneHoldSeconds:BETWEEN_SCENE_HOLD,error:null};writeStatus(status);let browser=null;try{if(!fs.existsSync(FFMPEG)||!fs.existsSync(FFPROBE))throw new Error('PROJECT_FFMPEG_OR_FFPROBE_MISSING');ensure(AUDIO);ensure(FRAMES);ensure(SEGMENTS);ensure(EXPORT_DIR);const master=JSON.parse(fs.readFileSync(MASTER,'utf8').replace(/^\uFEFF/,''));if(!Array.isArray(master.scenes)||master.scenes.length!==11)throw new Error('APPROVED_SCENE_COUNT_INVALID');const pyExe=ensureEdgeTts(status);browser=await chromium.launch({headless:true,channel:'chrome'});const page=await browser.newPage({viewport:{width:1920,height:1080}});const outputs=[];let expectedTotal=0;let totalChunks=0;for(const scene of master.scenes){const chunks=narrationChunks(scene.narration);if(!chunks.length)throw new Error(`SCENE_${scene.scene}_NO_NARRATION_CHUNKS`);status.currentScene=scene.scene;status.currentStage='speech_sync';status.lastLogActivity={at:now(),event:`Scene ${scene.scene}: synchronizing ${chunks.length} narration-driven reveals`};writeStatus(status);for(let i=0;i<chunks.length;i++){const chunkNo=i+1;const audio=ttsChunk(pyExe,scene.scene,chunkNo,chunks[i],status);const frame=await renderFrame(page,scene,chunks[i],chunkNo,chunks.length);const seg=buildChunkVideo(scene.scene,chunkNo,frame,audio.file,audio.duration,chunkNo===chunks.length);outputs.push(seg.file);expectedTotal+=seg.duration;totalChunks++;status.lastSuccessfulStep=`scene_${scene.scene}_chunk_${chunkNo}_synced`;status.lastLogActivity={at:now(),event:`Scene ${scene.scene} chunk ${chunkNo}/${chunks.length} synced to narration (${seg.duration.toFixed(2)}s)`};writeStatus(status);}status.lastSuccessfulStep=`scene_${scene.scene}_speech_synced`;}
await browser.close();browser=null;status.currentStage='export';status.lastLogActivity={at:now(),event:`Concatenating ${totalChunks} speech-synced chunks across 11 scenes`};writeStatus(status);concatFiles(outputs,OUTPUT);if(!fs.existsSync(OUTPUT)||fs.statSync(OUTPUT).size<1000000)throw new Error('FINAL_V5_MP4_MISSING_OR_TOO_SMALL');const actual=probeDuration(OUTPUT);status.ok=true;status.processState='COMPLETED';status.currentStage='complete';status.outputFileExists=true;status.runtimeSeconds=actual;status.expectedRuntimeSeconds=expectedTotal;status.all11Scenes='PASS';status.audio='PASS';status.visualNarrationSync='PASS';status.topicTransitionHoldMaxSeconds=BETWEEN_SCENE_HOLD;status.progressiveReveal='NARRATION_DRIVEN';status.export='1920x1080 H.264 AAC 30fps';status.goGreen=true;status.finishedAt=now();status.lastSuccessfulStep='final_v5_mp4_created';status.lastLogActivity={at:now(),event:`Final V5 speech-synced MP4 created: ${OUTPUT}`};writeStatus(status);console.log(JSON.stringify(status,null,2));}catch(e){if(browser){try{await browser.close();}catch{}}status.processState='FAILED';status.error=e.message;status.finishedAt=now();status.outputFileExists=fs.existsSync(OUTPUT);status.lastLogActivity={at:now(),event:e.message};writeStatus(status);console.error(JSON.stringify(status,null,2));process.exitCode=2;}}
if(require.main===module)main();
module.exports={main};
