'use strict';
require('dotenv').config({quiet:true});
const fs=require('fs'),path=require('path');
const {chromium}=require('playwright');
const Lifecycle=require('../SERVICES/revenue/P2GCFederalGrowthReviewLifecycleService');
const VideoProvider=require('../SERVICES/revenue/P2GCFederalGrowthReviewVideoProviderService');
const SegmentPlanner=require('../SERVICES/revenue/P2GCGoogleVidsSegmentPlannerService');
const ROOT=path.resolve(__dirname,'..');
const PROFILE=path.join(ROOT,'DATA','browser','profiles','miles-chrome');
const REVIEW_DIR=path.join(ROOT,'DATA','federal_growth_reviews');
const OUT=path.join(ROOT,'DATA','operational_acceptance','latest_p2gc_demo_video_finalization.json');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const clean=v=>String(v==null?'':v).trim();
function readJson(f){try{return JSON.parse(fs.readFileSync(f,'utf8').replace(/^\uFEFF/,''));}catch{return null;}}
function write(x){fs.mkdirSync(path.dirname(OUT),{recursive:true});fs.writeFileSync(OUT,JSON.stringify(x,null,2),'utf8');}
function latestReview(){const rows=fs.readdirSync(REVIEW_DIR).filter(x=>x.endsWith('.json')).map(n=>{const f=path.join(REVIEW_DIR,n),r=readJson(f);let m=0;try{m=fs.statSync(f).mtimeMs}catch{}return{r,m};}).filter(x=>x.r&&clean(x.r.presentation?.script)&&x.r.stageState?.PERSONALIZED_SCRIPT?.status==='COMPLETE');rows.sort((a,b)=>Math.max(Date.parse(b.r.updatedAt||0)||0,b.m)-Math.max(Date.parse(a.r.updatedAt||0)||0,a.m));if(!rows.length)throw new Error('NO_PERSONALIZED_REVIEW_READY_FOR_VIDEO');return rows[0].r;}
async function click(root,re){const q=root.locator('button,[role="button"],[aria-label]');for(let i=0,n=await q.count().catch(()=>0);i<n;i++){const l=q.nth(i);if(!(await l.isVisible().catch(()=>false))||!(await l.isEnabled().catch(()=>true)))continue;const s=[await l.innerText().catch(()=>''),await l.getAttribute('aria-label').catch(()=>''),await l.getAttribute('title').catch(()=>'' )].join(' ');if(!re.test(s))continue;try{await l.click({timeout:5000});return{ok:true,label:clean(s),index:i};}catch{}}return{ok:false};}
async function clickEverywhere(page,re){let r=await click(page,re);if(r.ok)return{...r,root:'main'};const ds=page.locator('[role="dialog"]');for(let i=(await ds.count().catch(()=>0))-1;i>=0;i--){r=await click(ds.nth(i),re);if(r.ok)return{...r,root:`dialog-${i}`};}for(const f of page.frames()){if(f===page.mainFrame())continue;r=await click(f,re);if(r.ok)return{...r,root:f.url()};}return{ok:false};}
async function fill(root,text){for(const s of ['textarea','[role="textbox"]','[contenteditable="true"]','input[placeholder*="script" i]','input[type="text"]']){const q=root.locator(s);for(let i=0,n=await q.count().catch(()=>0);i<n;i++){const l=q.nth(i);if(!(await l.isVisible().catch(()=>false)))continue;try{await l.fill(text).catch(async()=>{await l.click();await l.press('Control+A').catch(()=>{});await l.pressSequentially(text,{delay:0});});const v=await l.inputValue().catch(()=>l.innerText().catch(()=>''));if(clean(v).length>=Math.min(20,text.length))return{ok:true,selector:s,index:i};}catch{}}}return{ok:false};}
async function fillEverywhere(page,text){let r=await fill(page,text);if(r.ok)return{...r,root:'main'};for(const f of page.frames()){if(f===page.mainFrame())continue;r=await fill(f,text);if(r.ok)return{...r,root:f.url()};}return{ok:false};}
async function accountHint(page){const a=await page.locator('[aria-label]').evaluateAll(ns=>ns.map(n=>n.getAttribute('aria-label')).filter(Boolean)).catch(()=>[]);for(const v of a){const m=String(v).match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i);if(m)return m[0].toLowerCase();}return null;}
async function account(page){for(let slot=0;slot<12;slot++){await page.goto(`https://docs.google.com/videos/u/${slot}/`,{waitUntil:'domcontentloaded',timeout:60000});await sleep(1300);const email=await accountHint(page);if(email&&/@pathways(?:gsa|gov|govcon|federal|togc|2gc\.co)/i.test(email))return{slot,email};}throw new Error('NO_PATHWAYS_GOOGLE_VIDS_SESSION');}
async function ensureEditor(page,slot){await page.goto('https://vids.new',{waitUntil:'domcontentloaded',timeout:60000});await sleep(6000);if(/\/videos\/d\//i.test(page.url()))return;if((await clickEverywhere(page,/\bLandscape\b/i)).ok){await sleep(7000);return;}await page.goto(`https://docs.google.com/videos/u/${slot}/`,{waitUntil:'domcontentloaded',timeout:60000});await sleep(2200);await clickEverywhere(page,/Create new video/i);await sleep(4000);await clickEverywhere(page,/\bLandscape\b/i);await sleep(7000);}
async function addSegment(page,seg,res){if(!(await clickEverywhere(page,/Generate an avatar|\bAvatar\b/i)).ok)throw new Error(`SEGMENT_${seg.index}_AVATAR_CONTROL_NOT_FOUND`);await sleep(1800);await clickEverywhere(page,/Have your avatar present|AI avatar/i);await sleep(2200);res.lastFill=await fillEverywhere(page,seg.text||seg.script);write(res);if(!res.lastFill.ok)throw new Error(`SEGMENT_${seg.index}_SCRIPT_INPUT_NOT_FOUND`);res.lastGenerate=await clickEverywhere(page,/\bGenerate\b|\bCreate\b/i);write(res);if(!res.lastGenerate.ok)throw new Error(`SEGMENT_${seg.index}_GENERATE_CONTROL_NOT_FOUND`);let done=false,start=Date.now();while(Date.now()-start<180000){await sleep(3500);const body=(await Promise.all(page.frames().map(f=>f.locator('body').innerText().catch(()=>'')))).join('\n');if(/insert|add to scene|use this|done|generated/i.test(body)&&!/generating|creating/i.test(body)){done=true;break;}}if(!done)throw new Error(`SEGMENT_${seg.index}_GENERATION_TIMEOUT`);await clickEverywhere(page,/Insert|Add to scene|Use this/i);res.completedSegments=seg.index;write(res);if(seg.index<res.segmentPlan.segmentCount){await clickEverywhere(page,/New scene/i);await sleep(1200);}}
async function exportMp4(page,res){await clickEverywhere(page,/^File$/i);await sleep(700);const p=page.waitForEvent('download',{timeout:120000}).catch(()=>null);if(!(await clickEverywhere(page,/Download|Export/i)).ok)throw new Error('VIDEO_EXPORT_CONTROL_NOT_FOUND');const dl=await p;if(!dl)throw new Error('VIDEO_EXPORT_DOWNLOAD_NOT_OBSERVED');const dir=path.join(ROOT,'DATA','federal_growth_review_media','exports');fs.mkdirSync(dir,{recursive:true});let name=dl.suggestedFilename()||`P2GC_Demo_${Date.now()}.mp4`;if(!name.toLowerCase().endsWith('.mp4'))name+='.mp4';const target=path.join(dir,name);await dl.saveAs(target);const bytes=fs.statSync(target).size;if(bytes<10000)throw new Error('VIDEO_EXPORT_ARTIFACT_INVALID');res.mp4Path=target;res.mp4Bytes=bytes;}
async function main(){const res={ok:false,status:'STARTED',startedAt:new Date().toISOString(),completedSegments:0};write(res);let ctx;try{const review=latestReview();res.reviewId=review.reviewId;res.company=review.company;const lifecycle=new Lifecycle({rootDir:ROOT});const provider=new VideoProvider({rootDir:ROOT,lifecycle});const p=provider.prepareReview(review.reviewId);res.providerDecision=p;if(p.provider!=='GOOGLE_VIDS')throw new Error(`GOOGLE_VIDS_REQUIRED_CURRENT_PROVIDER_${p.provider||'NONE'}`);res.segmentPlan=new SegmentPlanner({wordsPerMinute:135,maxSeconds:28}).plan(review.presentation);write(res);ctx=await chromium.launchPersistentContext(PROFILE,{headless:true,channel:'chrome',acceptDownloads:true,viewport:{width:1440,height:1000},args:['--disable-blink-features=AutomationControlled']});const page=ctx.pages()[0]||await ctx.newPage();res.googleAccount=await account(page);await ensureEditor(page,res.googleAccount.slot);for(const seg of res.segmentPlan.segments)await addSegment(page,seg,res);await exportMp4(page,res);res.ok=true;res.status='MP4_EXPORTED';res.finishedAt=new Date().toISOString();write(res);console.log(JSON.stringify(res,null,2));}catch(e){res.status='FAILED';res.error=e.message;res.finishedAt=new Date().toISOString();write(res);console.error(JSON.stringify(res,null,2));process.exitCode=2;}finally{try{await ctx?.close();}catch{}}}
if(require.main===module)main();
module.exports={main};
