'use strict';
require('dotenv').config({quiet:true});
const fs=require('fs');
const path=require('path');
const {spawnSync}=require('child_process');
const {chromium}=require('playwright');
const ROOT=path.resolve(__dirname,'..');
const PROFILE=path.join(ROOT,'DATA','browser','profiles','miles-chrome');
const MANIFEST=path.join(ROOT,'DATA','reusable_demo','manifest.json');
const OUT=path.join(ROOT,'DATA','operational_acceptance','latest_p2gc_reusable_demo_video.json');
const SHOTS=path.join(ROOT,'DATA','operational_acceptance','p2gc_reusable_demo_evidence');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const clean=v=>String(v==null?'':v).trim();
function write(o){fs.mkdirSync(path.dirname(OUT),{recursive:true});fs.writeFileSync(OUT,JSON.stringify(o,null,2),'utf8');}
function run(script){const p=spawnSync(process.execPath,[path.join(ROOT,'SCRIPTS',script)],{cwd:ROOT,encoding:'utf8',windowsHide:true,timeout:120000});if(p.status!==0)throw new Error(`ASSET_BUILD_FAILED:${clean(p.stderr||p.stdout).slice(-1200)}`);}
async function snapshot(page,label,res){fs.mkdirSync(SHOTS,{recursive:true});const file=path.join(SHOTS,`${Date.now()}_${label}.png`);await page.screenshot({path:file,fullPage:true}).catch(()=>{});const body=await page.locator('body').innerText().catch(()=>'');const controls=await page.locator('button,[role="button"],[role="menuitem"],[aria-label],input,textarea,[contenteditable="true"]').evaluateAll(ns=>ns.map((n,i)=>({i,tag:n.tagName,text:(n.innerText||n.textContent||'').trim().replace(/\s+/g,' ').slice(0,160),aria:n.getAttribute('aria-label'),placeholder:n.getAttribute('placeholder'),title:n.getAttribute('title')})).filter(x=>x.text||x.aria||x.placeholder||x.title).slice(0,400)).catch(()=>[]);res.snapshots.push({label,file,url:page.url(),body:body.slice(0,12000),controls});write(res);}
async function clickRoot(root,re){const q=root.locator('button,[role="button"],[role="menuitem"],[role="option"],[aria-label],div,span');for(let i=0,n=await q.count().catch(()=>0);i<n;i++){const l=q.nth(i);if(!(await l.isVisible().catch(()=>false)))continue;const s=[await l.innerText().catch(()=>''),await l.getAttribute('aria-label').catch(()=>''),await l.getAttribute('title').catch(()=>'' )].join(' ').replace(/\s+/g,' ').trim();if(!re.test(s))continue;try{await l.click({timeout:5000});return{ok:true,label:clean(s),index:i};}catch{}}return{ok:false};}
async function clickAny(page,re){let r=await clickRoot(page,re);if(r.ok)return{...r,root:'main'};const ds=page.locator('[role="dialog"]');for(let i=(await ds.count().catch(()=>0))-1;i>=0;i--){r=await clickRoot(ds.nth(i),re);if(r.ok)return{...r,root:`dialog-${i}`};}for(const f of page.frames()){if(f===page.mainFrame())continue;r=await clickRoot(f,re);if(r.ok)return{...r,root:f.url()};}return{ok:false};}
async function clickExactTextRoot(root,text){const candidates=[root.getByText(text,{exact:true}),root.locator(`[aria-label="${text.replace(/"/g,'\\"')}"]`)];for(const q of candidates){for(let i=0,n=await q.count().catch(()=>0);i<n;i++){const l=q.nth(i);if(!(await l.isVisible().catch(()=>false)))continue;try{await l.click({timeout:5000});return{ok:true,text,index:i};}catch{}}}return{ok:false};}
async function clickExactText(page,text){let r=await clickExactTextRoot(page,text);if(r.ok)return{...r,root:'main'};for(const f of page.frames()){if(f===page.mainFrame())continue;r=await clickExactTextRoot(f,text);if(r.ok)return{...r,root:f.url()};}return{ok:false};}
async function fillAny(page,text){const sels=['textarea','[role="textbox"]','[contenteditable="true"]','input[type="text"]'];for(const root of [page,...page.frames().filter(f=>f!==page.mainFrame())])for(const s of sels){const q=root.locator(s);for(let i=0,n=await q.count().catch(()=>0);i<n;i++){const l=q.nth(i);if(!(await l.isVisible().catch(()=>false)))continue;try{await l.fill(text).catch(async()=>{await l.click();await l.press('Control+A').catch(()=>{});await l.pressSequentially(text,{delay:0});});const v=await l.inputValue().catch(()=>l.innerText().catch(()=>''));if(clean(v).length>=Math.min(20,text.length))return{ok:true,selector:s,index:i,root:root===page?'main':root.url()};}catch{}}}return{ok:false};}
async function accountHint(page){const vals=await page.locator('[aria-label]').evaluateAll(ns=>ns.map(n=>n.getAttribute('aria-label')).filter(Boolean)).catch(()=>[]);for(const v of vals){const m=String(v).match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i);if(m)return m[0].toLowerCase();}return null;}
async function chooseAccount(page){for(let slot=0;slot<12;slot++){await page.goto(`https://docs.google.com/videos/u/${slot}/`,{waitUntil:'domcontentloaded',timeout:60000});await sleep(1300);const email=await accountHint(page);if(email&&/@pathways(?:gsa|gov|govcon|federal|togc|2gc\.co)/i.test(email))return{slot,email};}throw new Error('NO_PATHWAYS_GOOGLE_VIDS_SESSION');}
async function ensureEditor(page,slot){await page.goto('https://vids.new',{waitUntil:'domcontentloaded',timeout:60000});await sleep(6500);if(/\/videos\/d\//i.test(page.url()))return;if((await clickAny(page,/Create a landscape video|\bLandscape\b/i)).ok){await sleep(7000);return;}await page.goto(`https://docs.google.com/videos/u/${slot}/`,{waitUntil:'domcontentloaded',timeout:60000});await sleep(2000);await clickAny(page,/Create new video/i);await sleep(4000);if(!(await clickAny(page,/Create a landscape video|\bLandscape\b/i)).ok)throw new Error('GOOGLE_VIDS_LANDSCAPE_CREATE_NOT_FOUND');await sleep(7000);}
async function setExistingFileInput(page,file){for(const root of [page,...page.frames().filter(f=>f!==page.mainFrame())]){const inputs=root.locator('input[type="file"]');const n=await inputs.count().catch(()=>0);if(n){await inputs.last().setInputFiles(file);return true;}}return false;}
async function chooserExact(page,text,file){const p=page.waitForEvent('filechooser',{timeout:12000}).catch(()=>null);const c=await clickExactText(page,text);if(!c.ok)return false;const chooser=await p;if(!chooser)return false;await chooser.setFiles(file);return true;}
async function uploadSceneImage(page,file){
  if(await setExistingFileInput(page,file)){await sleep(5000);await clickAny(page,/Insert|Add to scene|Use|Add/i);await sleep(2200);return;}
  const insert=(await clickExactText(page,'Insert')).ok || (await clickAny(page,/^Insert$/i)).ok;
  if(insert)await sleep(700);
  const image=(await clickExactText(page,'Image')).ok || (await clickAny(page,/^Image$/i)).ok;
  if(image)await sleep(700);
  let uploaded=false;
  for(const label of ['Upload from computer','Upload from device','Upload image','Choose image','Browse']){if(await chooserExact(page,label,file)){uploaded=true;break;}}
  if(!uploaded){for(const label of ['Uploads','Upload']){if((await clickExactText(page,label)).ok){await sleep(700);for(const sub of ['Upload from computer','Upload files','Choose files','Select files','Browse','From computer']){if(await chooserExact(page,sub,file)){uploaded=true;break;}}if(uploaded)break;}}}
  if(!uploaded)uploaded=await setExistingFileInput(page,file);
  if(!uploaded)throw new Error(`GOOGLE_VIDS_IMAGE_UPLOAD_PATH_NOT_FOUND:insert=${insert}:image=${image}`);
  await sleep(5000);await clickAny(page,/Insert|Add to scene|Use|Add/i);await sleep(2200);
}
async function generateTextFeature(page,featureRe,text,res,label){if(!(await clickAny(page,featureRe)).ok)throw new Error(`${label}_CONTROL_NOT_FOUND`);await sleep(1600);const fill=await fillAny(page,text);res.lastFill={label,...fill};write(res);if(!fill.ok)throw new Error(`${label}_TEXT_INPUT_NOT_FOUND`);const gen=await clickAny(page,/\bGenerate\b|\bCreate\b/i);res.lastGenerate={label,...gen};write(res);if(!gen.ok)throw new Error(`${label}_GENERATE_NOT_FOUND`);let done=false,start=Date.now();while(Date.now()-start<180000){await sleep(3500);const body=(await Promise.all(page.frames().map(f=>f.locator('body').innerText().catch(()=>'')))).join('\n');if(/insert|add to scene|use this|done|generated|ready/i.test(body)&&!/generating|creating/i.test(body)){done=true;break;}}if(!done)throw new Error(`${label}_GENERATION_TIMEOUT`);await clickAny(page,/Insert|Add to scene|Use this|Add/i);await sleep(1800);}
function splitAvatar(text,seconds){const words=clean(text).split(/\s+/);const count=Math.max(1,Math.round(seconds*135/60));return {avatar:words.slice(0,count).join(' '),remainder:words.slice(count).join(' ')};}
async function newScene(page){if(!(await clickAny(page,/New scene/i)).ok)throw new Error('NEW_SCENE_CONTROL_NOT_FOUND');await sleep(1800);}
async function exportMp4(page,res){await clickAny(page,/^File$/i);await sleep(800);const promise=page.waitForEvent('download',{timeout:180000}).catch(()=>null);if(!(await clickAny(page,/Download as MP4|Download|Export/i)).ok)throw new Error('VIDEO_EXPORT_CONTROL_NOT_FOUND');const dl=await promise;if(!dl)throw new Error('VIDEO_EXPORT_DOWNLOAD_NOT_OBSERVED');const dir=path.join(ROOT,'DATA','reusable_demo','exports');fs.mkdirSync(dir,{recursive:true});let name=dl.suggestedFilename()||'P2GC_Federal_Growth_Review_Demo.mp4';if(!name.toLowerCase().endsWith('.mp4'))name+='.mp4';const target=path.join(dir,name);await dl.saveAs(target);const bytes=fs.statSync(target).size;if(bytes<10000)throw new Error('VIDEO_EXPORT_ARTIFACT_INVALID');res.mp4Path=target;res.mp4Bytes=bytes;}
async function main(){const res={ok:false,status:'STARTED',startedAt:new Date().toISOString(),completedScene:0,snapshots:[]};write(res);let ctx;try{run('BuildP2GCReusableDemoAssets.js');const manifest=JSON.parse(fs.readFileSync(MANIFEST,'utf8'));res.assetCount=manifest.assetCount;res.targetRuntimeSeconds=manifest.targetRuntimeSeconds;res.sceneAssets=manifest.assets.map(a=>({scene:a.scene,pngFile:a.pngFile,durationSeconds:a.durationSeconds,avatarSeconds:a.avatarSeconds}));write(res);ctx=await chromium.launchPersistentContext(PROFILE,{headless:true,channel:'chrome',acceptDownloads:true,viewport:{width:1440,height:1000},args:['--disable-blink-features=AutomationControlled']});const page=ctx.pages()[0]||await ctx.newPage();res.googleAccount=await chooseAccount(page);await ensureEditor(page,res.googleAccount.slot);await snapshot(page,'editor_ready',res);
 for(const a of manifest.assets){if(a.scene>1)await newScene(page);await uploadSceneImage(page,a.pngFile);if(a.avatarSeconds>0){const parts=splitAvatar(a.narration,a.avatarSeconds);await generateTextFeature(page,/Generate an avatar|\bAvatar\b/i,parts.avatar,res,`SCENE_${a.scene}_AVATAR`);if(clean(parts.remainder))await generateTextFeature(page,/Generate a voiceover|\bVoiceover\b/i,parts.remainder,res,`SCENE_${a.scene}_VOICEOVER`);}else{await generateTextFeature(page,/Generate a voiceover|\bVoiceover\b/i,a.narration,res,`SCENE_${a.scene}_VOICEOVER`);}res.completedScene=a.scene;write(res);await snapshot(page,`scene_${a.scene}_complete`,res);}
 await exportMp4(page,res);res.ok=true;res.status='MP4_EXPORTED';res.finishedAt=new Date().toISOString();write(res);console.log(JSON.stringify(res,null,2));}catch(e){res.status='FAILED';res.error=e.message;res.stack=e.stack;res.finishedAt=new Date().toISOString();write(res);console.error(JSON.stringify(res,null,2));process.exitCode=2;}finally{try{await ctx?.close();}catch{}}}
if(require.main===module)main();
module.exports={main};
