"use strict";
const crypto=require("crypto"),fs=require("fs"),path=require("path");
const CAPS={"Expiring GSA 12 Months":45,"GSA":15,"Expiring VA 12 Months":5,"VA":10,"8(a)":10,"HUBZone":10,"SDVOSB":30,"VOSB":15,"WOSB":20,"SBS":20};
const hash=v=>crypto.createHash("sha256").update(v).digest("hex").toUpperCase();
class RevenueLaunchCapacityPlanService{
 constructor(o={}){this.service="REVENUE_LAUNCH_CAPACITY_PLAN";this.rootDir=path.resolve(o.rootDir||process.env.MILES_ROOT||path.resolve(__dirname,"..",".."));this.readinessPath=o.readinessPath||path.join(this.rootDir,"DATA","runtime","revenue","outbound_readiness","manifest.json");this.outputRoot=o.outputRoot||path.join(this.rootDir,"DATA","runtime","revenue","launch_capacity");this.outputPath=o.outputPath||path.join(this.outputRoot,"plan.json");this.generatedAt=o.generatedAt||(()=>new Date().toISOString());this.campaignProvider=o.campaignProvider|| (async id=>require(path.join(this.rootDir,"CONNECTORS","INSTANTLY","instantly.js")).getCampaign(id));this.accountProvider=o.accountProvider|| (async()=>require(path.join(this.rootDir,"CONNECTORS","INSTANTLY","instantly.js")).listAccounts({limit:100}));}
 preview(){return{ok:true,service:this.service,mode:"PLAN_ONLY",status:"PLANNED",providerWritesAuthorized:false,emailsSent:false,campaignsLaunched:false};}
 load(){if(!fs.existsSync(this.readinessPath))throw new Error("Gate 22 readiness evidence is missing.");return JSON.parse(fs.readFileSync(this.readinessPath,"utf8").replace(/^\uFEFF/,""));}
 items(r){if(Array.isArray(r))return r;for(const k of["items","accounts","data","results"])if(Array.isArray(r?.[k]))return r[k];throw new Error("Account inventory is invalid.");}
 schedule(c){return c.campaign_schedule||c.campaignSchedule||null;}
 async build(input={}){if(input.apply!==true)return this.preview();if(input.live!==true)throw new Error("Explicit --live read authorization is required.");const readiness=this.load();if(readiness.ok!==true||readiness.readyToLaunch!==true||readiness.readinessFingerprint!=="F19860CAF895EE8955D1514F8F04F54954DD497D0FB1F5EC800CD7F20A33D5DB")throw new Error("Gate 22 readiness evidence changed.");const accounts=this.items(await this.accountProvider());const campaigns=[];for(const route of readiness.routes){const live=await this.campaignProvider(route.campaignId);campaigns.push({route:route.route,campaignId:route.campaignId,paused:route.paused,currentDailyLimit:Number(live.daily_limit??live.dailyLimit??0),currentDailyMaxLeads:Number(live.daily_max_leads??live.dailyMaxLeads??0),currentSchedule:this.schedule(live),proposedDailyLimit:CAPS[route.route],mustRemainPaused:true});}const reference=campaigns.find(x=>x.route==="SBS")?.currentSchedule||campaigns.find(x=>x.currentSchedule)?.currentSchedule||null;const blockers=[];if(!reference)blockers.push("VALID_PROVIDER_SCHEDULE_REQUIRED");if(Object.values(CAPS).reduce((a,b)=>a+b,0)!==180)blockers.push("CAP_CONSERVATION_FAILED");if(campaigns.some(x=>!x.paused))blockers.push("CAMPAIGN_NOT_PAUSED");const report={ok:true,service:this.service,mode:"APPLY_LIVE_READ_ONLY",status:"LAUNCH_CAPACITY_PLANNED",generatedAt:this.generatedAt(),sourceReadinessFingerprint:readiness.readinessFingerprint,readyForCapacityApply:blockers.length===0,summary:{campaigns:10,accountsRead:accounts.length,totalDailyCap:180,targetPerHealthyInbox:20},referenceSchedule:reference,campaigns,blockers,stopConditions:{bounceRatePercent:3,spamComplaintCount:1,senderHealthFailure:true,suppressionConflictCount:1,unexpectedCampaignActivation:true},monitoring:{initialObservationHours:72,reviewDaily:true},providerWritesAuthorized:false,emailsSent:false,campaignsChanged:false,campaignsLaunched:false,authorizationRequired:"AUTHORIZE_GATE_24_CAPACITY_CONFIGURATION_180_PER_DAY_NO_LAUNCH"};const identity={...report};delete identity.generatedAt;report.capacityFingerprint=hash(Buffer.from(JSON.stringify(identity)));fs.mkdirSync(this.outputRoot,{recursive:true});fs.writeFileSync(this.outputPath,JSON.stringify(report,null,2),"utf8");report.artifact={filePath:this.outputPath,sha256:hash(fs.readFileSync(this.outputPath))};return report;}}
module.exports=RevenueLaunchCapacityPlanService;module.exports.CAPS=CAPS;
